{
  "hash": "cbd227bed1ae008397af32ec41068e91",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Paired-Samples T-Test\"\nsubtitle: \"PSY 348: Lecture 10\"\nauthor: \"Dave Brocker\"\ninstitute: \"Farmingdale State College\"\nfooter: \"Paired-Samples T-Test | ⬡⬢⬡⬢⬡⬢\"\nformat:\n  revealjs:\n    theme: ../custom.scss\n    incremental: true\n    touch: true\n    chalkboard: true\n    lightbox: true\n    scrollable: true\n    code-fold: true\n    slide-number: c/t\n    include-after-body: ../title-bg.html\n    width: 1600\n    height: 900\n    drop:\n      engine: webr\nrevealjs-plugins:\n  - drop\n  - codewindow\n---\n\n\n\n## Introduction to Paired-Samples t-Test\n\n### What is a paired-samples t-test?\n\n::: hero-def\n\n[Paired-Samples t-Test]{.term-pill}\n\n: A statistical method for comparing the means of **two related** sets of scores, such as the same people measured twice.\n:::\n\n## Purpose of Paired-Samples t-Test\n\n### Why use it?\n\n- To determine whether there is a statistically significant difference between two related group means.\n\n- Useful in psychology for assessing change due to an intervention, therapy, or experiment.\n\n## Application of Paired-Samples t-Test\n\n### When to apply this test\n\n:::::: badge-row\n::: content-badge\n[trending_up]{.material-icons}\n\n#### Pretest-Posttest\n\nThe same group measured before and after\n:::\n\n::: content-badge\n[people]{.material-icons}\n\n#### Matched Pairs\n\nTwins or matched participants\n:::\n\n::: content-badge\n[repeat]{.material-icons}\n\n#### Repeated Measures\n\nThe same group under different conditions\n:::\n::::::\n\n## Connection to the One-Sample *t*-Test\n\n::: {.callout-important appearance=\"minimal\"}\nA **paired-samples t-test** is a **one-sample t-test on the difference scores**.\n:::\n\n::::::: columns\n:::: {.column width=\"50%\"}\n::: callout-tip\n## One-sample\n\n$t = \\dfrac{\\bar{x} - \\mu_0}{s / \\sqrt{n}}$\n\nIs the sample mean different from a known value?\n:::\n::::\n\n:::: {.column width=\"50%\"}\n::: callout-tip\n## Paired\n\n$t = \\dfrac{\\bar{D} - 0}{s_D / \\sqrt{n}}$\n\nIs the **mean difference** $\\bar{D}$ different from 0?\n:::\n::::\n:::::::\n\n## Formula for Paired-Samples t-Test\n\n### Mathematical representation\n\n::: callout-tip\n## Paired-Samples t-Test\n\n$\\large{t = \\dfrac{\\color{blue}{\\bar{D}}}{\\color{orange}{s_D}/\\sqrt{n}}}$\n:::\n\n- $\\color{blue}{\\bar{D}}$: mean of the differences between paired observations.\n\n- $\\color{orange}{s_D}$: standard deviation of the differences.\n\n- $n$: number of pairs.\n\n- Degrees of freedom: $df = n - 1$.\n\n## Theoretical Formula Explanation\n\n### Understanding each component\n\n:::::: term-list\n::: fragment\n\n[Mean difference $\\bar{D}$]{.term-pill}\n\n: The average of the differences between paired scores.\n:::\n\n::: fragment\n\n[SD of differences $s_D$]{.term-pill}\n\n: How much individual differences vary around the mean difference.\n:::\n\n::: fragment\n\n[Number of pairs $n$]{.term-pill}\n\n: A larger $n$ shrinks the standard error $s_D/\\sqrt{n}$, so smaller differences can reach significance.\n:::\n::::::\n\n## Paired-Samples t-Test\n\n### Application in psychology research\n\n> A psychologist measures stress levels of a group before and after a mindfulness program. Participants first answer a stress survey, next they participate in a mindfulness exercise. After the exercise, their stress scores are measured again and compared.\n\n::: callout-tip\n## Steps\n\n1.  State the null and alternative hypotheses.\n2.  Calculate the difference between post- and pre-intervention scores.\n3.  Find the mean $\\bar{D}$ and standard deviation $s_D$ of the differences.\n4.  Apply the formula to calculate the t-value and check for significance.\n:::\n\n## Paired-Samples t-Test\n\n### Step 1: hypotheses\n\n::::::: columns\n:::: {.column width=\"50%\"}\n::: callout-tip\n## Null hypothesis $H_0$\n\nThere will be **no difference** in stress before and after the mindfulness exercise.\n\n$\\mu_\\text{post} = \\mu_\\text{pre}$, or equivalently $\\mu_D = 0$\n:::\n::::\n\n:::: {.column width=\"50%\"}\n::: callout-important\n## Alternative hypothesis $H_A$\n\nThere will be a **decrease** in stress after the mindfulness exercise.\n\n$\\mu_\\text{post} < \\mu_\\text{pre}$, or equivalently $\\mu_D < 0$\n:::\n::::\n:::::::\n\n## Paired-Samples t-Test\n\n### Each person has two scores\n\n::::: columns\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"rkrfhdamgw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rkrfhdamgw table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rkrfhdamgw thead, #rkrfhdamgw tbody, #rkrfhdamgw tfoot, #rkrfhdamgw tr, #rkrfhdamgw td, #rkrfhdamgw th {\n  border-style: none;\n}\n\n#rkrfhdamgw p {\n  margin: 0;\n  padding: 0;\n}\n\n#rkrfhdamgw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 24px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 95%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rkrfhdamgw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rkrfhdamgw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rkrfhdamgw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rkrfhdamgw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rkrfhdamgw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rkrfhdamgw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rkrfhdamgw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rkrfhdamgw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rkrfhdamgw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rkrfhdamgw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rkrfhdamgw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rkrfhdamgw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rkrfhdamgw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rkrfhdamgw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rkrfhdamgw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rkrfhdamgw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rkrfhdamgw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rkrfhdamgw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rkrfhdamgw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rkrfhdamgw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rkrfhdamgw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rkrfhdamgw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rkrfhdamgw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rkrfhdamgw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rkrfhdamgw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rkrfhdamgw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rkrfhdamgw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rkrfhdamgw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rkrfhdamgw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rkrfhdamgw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rkrfhdamgw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rkrfhdamgw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rkrfhdamgw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rkrfhdamgw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rkrfhdamgw .gt_left {\n  text-align: left;\n}\n\n#rkrfhdamgw .gt_center {\n  text-align: center;\n}\n\n#rkrfhdamgw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rkrfhdamgw .gt_font_normal {\n  font-weight: normal;\n}\n\n#rkrfhdamgw .gt_font_bold {\n  font-weight: bold;\n}\n\n#rkrfhdamgw .gt_font_italic {\n  font-style: italic;\n}\n\n#rkrfhdamgw .gt_super {\n  font-size: 65%;\n}\n\n#rkrfhdamgw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rkrfhdamgw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rkrfhdamgw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rkrfhdamgw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rkrfhdamgw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rkrfhdamgw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rkrfhdamgw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#rkrfhdamgw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#rkrfhdamgw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Participant\">Participant</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Pre\">Pre</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Post\">Post</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier;\">1</th>\n<td headers=\"stub_1_1 Participant\" class=\"gt_row gt_left\">P1</td>\n<td headers=\"stub_1_1 Pre\" class=\"gt_row gt_right\">10</td>\n<td headers=\"stub_1_1 Post\" class=\"gt_row gt_right\">7</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier;\">2</th>\n<td headers=\"stub_1_2 Participant\" class=\"gt_row gt_left gt_striped\">P2</td>\n<td headers=\"stub_1_2 Pre\" class=\"gt_row gt_right gt_striped\">7</td>\n<td headers=\"stub_1_2 Post\" class=\"gt_row gt_right gt_striped\">7</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier;\">3</th>\n<td headers=\"stub_1_3 Participant\" class=\"gt_row gt_left\">P3</td>\n<td headers=\"stub_1_3 Pre\" class=\"gt_row gt_right\">12</td>\n<td headers=\"stub_1_3 Post\" class=\"gt_row gt_right\">11</td></tr>\n    <tr><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier;\">4</th>\n<td headers=\"stub_1_4 Participant\" class=\"gt_row gt_left gt_striped\">P4</td>\n<td headers=\"stub_1_4 Pre\" class=\"gt_row gt_right gt_striped\">5</td>\n<td headers=\"stub_1_4 Post\" class=\"gt_row gt_right gt_striped\">5</td></tr>\n    <tr><th id=\"stub_1_5\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier;\">5</th>\n<td headers=\"stub_1_5 Participant\" class=\"gt_row gt_left\">P5</td>\n<td headers=\"stub_1_5 Pre\" class=\"gt_row gt_right\">7</td>\n<td headers=\"stub_1_5 Post\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><th id=\"stub_1_6\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier;\">6</th>\n<td headers=\"stub_1_6 Participant\" class=\"gt_row gt_left gt_striped\">P6</td>\n<td headers=\"stub_1_6 Pre\" class=\"gt_row gt_right gt_striped\">9</td>\n<td headers=\"stub_1_6 Post\" class=\"gt_row gt_right gt_striped\">4</td></tr>\n    <tr><th id=\"stub_1_7\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier; font-size: x-small; background-color: #E4E4E4;\">7..29</th>\n<td headers=\"stub_1_7 Participant\" class=\"gt_row gt_left\" style=\"background-color: #E4E4E4;\"></td>\n<td headers=\"stub_1_7 Pre\" class=\"gt_row gt_right\" style=\"background-color: #E4E4E4;\"></td>\n<td headers=\"stub_1_7 Post\" class=\"gt_row gt_right\" style=\"background-color: #E4E4E4;\"></td></tr>\n    <tr><th id=\"stub_1_8\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier;\">30</th>\n<td headers=\"stub_1_8 Participant\" class=\"gt_row gt_left gt_striped\">P30</td>\n<td headers=\"stub_1_8 Pre\" class=\"gt_row gt_right gt_striped\">7</td>\n<td headers=\"stub_1_8 Post\" class=\"gt_row gt_right gt_striped\">6</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n\n::: {.column width=\"60%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec10_files/figure-revealjs/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n:::\n:::::\n\n## Paired-Samples t-Test\n\n### Step 2: the difference scores\n\n::::: columns\n::: {.column width=\"55%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"taqfqhckgr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#taqfqhckgr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#taqfqhckgr thead, #taqfqhckgr tbody, #taqfqhckgr tfoot, #taqfqhckgr tr, #taqfqhckgr td, #taqfqhckgr th {\n  border-style: none;\n}\n\n#taqfqhckgr p {\n  margin: 0;\n  padding: 0;\n}\n\n#taqfqhckgr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 26px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 95%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#taqfqhckgr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#taqfqhckgr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#taqfqhckgr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#taqfqhckgr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#taqfqhckgr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#taqfqhckgr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#taqfqhckgr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#taqfqhckgr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#taqfqhckgr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#taqfqhckgr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#taqfqhckgr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#taqfqhckgr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#taqfqhckgr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#taqfqhckgr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#taqfqhckgr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#taqfqhckgr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#taqfqhckgr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#taqfqhckgr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#taqfqhckgr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#taqfqhckgr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#taqfqhckgr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#taqfqhckgr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#taqfqhckgr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#taqfqhckgr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#taqfqhckgr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#taqfqhckgr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#taqfqhckgr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#taqfqhckgr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#taqfqhckgr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#taqfqhckgr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#taqfqhckgr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#taqfqhckgr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#taqfqhckgr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#taqfqhckgr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#taqfqhckgr .gt_left {\n  text-align: left;\n}\n\n#taqfqhckgr .gt_center {\n  text-align: center;\n}\n\n#taqfqhckgr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#taqfqhckgr .gt_font_normal {\n  font-weight: normal;\n}\n\n#taqfqhckgr .gt_font_bold {\n  font-weight: bold;\n}\n\n#taqfqhckgr .gt_font_italic {\n  font-style: italic;\n}\n\n#taqfqhckgr .gt_super {\n  font-size: 65%;\n}\n\n#taqfqhckgr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#taqfqhckgr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#taqfqhckgr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#taqfqhckgr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#taqfqhckgr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#taqfqhckgr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#taqfqhckgr .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#taqfqhckgr .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#taqfqhckgr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Participant\">Participant</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Pre\">Pre</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Post\">Post</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"D-=-Post---Pre\">D = Post - Pre</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier;\">1</th>\n<td headers=\"stub_1_1 Participant\" class=\"gt_row gt_left\">P1</td>\n<td headers=\"stub_1_1 Pre\" class=\"gt_row gt_right\">10</td>\n<td headers=\"stub_1_1 Post\" class=\"gt_row gt_right\">7</td>\n<td headers=\"stub_1_1 D = Post - Pre\" class=\"gt_row gt_right\">-3</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier;\">2</th>\n<td headers=\"stub_1_2 Participant\" class=\"gt_row gt_left gt_striped\">P2</td>\n<td headers=\"stub_1_2 Pre\" class=\"gt_row gt_right gt_striped\">7</td>\n<td headers=\"stub_1_2 Post\" class=\"gt_row gt_right gt_striped\">7</td>\n<td headers=\"stub_1_2 D = Post - Pre\" class=\"gt_row gt_right gt_striped\">0</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier;\">3</th>\n<td headers=\"stub_1_3 Participant\" class=\"gt_row gt_left\">P3</td>\n<td headers=\"stub_1_3 Pre\" class=\"gt_row gt_right\">12</td>\n<td headers=\"stub_1_3 Post\" class=\"gt_row gt_right\">11</td>\n<td headers=\"stub_1_3 D = Post - Pre\" class=\"gt_row gt_right\">-1</td></tr>\n    <tr><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier;\">4</th>\n<td headers=\"stub_1_4 Participant\" class=\"gt_row gt_left gt_striped\">P4</td>\n<td headers=\"stub_1_4 Pre\" class=\"gt_row gt_right gt_striped\">5</td>\n<td headers=\"stub_1_4 Post\" class=\"gt_row gt_right gt_striped\">5</td>\n<td headers=\"stub_1_4 D = Post - Pre\" class=\"gt_row gt_right gt_striped\">0</td></tr>\n    <tr><th id=\"stub_1_5\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier;\">5</th>\n<td headers=\"stub_1_5 Participant\" class=\"gt_row gt_left\">P5</td>\n<td headers=\"stub_1_5 Pre\" class=\"gt_row gt_right\">7</td>\n<td headers=\"stub_1_5 Post\" class=\"gt_row gt_right\">4</td>\n<td headers=\"stub_1_5 D = Post - Pre\" class=\"gt_row gt_right\">-3</td></tr>\n    <tr><th id=\"stub_1_6\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier;\">6</th>\n<td headers=\"stub_1_6 Participant\" class=\"gt_row gt_left gt_striped\">P6</td>\n<td headers=\"stub_1_6 Pre\" class=\"gt_row gt_right gt_striped\">9</td>\n<td headers=\"stub_1_6 Post\" class=\"gt_row gt_right gt_striped\">4</td>\n<td headers=\"stub_1_6 D = Post - Pre\" class=\"gt_row gt_right gt_striped\">-5</td></tr>\n    <tr><th id=\"stub_1_7\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier; font-size: x-small; background-color: #E4E4E4;\">7..29</th>\n<td headers=\"stub_1_7 Participant\" class=\"gt_row gt_left\" style=\"background-color: #E4E4E4;\"></td>\n<td headers=\"stub_1_7 Pre\" class=\"gt_row gt_right\" style=\"background-color: #E4E4E4;\"></td>\n<td headers=\"stub_1_7 Post\" class=\"gt_row gt_right\" style=\"background-color: #E4E4E4;\"></td>\n<td headers=\"stub_1_7 D = Post - Pre\" class=\"gt_row gt_right\" style=\"background-color: #E4E4E4;\"></td></tr>\n    <tr><th id=\"stub_1_8\" scope=\"row\" class=\"gt_row gt_right gt_stub\" style=\"font-family: Courier;\">30</th>\n<td headers=\"stub_1_8 Participant\" class=\"gt_row gt_left gt_striped\">P30</td>\n<td headers=\"stub_1_8 Pre\" class=\"gt_row gt_right gt_striped\">7</td>\n<td headers=\"stub_1_8 Post\" class=\"gt_row gt_right gt_striped\">6</td>\n<td headers=\"stub_1_8 D = Post - Pre\" class=\"gt_row gt_right gt_striped\">-1</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n\n::: {.column width=\"45%\"}\n- $D$ is **post minus pre**.\n\n- A **negative** $D$ means stress went **down**.\n\n- From here on, the test only looks at the column of $D$ values.\n:::\n:::::\n\n## Paired-Samples t-Test\n\n### Steps 3 and 4: construct the formula (manually)\n\n::: callout-tip\n## Mean and SD of the differences\n\n$\\bar{D} = -1.67$ and $s_D = 1.21$ across $n = 30$ pairs\n:::\n\n::: callout-tip\n## Compute t\n\n$t = \\dfrac{\\bar{D}}{s_D/\\sqrt{n}} = \\dfrac{-1.67}{1.21/\\sqrt{30}} = -7.53$\n:::\n\n::: callout-tip\n## Decide\n\nAt $\\alpha = .05$ (two-tailed) and $df = 29$, $t_{critical} = \\pm 2.045$. Since $|t| = 7.53 > 2.045$, we **reject** $H_0$.\n:::\n\n## Paired-Samples t-Test\n\n### Construct the formula (computationally)\n\n::: {.codewindow .r .codewindow-dark}\npaired_t.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# post - pre, so a decrease in stress is a negative difference\nt.test(stress$Post, stress$Pre, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  stress$Post and stress$Pre\nt = -7.526, df = 29, p-value = 2.696e-08\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -2.119592 -1.213741\nsample estimates:\nmean difference \n      -1.666667 \n```\n\n\n:::\n:::\n\n:::\n\n## Paired-Samples t-Test\n\n### Reading the output\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gurjetzkaf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gurjetzkaf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gurjetzkaf thead, #gurjetzkaf tbody, #gurjetzkaf tfoot, #gurjetzkaf tr, #gurjetzkaf td, #gurjetzkaf th {\n  border-style: none;\n}\n\n#gurjetzkaf p {\n  margin: 0;\n  padding: 0;\n}\n\n#gurjetzkaf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 32px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 70%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gurjetzkaf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gurjetzkaf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gurjetzkaf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gurjetzkaf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gurjetzkaf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gurjetzkaf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gurjetzkaf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gurjetzkaf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gurjetzkaf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gurjetzkaf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gurjetzkaf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gurjetzkaf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gurjetzkaf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gurjetzkaf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gurjetzkaf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gurjetzkaf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gurjetzkaf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gurjetzkaf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gurjetzkaf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gurjetzkaf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gurjetzkaf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gurjetzkaf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gurjetzkaf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gurjetzkaf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gurjetzkaf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gurjetzkaf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gurjetzkaf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gurjetzkaf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gurjetzkaf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gurjetzkaf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gurjetzkaf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gurjetzkaf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gurjetzkaf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gurjetzkaf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gurjetzkaf .gt_left {\n  text-align: left;\n}\n\n#gurjetzkaf .gt_center {\n  text-align: center;\n}\n\n#gurjetzkaf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gurjetzkaf .gt_font_normal {\n  font-weight: normal;\n}\n\n#gurjetzkaf .gt_font_bold {\n  font-weight: bold;\n}\n\n#gurjetzkaf .gt_font_italic {\n  font-style: italic;\n}\n\n#gurjetzkaf .gt_super {\n  font-size: 65%;\n}\n\n#gurjetzkaf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gurjetzkaf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gurjetzkaf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gurjetzkaf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gurjetzkaf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gurjetzkaf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gurjetzkaf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gurjetzkaf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gurjetzkaf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"d\">d</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"t\">t</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"CI[ll,uu]\">CI[ll,uu]</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"d\" class=\"gt_row gt_right\">−1.67</td>\n<td headers=\"t\" class=\"gt_row gt_right\">−7.53</td>\n<td headers=\"df\" class=\"gt_row gt_right\">29</td>\n<td headers=\"p\" class=\"gt_row gt_left\">&lt;.001</td>\n<td headers=\"CI[ll,uu]\" class=\"gt_row gt_left\">[-2.12, -1.21]</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n- d = mean difference (post minus pre, $\\bar{D}$)\n\n- t = t-test statistic\n\n- df = $n - 1$ (30 - 1)\n\n- p = probability of a difference at least this extreme if $H_0$ is true\n\n- CI\\[ll,uu\\] = 95% confidence interval for the mean difference\n\n## One-Tailed or Two-Tailed?\n\n### Matching the test to the hypothesis\n\n- Our alternative is **directional**: $H_A: \\mu_\\text{post} < \\mu_\\text{pre}$.\n\n- `t.test()` is two-tailed by default. A directional test uses `alternative`:\n\n::: {.codewindow .r .codewindow-dark}\none_tailed.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# post - pre, testing for a DEcrease\nt.test(stress$Post, stress$Pre, paired = TRUE, alternative = \"less\")\n```\n:::\n\n:::\n\n- The t-statistic is the same, but the one-tailed p-value is **half** the two-tailed p-value (for an effect in the predicted direction) and the CI becomes one-sided.\n\n- Choose the direction **before** you see the data. Here the conclusion is the same either way: p < .001.\n\n## Why Pairing Helps\n\n### The same data, analyzed two ways\n\n::::::::: side-by-cols\n::::: stat-card\n::: stat-num\n-7.53\n:::\n\n::: stat-sub\n**Paired** t-test (uses the pairing)\n:::\n:::::\n\n::::: stat-card\n::: stat-num\n-3.12\n:::\n\n::: stat-sub\n**Independent** t-test (ignores the pairing)\n:::\n:::::\n:::::::::\n\n- People differ a lot from each other, and that **between-person** variability swamps the average change in an independent-samples test.\n\n- Pairing compares each person to **themselves**. Because pre and post scores are correlated (r = 0.83), the differences are much less spread out than the raw scores.\n\n## Effect Size: Cohen's *d*\n\n### Why report effect size?\n\n- Statistical significance ($p$) tells us **if** there is a difference.\n\n- Effect size tells us **how big** that difference is.\n\n- For a paired-samples design, the effect size is $d_z$:\n\n::: callout-tip\n## $d_z$\n\n$d_z = \\dfrac{\\bar{D}}{s_D}$: the mean difference in units of the standard deviation of the differences.\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"cphchdeafh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#cphchdeafh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#cphchdeafh thead, #cphchdeafh tbody, #cphchdeafh tfoot, #cphchdeafh tr, #cphchdeafh td, #cphchdeafh th {\n  border-style: none;\n}\n\n#cphchdeafh p {\n  margin: 0;\n  padding: 0;\n}\n\n#cphchdeafh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 22px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 50%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#cphchdeafh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#cphchdeafh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#cphchdeafh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#cphchdeafh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cphchdeafh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cphchdeafh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cphchdeafh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#cphchdeafh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#cphchdeafh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#cphchdeafh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#cphchdeafh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#cphchdeafh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#cphchdeafh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#cphchdeafh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#cphchdeafh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#cphchdeafh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#cphchdeafh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#cphchdeafh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cphchdeafh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#cphchdeafh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#cphchdeafh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#cphchdeafh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cphchdeafh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#cphchdeafh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#cphchdeafh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cphchdeafh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cphchdeafh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#cphchdeafh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cphchdeafh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#cphchdeafh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cphchdeafh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cphchdeafh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cphchdeafh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cphchdeafh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cphchdeafh .gt_left {\n  text-align: left;\n}\n\n#cphchdeafh .gt_center {\n  text-align: center;\n}\n\n#cphchdeafh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#cphchdeafh .gt_font_normal {\n  font-weight: normal;\n}\n\n#cphchdeafh .gt_font_bold {\n  font-weight: bold;\n}\n\n#cphchdeafh .gt_font_italic {\n  font-style: italic;\n}\n\n#cphchdeafh .gt_super {\n  font-size: 65%;\n}\n\n#cphchdeafh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#cphchdeafh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#cphchdeafh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#cphchdeafh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#cphchdeafh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#cphchdeafh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#cphchdeafh .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#cphchdeafh .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#cphchdeafh div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a|d|\">|d|</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Interpretation\">Interpretation</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"|d|\" class=\"gt_row gt_right\">0.20</td>\n<td headers=\"Interpretation\" class=\"gt_row gt_left\">Small effect</td></tr>\n    <tr><td headers=\"|d|\" class=\"gt_row gt_right gt_striped\">0.50</td>\n<td headers=\"Interpretation\" class=\"gt_row gt_left gt_striped\">Medium effect</td></tr>\n    <tr><td headers=\"|d|\" class=\"gt_row gt_right\">0.80</td>\n<td headers=\"Interpretation\" class=\"gt_row gt_left\">Large effect</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Cohen's d\n\n### Mindfulness example\n\n::::::: columns\n:::: {.column width=\"50%\"}\n::: callout-tip\n## By hand\n\n$d_z = \\dfrac{\\bar{D}}{s_D} = \\dfrac{-1.67}{1.21} = -1.37$\n:::\n\nThe size is $|d_z| = 1.37$, a **large** effect. The negative sign just means scores went **down**.\n::::\n\n:::: {.column width=\"50%\"}\n::: {.codewindow .r .codewindow-dark}\ncohens_d.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(rstatix)\nstress |>\n  pivot_longer(c(Post, Pre),\n               names_to = \"time\", values_to = \"score\") |>\n  cohens_d(score ~ time, paired = TRUE)\n```\n:::\n\n:::\n\n`rstatix` reports the same value: $d_z = -1.37$.\n::::\n:::::::\n\n## Paired T-Tests\n\n### Visualizing results\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec10_files/figure-revealjs/unnamed-chunk-10-1.png){width=1152}\n:::\n:::\n\n\n## Reporting Results\n\n### APA-style\n\n> A [paired-samples t-test]{.hl} was conducted to [compare stress before and after a mindfulness program]{.hl}. Results showed a [significant decrease]{.hl} in stress after the program, [*t(29) = -7.53, p < .001*]{.hl}, 95% CI \\[-2.12, -1.21\\], $d_z$ = -1.37.\n\n- **What kind of test?** paired-samples t-test\n- **What is being compared?** stress before and after the program\n- **Is it significant?** significant decrease\n- **What are the test results?** t, df, p, confidence interval, and effect size\n\n## Interpreting Results\n\n- We found a **statistically significant** decrease in stress ($p$ < .001).\n\n- The **effect size** ($|d_z| =$ 1.37) indicates a *large* change.\n\n- Combining significance and effect size gives us a fuller picture of the data.\n\n> Always ask: is this difference not just *statistically*, but *practically* meaningful?\n\n## Summary of Paired-Samples t-Test\n\n### Key takeaways\n\n- Paired-samples t-tests are ideal for comparing **two related** sets of scores.\n\n- They help determine if interventions or conditions produce **significant changes**.\n\n- Remember to check the **assumptions**:\n\n::: callout-important\n## Assumptions\n\n1.  **The differences are normally distributed.** Check with a histogram, QQ plot, or Shapiro-Wilk test.\n2.  **The pairs are dependent (related measures).** Same participants or matched pairs.\n3.  **No major outliers in the differences.**\n:::\n\n\n\n## Practice\n\n### Pre/post stress\n\n> A researcher measures 30 participants' stress before and after a mindfulness program (`ex_1`: `Stress_Pre`, `Stress_Post`). She predicts that stress will be **lower** afterward.\n\n::: {.callout-tip .nonincremental}\n## Your tasks\n\n1.  State $H_0$ and $H_A$.\n2.  Compute the difference scores (post minus pre).\n3.  Run the paired-samples t-test, report $d_z$, and write an APA sentence.\n:::\n\n## Practice\n\n### Pre/post stress: data and answer\n\n::: {.codewindow .r .codewindow-dark}\npractice_1.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nset.seed(101)\nex_1 <- tibble(\n  ID = 1:30,\n  Stress_Pre  = rnorm(30, mean = 20, sd = 4)\n) |> mutate(Stress_Post = Stress_Pre - 4 + rnorm(30, 0, 3))\n```\n:::\n\n:::\n\n::: {.fragment}\n::: {.callout-important .nonincremental}\n## Answer\n\n$H_0: \\mu_D = 0$; $H_A: \\mu_D < 0$. *t(29) = -7.87, p < .001*, $d_z$ = -1.44: a significant, large decrease in stress.\n:::\n:::\n\n## Practice\n\n### Reaction time and music\n\n> Do people respond faster with music playing? 25 participants complete a reaction-time task with no music and with music (`ex_2`: `RT_NoMusic`, `RT_Music`). The prediction is that reaction times will be **faster (lower)** with music.\n\n::: {.callout-tip .nonincremental}\n## Your tasks\n\n1.  State $H_0$ and $H_A$.\n2.  Compute the difference scores (music minus no music).\n3.  Run a **one-tailed** paired-samples t-test (`alternative = \"less\"`) and decide.\n:::\n\n## Practice\n\n### Reaction time and music: data and answer\n\n::: {.codewindow .r .codewindow-dark}\npractice_2.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nset.seed(102)\nex_2 <- tibble(\n  ID = 1:25,\n  RT_NoMusic = rnorm(25, mean = 520, sd = 60)\n) |> mutate(RT_Music = RT_NoMusic - 20 + rnorm(25, 0, 25))\n```\n:::\n\n:::\n\n::: {.fragment}\n::: {.callout-important .nonincremental}\n## Answer\n\n$H_0: \\mu_D = 0$; $H_A: \\mu_D < 0$. *t(24) = -1.49, p = .075 (one-tailed)*, $d_z$ = -0.30. The decision depends on the result: compare p to $\\alpha = .05$ and interpret both the decision and the effect size.\n:::\n:::\n",
    "supporting": [
      "lec10_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}