project:
  type: website
  output-dir: docs

website:
  sidebar: 
    style: "docked"
    section: "PSY 348"
    contents:
      - section: "Lectures"
        contents:
        - href: "lec1_viewer.qmd"
        - href: "lec2_viewer.qmd"
        - href: "lec3_viewer.qmd"
        - href: "lec4_viewer.qmd"
        - href: "lec5_viewer.qmd"
        - href: "lec6_viewer.qmd"
        - href: "lec7_viewer.qmd"
        - href: "lec8_viewer.qmd"
        - href: "lec9_viewer.qmd"
        - href: "lec10_viewer.qmd"
        - href: "lec11_viewer.qmd"
        - href: "lec12_viewer.qmd"
        - href: "lec13fct_viewer.qmd"
        - href: "lec14_viewer.qmd"
        - href: "lec15c_viewer.qmd"
        - href: "lec15_viewer.qmd"
      - section: "Labs"
        contents:
        - href: "lab_orientation_viewer.qmd"
        - href: "lab1_viewer.qmd"
        - href: "lab3_viewer.qmd"
        - href: "lab_zscores_viewer.qmd"
        - href: "lab10_viewer.qmd"
        - href: "lab7_viewer.qmd"
      - section: "Exam Review"
        contents:
        - href: "formulas.qmd"
        - href: "exam1_review_viewer.qmd"
        - href: "exam2_review_viewer.qmd"
      - section: "Using R"
        contents:
        - href: "Using R.qmd"
        - href: "RWorkstation_viewer.qmd"
  title: "PSY 348: Statistics for Psychology"
  navbar:
    background: "#5C715E"
    left:
      - href: index.qmd

format:
  html:
    theme: [default, custom.scss]
    respect-user-color-scheme: true
    css: styles.css
    toc: true

execute: 
  freeze: auto

editor: visual
