project:
  type: website
  output-dir: docs

website:
  sidebar: 
    style: "docked"
    section: "PSY 348"
    contents:
      - section: "Lectures"
        contents:
        - href: "lec2.qmd"
        - href: "lec3.qmd"
        - href: "lec4.qmd"
        - href: "lec5.qmd"
        - href: "lec6.qmd"
        - href: "lec7.qmd"
        - href: "lec8.qmd"
        - href: "lec9.qmd"
        - href: "lec10.qmd"
        - href: "lec11.qmd"
        - href: "lec12.qmd"
        - href: "lec13.qmd"
        - href: "lec14.qmd"
        - href: "lec15.qmd"
        - href: "lec16.qmd"
        - href: "lec17.qmd"
      - section: "Labs"
        contents:
        - href: "lab1.qmd"
        - href: "lab2.qmd"
        - href: "lab3.qmd"
        - href: "lab4.qmd"
      - section: "Exam Review"
        contents:
        - href: "formulas.qmd"
        - href: "exam1_review.qmd"
        - href: "exam2_review.qmd"
      - section: "Using R"
        contents:
        - href: "Using R.qmd"
        - href: "RWorkstation.qmd"
  title: "PSY 348: Statistics for Psychology"
  navbar:
    background: "maroon"
    left:
      - href: index.qmd

format:
  html:
    theme: [default, custom.scss]
    respect-user-color-scheme: true
    css: styles.css
    toc: true

execute: 
  freeze: auto

editor: visual
