project:
  type: website
  output-dir: docs

website:
  sidebar: 
    style: "docked"
    section: "PSY 348"
    contents:
      - section: "Lectures"
        contents:
        - href: "lec2_viewer.qmd"
        - href: "lec3_viewer.qmd"
        - href: "lec4_viewer.qmd"
        - href: "lec5_viewer.qmd"
        - href: "lec6_viewer.qmd"
        - href: "lec7_viewer.qmd"
        - href: "lec8_viewer.qmd"
        - href: "lec9_viewer.qmd"
        - href: "lec10_viewer.qmd"
        - href: "lec11_viewer.qmd"
        - href: "lec12_viewer.qmd"
        - href: "lec13_viewer.qmd"
        - href: "lec14_viewer.qmd"
        - href: "lec15_viewer.qmd"
        - href: "lec16_viewer.qmd"
        - href: "lec17_viewer.qmd"
      - section: "Labs"
        contents:
        - href: "lab1.qmd"
        - href: "lab2.qmd"
        - href: "lab3.qmd"
        - href: "lab4.qmd"
      - section: "Exam Review"
        contents:
        - href: "formulas.qmd"
        - href: "exam1_review.qmd"
        - href: "exam2_review.qmd"
      - section: "Using R"
        contents:
        - href: "Using R.qmd"
        - href: "RWorkstation.qmd"
  title: "PSY 348: Statistics for Psychology"
  navbar:
    background: "maroon"
    left:
      - href: index.qmd

format:
  html:
    theme: [default, custom.scss]
    respect-user-color-scheme: true
    css: styles.css
    toc: true

execute: 
  freeze: true

editor: visual
