project:
  type: website
  output-dir: docs

website:
  sidebar: 
    style: "docked"
    section: "PSY 348"
    contents:
      - section: "Lectures"
        contents:
        - href: "lec1/lec1_viewer.qmd"
        - href: "lec2/lec2_viewer.qmd"
        - href: "lec3/lec3_viewer.qmd"
        - href: "lec4/lec4_viewer.qmd"
        - href: "lec5/lec5_viewer.qmd"
        - href: "lec6/lec6_viewer.qmd"
        - href: "lec7/lec7_viewer.qmd"
        - href: "lec8/lec8_viewer.qmd"
        - href: "lec9/lec9_viewer.qmd"
        - href: "lec10/lec10_viewer.qmd"
        - href: "lec11/lec11_viewer.qmd"
        - href: "lec12/lec12_viewer.qmd"
        - href: "lec13fct/lec13fct_viewer.qmd"
        - href: "lec14/lec14_viewer.qmd"
        - href: "lec15c/lec15c_viewer.qmd"
        - href: "lec15/lec15_viewer.qmd"
      - section: "Labs"
        contents:
        - href: "lab_orientation/lab_orientation_viewer.qmd"
        - href: "lab1/lab1_viewer.qmd"
        - href: "lab3/lab3_viewer.qmd"
        - href: "lab_zscores/lab_zscores_viewer.qmd"
        - href: "lab10/lab10_viewer.qmd"
        - href: "lab7/lab7_viewer.qmd"
      - section: "Exam Review"
        contents:
        - href: "formulas.qmd"
        - href: "exam1/exam1_review_viewer.qmd"
        - href: "exam2/exam2_review_viewer.qmd"
      - section: "Using R"
        contents:
        - href: "using_r/Using R.qmd"
        - href: "using_r/RWorkstation_viewer.qmd"
  title: "PSY 348: Statistics for Psychology"
  navbar:
    background: "#5C715E"
    left:
      - href: index.qmd

format:
  html:
    theme: [default, custom.scss]
    respect-user-color-scheme: true
    css: styles.css
    toc: true

execute: 
  freeze: auto

editor: visual
