---
title: "Course Overview"
author: 
  - name: "Dave Brocker"
    email: "brockeda@farmingdale.edu"
    affiliation: "Farmingdale State College"
---

## Welcome to Stats!

Discover how data tells a story! In this course, you’ll learn to **analyze, interpret, and visualize** data to uncover meaningful insights. From understanding basic concepts like **descriptive statistics** to mastering **hypothesis testing** and **regression analysis**, you’ll gain the tools to make informed decisions based on evidence.

No matter your background, this course will help you see statistics not just as numbers, but as a **powerful way of thinking**. Get ready to explore real-world data, develop critical analysis skills, and even have some fun with stats along the way!

### What should I do next?

**Explore the Lectures:** Take some time to browse through the lecture materials.

-   Use the search bar to find what you are looking for

**Check the Textbook:** Familiarize yourself with key concepts that will help you connect theory with practice.

**Engage with Data:** Practice using R/Posit Cloud early—you’ll find it makes stats more interactive and intuitive.

-   Use the **Data Sandbox** to explore different data-sets and hone your skills
