{
  "hash": "c73aba9311edf90acf9a5a20b8d68c9f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"One-Sample T-Test\"\nsubtitle: \"PSY 348: Lecture 9\"\nauthor: \"Dave Brocker\"\ninstitute: \"Farmingdale State College\"\nfooter: \"One-Sample T-Test | ⬡⬢⬡⬢⬡⬢\"\nformat:\n  revealjs:\n    theme: ../custom.scss\n    incremental: true\n    touch: true\n    chalkboard: true\n    lightbox: true\n    scrollable: true\n    code-fold: true\n    slide-number: c/t\n    include-after-body: ../title-bg.html\n    width: 1600\n    height: 900\n    drop:\n      engine: webr\nrevealjs-plugins:\n  - drop\n  - codewindow\n---\n\n\n\n## Recap\n\n### How did we get here?\n\n:::::: badge-row\n::: content-badge\n[straighten]{.material-icons}\n\n#### Measurement\n\nMeasuring abstract concepts\n:::\n\n::: content-badge\n[category]{.material-icons}\n\n#### Variables\n\nTypes and scales\n:::\n\n::: content-badge\n[show_chart]{.material-icons}\n\n#### The Normal Curve\n\nProbability from z-scores\n:::\n\n::: content-badge\n[groups]{.material-icons}\n\n#### Sampling Theory\n\nDistribution of sample means\n:::\n::::::\n\n::: {.callout-tip appearance=\"minimal\"}\nIf we can estimate the probability that a sample mean came from a particular distribution, can we also estimate whether it came from the null or the alternative hypothesis?\n:::\n\n## From Probability to Decision-Making\n\n- Once we know how likely a sample mean is to occur, we can begin to make decisions about what that likelihood means.\n\n- We introduced two competing ideas:\n\n::::: columns\n::: {.column width=\"50%\"}\n::: callout-tip\n## Null hypothesis $H_0$\n\nNo real difference or effect.\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: callout-important\n## Alternative hypothesis $H_1/H_A$\n\nA true difference or effect exists.\n:::\n:::\n:::::\n\n- Because samples vary, we can never be 100% certain, only confident to a degree.\n\n## Errors in Estimation\n\n### Type I and II Error\n\n- That degree of confidence is defined by $\\alpha$ (alpha), our threshold for error when rejecting $H_0$.\n\n- $\\beta$ (beta) is the probability of missing a real effect (failing to reject $H_0$ when $H_1$ is true).\n\n::::: term-list\n::: fragment\n[Type I Error ($\\alpha$)]{.term-pill}\n\n: Finding a difference that isn't really there. (False Positive)\n:::\n\n::: fragment\n[Type II Error ($\\beta$)]{.term-pill}\n\n: Missing a difference that actually exists. (False Negative)\n:::\n:::::\n\n## The Truth Table\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ymonboorzh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ymonboorzh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ymonboorzh thead, #ymonboorzh tbody, #ymonboorzh tfoot, #ymonboorzh tr, #ymonboorzh td, #ymonboorzh th {\n  border-style: none;\n}\n\n#ymonboorzh p {\n  margin: 0;\n  padding: 0;\n}\n\n#ymonboorzh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 25px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 70%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ymonboorzh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ymonboorzh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ymonboorzh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ymonboorzh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ymonboorzh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ymonboorzh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ymonboorzh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ymonboorzh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ymonboorzh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ymonboorzh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ymonboorzh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ymonboorzh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ymonboorzh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ymonboorzh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ymonboorzh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ymonboorzh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ymonboorzh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ymonboorzh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ymonboorzh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ymonboorzh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ymonboorzh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ymonboorzh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ymonboorzh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ymonboorzh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ymonboorzh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ymonboorzh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ymonboorzh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ymonboorzh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ymonboorzh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ymonboorzh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ymonboorzh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ymonboorzh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ymonboorzh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ymonboorzh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ymonboorzh .gt_left {\n  text-align: left;\n}\n\n#ymonboorzh .gt_center {\n  text-align: center;\n}\n\n#ymonboorzh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ymonboorzh .gt_font_normal {\n  font-weight: normal;\n}\n\n#ymonboorzh .gt_font_bold {\n  font-weight: bold;\n}\n\n#ymonboorzh .gt_font_italic {\n  font-style: italic;\n}\n\n#ymonboorzh .gt_super {\n  font-size: 65%;\n}\n\n#ymonboorzh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ymonboorzh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ymonboorzh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ymonboorzh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ymonboorzh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ymonboorzh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ymonboorzh .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ymonboorzh .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ymonboorzh div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style><span data-qmd-base64=\"KipEZWNpc2lvbiBPdXRjb21lcyBpbiBIeXBvdGhlc2lzIFRlc3RpbmcqKg==\"><span class='gt_from_md'><strong>Decision Outcomes in Hypothesis Testing</strong></span></span></td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"null_true\"><span data-qmd-base64=\"JCRIXzBcdGV4dHsgVHJ1ZX0kJA==\"><span class='gt_from_md'>$$H_0\\text{ True}$$</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"null_false\"><span data-qmd-base64=\"JCRIXzBcdGV4dHsgRmFsc2V9JCQ=\"><span class='gt_from_md'>$$H_0\\text{ False}$$</span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"JCRcdGV4dHtSZWplY3QgfUhfMCQk\"><span class='gt_from_md'>$$\\text{Reject }H_0$$</span></span></th>\n<td headers=\"stub_1_1 null_true\" class=\"gt_row gt_left\" style=\"background-color: #EBC9C3;\"><span data-qmd-base64=\"JCRcdGV4dHtUeXBlIEkgRXJyb3IgfShcYWxwaGEpJCQ=\"><span class='gt_from_md'>$$\\text{Type I Error }(\\alpha)$$</span></span></td>\n<td headers=\"stub_1_1 null_false\" class=\"gt_row gt_left\" style=\"background-color: #DCE8E1;\"><span data-qmd-base64=\"JCRcdGV4dHtDb3JyZWN0IERlY2lzaW9ufVxcMS1cYmV0YSQk\"><span class='gt_from_md'>$$\\text{Correct Decision}\\\\1-\\beta$$</span></span></td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"JCRcdGV4dHtGYWlsIHRvIFJlamVjdCB9IEhfMCQk\"><span class='gt_from_md'>$$\\text{Fail to Reject } H_0$$</span></span></th>\n<td headers=\"stub_1_2 null_true\" class=\"gt_row gt_left\" style=\"background-color: #DCE8E1;\"><span data-qmd-base64=\"JCRcdGV4dHtDb3JyZWN0IERlY2lzaW9ufVxcMS1cYWxwaGEkJA==\"><span class='gt_from_md'>$$\\text{Correct Decision}\\\\1-\\alpha$$</span></span></td>\n<td headers=\"stub_1_2 null_false\" class=\"gt_row gt_left\" style=\"background-color: #EBC9C3;\"><span data-qmd-base64=\"JCRcdGV4dHtUeXBlIElJIEVycm9yIH0gKFxiZXRhKSQk\"><span class='gt_from_md'>$$\\text{Type II Error } (\\beta)$$</span></span></td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Alpha and Beta\n\n### Seeing the two errors\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec9_files/figure-revealjs/unnamed-chunk-3-1.png){width=1056}\n:::\n:::\n\n\n- The dashed line is the **critical value**: results beyond it lead us to reject $H_0$.\n\n- $\\alpha$ (red): the part of the $H_0$ curve beyond the line, so a true null gets rejected (Type I error).\n\n- $\\beta$ (orange): the part of the $H_1$ curve before the line, so a real effect is missed (Type II error).\n\n- **Power** is $1 - \\beta$: the chance of detecting a real effect.\n\n## Why Compare Means?\n\n- We often want to test whether a sample mean differs from a known population mean.\n\n- The one-sample t-test helps determine if the sample mean is significantly different from the hypothesized population mean.\n\n:::::: badge-row\n::: content-badge\n[school]{.material-icons}\n\n#### Exam scores\n\nClass average vs. a national average of 75\n:::\n\n::: content-badge\n[timer]{.material-icons}\n\n#### Reaction times\n\nAverage vs. a published 250 ms standard\n:::\n\n::: content-badge\n[linear_scale]{.material-icons}\n\n#### Scale midpoints\n\nRatings vs. the scale midpoint\n:::\n::::::\n\n## Why Not z?\n\n### From z to t\n\n- In lecture 8 we computed $z = \\dfrac{\\bar{x} - \\mu}{\\sigma / \\sqrt{n}}$, which needs the **population** standard deviation $\\sigma$.\n\n- In practice we almost never know $\\sigma$, so we substitute the sample's $s$.\n\n- But $s$ changes from sample to sample, especially when $n$ is small. That is **extra uncertainty** the normal curve does not account for.\n\n- So the sampling distribution has **heavier tails** than the normal curve: the t-distribution. A result must be more extreme to count as unusual.\n\n## Why Not z?\n\n### Same $\\alpha = .05$, bigger cutoff for small samples\n\nTwo-tailed critical values:\n\n:::::::::::: side-by-cols\n::::: stat-card\n::: stat-num\n1.96\n:::\n\n::: stat-sub\nz ($\\sigma$ known)\n:::\n:::::\n\n::::: stat-card\n::: stat-num\n2.09\n:::\n\n::: stat-sub\nt, $df = 19$ ($n = 20$)\n:::\n:::::\n\n::::: stat-card\n::: stat-num\n2.78\n:::\n\n::: stat-sub\nt, $df = 4$ ($n = 5$)\n:::\n:::::\n::::::::::::\n\n- The smaller the sample, the more the t cutoff moves away from the z cutoff. With large $n$, they are nearly identical.\n\n## The t-test\n\n### Three types, three cases\n\n::::: columns\n::: {.column width=\"33%\"}\n::: callout-tip\n## One-Sample\n\n$t=\\dfrac{\\bar{x}-\\mu}{\\sigma/\\sqrt{n}} \\;|\\; \\dfrac{\\bar{x}-\\mu}{s/\\sqrt{n}}$\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: callout-tip\n## Paired-Samples\n\n$t=\\dfrac{\\bar{D}}{\\sigma_D/\\sqrt{n}} \\;|\\; \\dfrac{\\bar{D}}{s_D/\\sqrt{n}}$\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: callout-tip\n## Independent-Samples\n\n$t = \\dfrac{\\bar{x}_1 - \\bar{x}_2}{\\sqrt{s_p^2\\left(\\frac{1}{n_1} + \\frac{1}{n_2}\\right)}}$\n\n$s_p^2 = \\dfrac{(n_1 - 1)s_1^2 + (n_2 - 1)s_2^2}{n_1 + n_2 - 2}$\n:::\n:::\n:::::\n\n- We use the sample standard deviation ($s$) to estimate the standard error ($s/\\sqrt{n}$) since population $\\sigma$ is typically unknown.\n\n- $s_D$ is the standard deviation of the **difference scores**; $s_p^2$ is the **pooled variance**, a weighted average of the two groups' variances.\n\n- In all cases, the t-distribution's shape (and so the critical value) depends on the **degrees of freedom** (df).\n\n  - One-sample and paired: $df = n - 1$. Independent samples: $df = n_1 + n_2 - 2$\n\n## The t-distribution\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec9_files/figure-revealjs/unnamed-chunk-4-1.png){width=1056}\n:::\n:::\n\n\n- The t-distribution has **heavier tails** than the normal curve when df is small, because $s$ is only an estimate of $\\sigma$.\n\n- As df grows, the t-distribution approaches the normal curve.\n\n## Assumptions of the One-Sample t-Test\n\n::: callout-important\n## Assumptions\n\n1.  The data are continuous (interval or ratio scale).\n2.  The sample is randomly selected.\n3.  The data are normally distributed (or the sample size is large enough for the Central Limit Theorem to apply).\n:::\n\n## The One-Sample t-Test Formula\n\n::: callout-tip\n## One-Sample t-Test\n\n$\\large{t = \\dfrac{\\color{blue}{\\bar{x}} - \\mu}{\\color{orange}{s}/\\sqrt{n}}}$\n:::\n\nWhere:\n\n- $\\color{blue}{\\bar{x}}$ = sample mean\n\n- $\\mu$ = population mean (null hypothesis value)\n\n- $\\color{orange}{s}/\\sqrt{n}$ = the standard error (SE), estimated from the sample since population $\\sigma$ is typically unknown\n\n  - $\\color{orange}{s}$ = sample standard deviation\n\n  - $n$ = sample size\n\n## Hypothesis Testing Steps\n\n::: callout-tip\n## Four steps\n\n1.  **Set hypotheses:** define both the null and alternative.\n2.  **Collect sample data:** use the appropriate sampling method and collect the needed data.\n3.  **Compute the t-statistic:** conduct the correct t-test.\n4.  **Compare to the critical value:** use the t-statistic, sample size (df), and alpha level to determine statistical significance. Equivalently, compare the p-value to $\\alpha$.\n:::\n\n## Reading the t-Table\n\n### Critical values by degrees of freedom\n\n::: z-excerpt\n| df | One-tailed .05<br>(two-tailed .10) | One-tailed .025<br>(two-tailed .05) | One-tailed .005<br>(two-tailed .01) |\n|:----------------:|:----------------:|:----------------:|:----------------:|\n| 15 | 1.753 | 2.131 | 2.947 |\n| **19** | 1.729 | [2.093]{.z-hit} | 2.861 |\n| 24 | 1.711 | 2.064 | 2.797 |\n| 29 | 1.699 | 2.045 | 2.756 |\n| ∞ (z) | 1.645 | 1.960 | 2.576 |\n\n: Excerpt of the t-table (critical values)\n:::\n\n- Find your **df** ($n - 1$ for a one-sample test), then pick the column for your $\\alpha$ and your **tails**.\n\n- If $|t|$ is **beyond** the critical value, reject $H_0$.\n\n  - Example: $t = 2.68$ with $df = 19$, two-tailed $\\alpha = .05$: $2.68 > 2.093$, so reject.\n\n- In R: `qt(.975, df = 19)` returns `2.093`.\n\n## Hypothesis Testing Steps\n\n### Manual: hypotheses and data\n\n> A sample of `20` students has a mean exam score of `78` with a standard deviation of `5`. Does the class differ from the national average of `75`?\n\n::: callout-tip\n## 1. Set hypotheses\n\n- $H_0$: The average exam score is 75 ($\\mu = 75$).\n- $H_A$: The average exam score is not 75 ($\\mu \\neq 75$).\n:::\n\n::: callout-tip\n## 2. Collect sample data\n\n- Sample size: $n = 20$\n- Sample mean: $\\color{blue}{\\bar{x}} = 78$\n- Sample standard deviation: $\\color{orange}{s} = 5$\n:::\n\n## Hypothesis Testing Steps\n\n### Manual: test and decide\n\n::: callout-tip\n## 3. Compute the t-statistic\n\n$t = \\dfrac{78 - 75}{\\frac{5}{\\sqrt{20}}} = \\dfrac{3}{1.118} = 2.68$\n:::\n\n::: callout-tip\n## 4. Compare to the critical value\n\n- At $\\alpha = .05$ (two-tailed) and $df = 19$: $t_{critical} = \\pm 2.093$.\n- Since $2.68 > 2.093$, we **reject** $H_0$.\n:::\n\n## Hypothesis Testing Steps\n\n### Programmatic\n\n::: {.codewindow .r .codewindow-dark}\none_sample.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# For Reproducibility\nset.seed(20)\n\nn = 20   # sample size\nm = 78   # sample mean\nmu = 75  # population mean (H0)\ns = 5    # sample SD\n\n# Simulate data, then rescale so the sample has exactly mean 78 and SD 5\ndat <- rnorm(n)\ndat <- m + s * (dat - mean(dat)) / sd(dat)\n\nt.test(dat, mu = mu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  dat\nt = 2.6833, df = 19, p-value = 0.01471\nalternative hypothesis: true mean is not equal to 75\n95 percent confidence interval:\n 75.65993 80.34007\nsample estimates:\nmean of x \n       78 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n# By hand\n(m - mu) / (s / sqrt(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.683282\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n# Critical value (two-tailed, alpha = .05)\nqt(.975, df = n - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.093024\n```\n\n\n:::\n:::\n\n:::\n\n## Reporting Results\n\n### APA-style\n\n> A one-sample t-test was conducted to compare exam scores to the national average of `75`. Results showed a significant difference, `t(19) = 2.68, p = .015`, indicating that students scored significantly higher than the national average (`M = 78, SD = 5`).\n\n- What kind of test?\n- What is being compared?\n- Is it significant?\n- What are the test results?\n\n## Reporting Results\n\n### APA-style\n\n> A [one-sample t-test]{.hl} was conducted to [compare exam scores to the national average]{.hl} of `75`. Results showed a [significant difference]{.hl}, [`t(19) = 2.68, p = .015`]{.hl}, indicating that students scored significantly higher than the national average (`M = 78, SD = 5`).\n\n- **What kind of test?** one-sample t-test\n- **What is being compared?** exam scores to the national average\n- **Is it significant?** significant difference\n- **What are the test results?** `t(19) = 2.68, p = .015`\n\n## Interpreting Results\n\n### Sample summary table\n\n- A significant result ($p < .05$) suggests that the sample mean is different from the population mean.\n\n- A non-significant result ($p > .05$) means we fail to reject $H_0$ (insufficient evidence of a difference).\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"shmsipenme\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#shmsipenme table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#shmsipenme thead, #shmsipenme tbody, #shmsipenme tfoot, #shmsipenme tr, #shmsipenme td, #shmsipenme th {\n  border-style: none;\n}\n\n#shmsipenme p {\n  margin: 0;\n  padding: 0;\n}\n\n#shmsipenme .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 20px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#shmsipenme .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#shmsipenme .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#shmsipenme .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#shmsipenme .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#shmsipenme .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shmsipenme .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#shmsipenme .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#shmsipenme .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#shmsipenme .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#shmsipenme .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#shmsipenme .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#shmsipenme .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#shmsipenme .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#shmsipenme .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#shmsipenme .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#shmsipenme .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#shmsipenme .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#shmsipenme .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shmsipenme .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#shmsipenme .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#shmsipenme .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#shmsipenme .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shmsipenme .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#shmsipenme .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#shmsipenme .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shmsipenme .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shmsipenme .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#shmsipenme .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shmsipenme .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#shmsipenme .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shmsipenme .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#shmsipenme .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shmsipenme .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#shmsipenme .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shmsipenme .gt_left {\n  text-align: left;\n}\n\n#shmsipenme .gt_center {\n  text-align: center;\n}\n\n#shmsipenme .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#shmsipenme .gt_font_normal {\n  font-weight: normal;\n}\n\n#shmsipenme .gt_font_bold {\n  font-weight: bold;\n}\n\n#shmsipenme .gt_font_italic {\n  font-style: italic;\n}\n\n#shmsipenme .gt_super {\n  font-size: 65%;\n}\n\n#shmsipenme .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#shmsipenme .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#shmsipenme .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#shmsipenme .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#shmsipenme .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#shmsipenme .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#shmsipenme .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#shmsipenme .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#shmsipenme div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"M\">M</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"t\">t</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p\">p</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\">One Sample t-test</th>\n<td headers=\"stub_1_1 M\" class=\"gt_row gt_right\">78 </td>\n<td headers=\"stub_1_1 t\" class=\"gt_row gt_right\">2.683</td>\n<td headers=\"stub_1_1 p\" class=\"gt_row gt_right\">0.015</td>\n<td headers=\"stub_1_1 df\" class=\"gt_row gt_right\">19 </td>\n<td headers=\"stub_1_1 conf.low\" class=\"gt_row gt_right\">75.66</td>\n<td headers=\"stub_1_1 conf.high\" class=\"gt_row gt_right\">80.34</td>\n<td headers=\"stub_1_1 alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Visualizing Data\n\n### Scores against the national average\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec9_files/figure-revealjs/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec9_files/figure-revealjs/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n:::\n:::::\n\n## Exam Scores vs. National Average\n\n### Hypotheses\n\n> A professor wants to test if students in their class scored differently from the national average of `75` on an exam. A sample of `25` students has a mean score of `78` with a standard deviation of `10`.\n\n- Null Hypothesis ($H_0$): $\\mu = 75$ (no difference)\n\n- Alternative Hypothesis ($H_A$): $\\mu \\neq 75$ (scores differ)\n\n## Exam Scores vs. National Average\n\n### Manual\n\n::: callout-tip\n## Compute t\n\n$t = \\dfrac{\\color{blue}{\\bar{x}} - \\mu}{\\frac{\\color{orange}{s}}{\\sqrt{n}}} = \\dfrac{78 - 75}{\\frac{10}{\\sqrt{25}}} = \\dfrac{3}{2} = 1.5$\n:::\n\n::: callout-tip\n## Decide\n\nFor $df = 24$ ($25 - 1$), the critical value at $\\alpha = .05$ (two-tailed) is $\\pm 2.064$. Since $1.5 < 2.064$, we **fail to reject** $H_0$.\n:::\n\n## Exam Scores vs. National Average\n\n### Programmatic\n\n::: {.codewindow .r .codewindow-dark}\nexam_scores.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# For Reproducibility\nset.seed(131)\n\n# Simulate data, then rescale so the sample has exactly mean 78 and SD 10\nx <- rnorm(25)\nx <- 78 + 10 * (x - mean(x)) / sd(x)\n\nt.test(\n  x,\n  # The population mean to test against\n  mu = 75\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  x\nt = 1.5, df = 24, p-value = 0.1467\nalternative hypothesis: true mean is not equal to 75\n95 percent confidence interval:\n 73.8722 82.1278\nsample estimates:\nmean of x \n       78 \n```\n\n\n:::\n:::\n\n:::\n\n## APA Reporting\n\n> A one-sample t-test was conducted to determine whether students' exam scores differed from the national average ($\\mu$ = 75). Results were not statistically significant, `t(24) = 1.50, p = .147`, indicating that students performed similarly to the national average (`M = 78, SD = 10`).\n\n## Daily Coffee Consumption\n\n### Hypotheses\n\n> A coffee company claims that people drink an average of `3 cups` of coffee per day. A researcher samples `16 individuals`, finding a mean of `2.5 cups` and a standard deviation of `1 cup`.\n\n- Null Hypothesis ($H_0$): $\\mu = 3$\n\n- Alternative Hypothesis ($H_A$): $\\mu < 3$ (people drink less)\n\n## Daily Coffee Consumption\n\n### Manual\n\n::: callout-tip\n## Compute t\n\n$t = \\dfrac{2.5 - 3}{1 / \\sqrt{16}} = \\dfrac{-0.5}{0.25} = -2.0$\n:::\n\n::: callout-tip\n## Decide\n\nFor $df = 15$ ($16 - 1$), the critical t-value for a one-tailed test at $\\alpha = .05$ is $-1.753$. Since $-2.0 < -1.753$, we **reject** $H_0$.\n:::\n\n## Daily Coffee Consumption\n\n### Programmatic\n\n::: {.codewindow .r .codewindow-dark}\ncoffee.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# For Reproducibility\nset.seed(131)\n\n# Simulate data, then rescale so the sample has exactly mean 2.5 and SD 1\nx <- rnorm(16)\nx <- 2.5 + 1 * (x - mean(x)) / sd(x)\n\nt.test(\n  x,\n  # The value claimed by the company\n  mu = 3,\n  # Our alternative is directional: fewer than 3 cups\n  alternative = \"less\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  x\nt = -2, df = 15, p-value = 0.03197\nalternative hypothesis: true mean is less than 3\n95 percent confidence interval:\n     -Inf 2.938263\nsample estimates:\nmean of x \n      2.5 \n```\n\n\n:::\n:::\n\n:::\n\n## APA Reporting\n\n> A one-sample t-test was conducted to test whether daily coffee consumption was lower than the reported average of `3 cups`. Results showed a significant difference, `t(15) = -2.00, p = .032` (one-tailed), suggesting that people consume significantly fewer cups of coffee per day than reported (`M = 2.5, SD = 1`).\n\n## Sleep Duration Among College Students\n\n### Hypotheses\n\n> A health researcher believes college students sleep less than `7 hours` per night. A sample of `30 students` reports a mean of `6.5` hours with a standard deviation of `1.2` hours.\n\n- Null Hypothesis ($H_0$): $\\mu = 7$\n\n- Alternative Hypothesis ($H_A$): $\\mu < 7$\n\n## Sleep Duration Among College Students\n\n### Manual\n\n::: callout-tip\n## Compute t\n\n$t = \\dfrac{6.5 - 7}{1.2 / \\sqrt{30}} = \\dfrac{-0.5}{0.219} = -2.28$\n:::\n\n::: callout-tip\n## Decide\n\nFor $df = 29$, the critical t-value for a one-tailed test at $\\alpha = .05$ is $-1.699$. Since $-2.28 < -1.699$, we **reject** $H_0$.\n:::\n\n## Sleep Duration Among College Students\n\n### Programmatic\n\n::: {.codewindow .r .codewindow-dark}\nsleep.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# For Reproducibility\nset.seed(728)\n\n# Simulate data, then rescale so the sample has exactly mean 6.5 and SD 1.2\nx <- rnorm(30)\nx <- 6.5 + 1.2 * (x - mean(x)) / sd(x)\n\nt.test(\n  x,\n  # The value we are testing against\n  mu = 7,\n  # Our alternative is directional: less than 7 hours\n  alternative = \"less\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  x\nt = -2.2822, df = 29, p-value = 0.015\nalternative hypothesis: true mean is less than 7\n95 percent confidence interval:\n    -Inf 6.87226\nsample estimates:\nmean of x \n      6.5 \n```\n\n\n:::\n:::\n\n:::\n\n## APA Reporting\n\n> A one-sample t-test was conducted to test whether college students sleep fewer than 7 hours per night. Results were statistically significant, `t(29) = -2.28, p = .015` (one-tailed), indicating that students get significantly less sleep than the recommended amount (`M = 6.5, SD = 1.2`).\n",
    "supporting": [
      "lec9_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}