{
  "hash": "a54b336c0f53875eec0312aa44782a59",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Factorial ANOVA\"\nsubtitle: \"PSY 348: Lecture 13\"\nauthor: \"Dave Brocker\"\ninstitute: \"Farmingdale State College\"\nfooter: \"Factorial ANOVA | ⬡⬢⬡⬢⬡⬢\"\nformat:\n  revealjs:\n    theme: ../custom.scss\n    scrollable: true\n    width: 1600\n    height: 900\n    incremental: true\n    touch: true\n    chalkboard: true\n    lightbox: true\n    code-fold: true\n    slide-number: c/t\n    include-after-body: ../title-bg.html\n    drop:\n      engine: webr\nrevealjs-plugins:\n  - drop\n  - codewindow\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n## What is a Factorial ANOVA?\n\n### More than 1 independent variable\n\n- Up to now, we've looked at experiments that test **one question at a\n  time**.\n\n::::::: columns\n:::: {.column width=\"50%\"}\n::: callout-tip\n## t-test\n\nDo **two groups** differ?\n\n*\"Does drinking coffee make people happier than not drinking coffee?\"*\n:::\n::::\n\n:::: {.column width=\"50%\"}\n::: callout-tip\n## One-way ANOVA\n\nDo **more than two groups** differ on one IV?\n\n*\"Does coffee make people happier, compared to decaf or water?\"*\n:::\n::::\n:::::::\n\n- But in real life, there's *rarely* just one thing influencing\n  behavior.\n\n## Why Factorial ANOVA?\n\nA **Factorial ANOVA** allows us to test **more than one independent\nvariable (IV)** *at the same time.*\n\n- Instead of asking separate questions:\n\n  - \"Does coffee make people happier?\"\n\n  - \"Does watching TV make people happier?\"\n\n- We can now ask:\n\n  - \"Does coffee *and* watching TV make people happier?\"\n\n  - \"Does the effect of coffee *depend* on what you're watching?\"\n\n## The Power of Two (or More)\n\n### Testing as separate IVs\n\n```{dot}\ndigraph {\n  node [shape = box, style = \"rounded,filled\", fillcolor = \"white\", color = \"#5C715E\", fontname = \"Fira Sans\"]\n  edge [color = \"#5C715E\"]\n  bgcolor = \"#E9F1EC\"\n\n  subgraph cluster_coffee {\n    label = \"Independent Variable 1: Coffee\"\n    bgcolor = \"white\"\n    style = rounded\n    color = \"#8FAF9E\"\n\n    C1 [label=\"Coffee\"]\n    C2 [label=\"No Coffee\"]\n    H1 [label=\"Happiness\"]\n    H2 [label=\"Happiness\"]\n\n    C1 -> H1\n    C2 -> H2\n  }\n\n  subgraph cluster_tv {\n    label = \"Independent Variable 2: TV Show\"\n    bgcolor = \"white\"\n    style = rounded\n    color = \"#8FAF9E\"\n\n    TV [label=\"TV\"]\n    NTV [label=\"No TV\"]\n    H3 [label=\"Happiness\"]\n    H4 [label=\"Happiness\"]\n\n    TV -> H3\n    NTV -> H4\n  }\n}\n```\n\n## The Power of Two (or More)\n\n### Combining IVs\n\n```{dot}\ndigraph {\n  node [shape = box, style = \"rounded,filled\", fillcolor = \"white\", color = \"#5C715E\", fontname = \"Fira Sans\"]\n  edge [color = \"#5C715E\"]\n  bgcolor = \"#E9F1EC\"\n\n  Coffee [label=\"Coffee\"]\n  NoCoffee [label=\"No Coffee\"]\n  Dark [label=\"Watch Dark\"]\n  NoDark [label=\"No Dark\"]\n\n  subgraph cluster_design {\n    label = \"2 × 2 Factorial Design\"\n    bgcolor = \"white\"\n    style = rounded\n    color = \"#8FAF9E\"\n\n    CoffeeDark [label=\"Coffee + Dark\"]\n    CoffeeNoDark [label=\"Coffee + No Dark\"]\n    NoCoffeeDark [label=\"No Coffee + Dark\"]\n    NoCoffeeNoDark [label=\"No Coffee + No Dark\"]\n\n    Coffee -> CoffeeDark\n    Coffee -> CoffeeNoDark\n    NoCoffee -> NoCoffeeDark\n    NoCoffee -> NoCoffeeNoDark\n\n    Dark -> CoffeeDark\n    Dark -> NoCoffeeDark\n    NoDark -> CoffeeNoDark\n    NoDark -> NoCoffeeNoDark\n  }\n\n  Happiness1 [label=\"Happiness\", style = \"rounded,filled\", fillcolor = \"#DCE8E1\"]\n  Happiness2 [label=\"Happiness\", style = \"rounded,filled\", fillcolor = \"#DCE8E1\"]\n  Happiness3 [label=\"Happiness\", style = \"rounded,filled\", fillcolor = \"#DCE8E1\"]\n  Happiness4 [label=\"Happiness\", style = \"rounded,filled\", fillcolor = \"#DCE8E1\"]\n\n  CoffeeDark -> Happiness1\n  CoffeeNoDark -> Happiness2\n  NoCoffeeDark -> Happiness3\n  NoCoffeeNoDark -> Happiness4\n}\n```\n\n## The Power of Two (or More)\n\n### Three questions at once\n\n:::::: term-list\n::: fragment\n\n[Main Effect 1]{.term-pill}\n\n: Does IV1 alone affect the outcome? (Coffee → Happiness)\n:::\n\n::: fragment\n\n[Main Effect 2]{.term-pill}\n\n: Does IV2 alone affect the outcome? (TV Show → Happiness)\n:::\n\n::: fragment\n\n[Interaction Effect]{.term-pill}\n\n: Does the effect of one variable depend on the other? (Maybe coffee\n  *only* helps if you're watching *TV!*)\n:::\n::::::\n\n## Why Not Just Run Multiple t-tests?\n\n### You could compare...\n\n- Coffee vs. No Coffee\n\n- Dark vs. No Dark\n\n- Coffee + Dark vs. everything else\n\n  - but each additional t-test increases your **Type I error rate**\n    (false positives).\n\n- A Factorial ANOVA solves that problem by testing all these\n  relationships **in one model**, controlling for shared variance and\n  examining combined effects.\n\n## In Other Words...\n\n| Test Type | Question | Example |\n|:-----------------------|:-----------------------|:-----------------------|\n| **t-test** | Do two groups differ? | Coffee vs. No Coffee |\n| **One-Way ANOVA** | Do 3+ groups differ on one IV? | Decaf, Coffee, Energy Drink |\n| **Factorial ANOVA** | How do **two or more IVs** work together? | Coffee × TV Show → Happiness |\n\n## The Goal of Research\n\n- The goal of good research is to **narrow in on the real sources of\n  variation.**\n\n- Factorial ANOVA lets us see *not just whether variables matter,* but\n  *how they matter together.*\n\n> It's not just what causes an effect, it's what combinations of causes\n> create patterns we care about.\n\n## Factorial ANOVA\n\n### Four sources of variance\n\n::::::: term-list\n::: fragment\n\n[Between IV 1]{.term-pill}\n\n: Variance between the groups of the first IV (main effect 1).\n:::\n\n::: fragment\n\n[Between IV 2]{.term-pill}\n\n: Variance between the groups of the second IV (main effect 2).\n:::\n\n::: fragment\n\n[Interaction]{.term-pill}\n\n: Variance from the **combination** of the groups (the cells).\n:::\n\n::: fragment\n\n[Error]{.term-pill}\n\n: Variance **within** each cell, around that cell's own mean.\n:::\n:::::::\n\n## Understanding Main Effects\n\n::::: columns\n::: {.column width=\"50%\"}\n- The **main effect of Coffee** asks:\n\n  - *On average, does drinking coffee make people happier than not\n    drinking coffee?*\\\n    (Regardless of whether they watched *TV* or not.)\n\n- The **main effect of Watching TV** asks:\n\n  - *On average, does watching TV make people happier than not watching\n    it?*\\\n    (Regardless of whether they had coffee or not.)\n:::\n\n::: {.column width=\"50%\"}\n```{dot}\ndigraph {\n  rankdir = RL\n  node [shape = box, style = \"rounded,filled\", fillcolor = \"white\", color = \"#5C715E\", fontname = \"Fira Sans\"]\n  edge [color = \"#5C715E\"]\n  bgcolor = \"#E9F1EC\"\n\n  subgraph cluster_coffee {\n    label = \"Independent Variable 1: Coffee\"\n    bgcolor = \"white\"\n    style = rounded\n    color = \"#8FAF9E\"\n\n    C1 [label=\"Coffee\"]\n    C2 [label=\"No Coffee\"]\n    H1 [label=\"Happiness\"]\n    H2 [label=\"Happiness\"]\n\n    H1 -> C1\n    H2 -> C2\n  }\n\n  subgraph cluster_tv {\n    label = \"Independent Variable 2: TV Show\"\n    bgcolor = \"white\"\n    style = rounded\n    color = \"#8FAF9E\"\n\n    TV [label=\"TV\"]\n    NTV [label=\"No TV\"]\n    H3 [label=\"Happiness\"]\n    H4 [label=\"Happiness\"]\n\n    H3 -> TV\n    H4 -> NTV\n  }\n}\n```\n:::\n:::::\n\n## Understanding Main Effects\n\n### The 2 × 2 table of means\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xbyknbbjyv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xbyknbbjyv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xbyknbbjyv thead, #xbyknbbjyv tbody, #xbyknbbjyv tfoot, #xbyknbbjyv tr, #xbyknbbjyv td, #xbyknbbjyv th {\n  border-style: none;\n}\n\n#xbyknbbjyv p {\n  margin: 0;\n  padding: 0;\n}\n\n#xbyknbbjyv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 28px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xbyknbbjyv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xbyknbbjyv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xbyknbbjyv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xbyknbbjyv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xbyknbbjyv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xbyknbbjyv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xbyknbbjyv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xbyknbbjyv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xbyknbbjyv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xbyknbbjyv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xbyknbbjyv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xbyknbbjyv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xbyknbbjyv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xbyknbbjyv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xbyknbbjyv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xbyknbbjyv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xbyknbbjyv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xbyknbbjyv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xbyknbbjyv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xbyknbbjyv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xbyknbbjyv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xbyknbbjyv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xbyknbbjyv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xbyknbbjyv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xbyknbbjyv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xbyknbbjyv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xbyknbbjyv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xbyknbbjyv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xbyknbbjyv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xbyknbbjyv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xbyknbbjyv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xbyknbbjyv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xbyknbbjyv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xbyknbbjyv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xbyknbbjyv .gt_left {\n  text-align: left;\n}\n\n#xbyknbbjyv .gt_center {\n  text-align: center;\n}\n\n#xbyknbbjyv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xbyknbbjyv .gt_font_normal {\n  font-weight: normal;\n}\n\n#xbyknbbjyv .gt_font_bold {\n  font-weight: bold;\n}\n\n#xbyknbbjyv .gt_font_italic {\n  font-style: italic;\n}\n\n#xbyknbbjyv .gt_super {\n  font-size: 65%;\n}\n\n#xbyknbbjyv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xbyknbbjyv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xbyknbbjyv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xbyknbbjyv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xbyknbbjyv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xbyknbbjyv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xbyknbbjyv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xbyknbbjyv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xbyknbbjyv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\" style><span data-qmd-base64=\"KioyIMOXIDIgRmFjdG9yaWFsIERlc2lnbjogQ29mZmVlIMOXIFRWKio=\"><span class='gt_from_md'><strong>2 × 2 Factorial Design: Coffee × TV</strong></span></span></td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Mean happiness by condition (cell means)</td>\n    </tr>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"TV\">Watched TV?</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"**Coffee condition**\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipDb2ZmZWUgY29uZGl0aW9uKio=\"><span class='gt_from_md'><strong>Coffee condition</strong></span></span></div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Coffee\">Coffee</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"No-Coffee\">No Coffee</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"TV\" class=\"gt_row gt_center\">TV</td>\n<td headers=\"Coffee\" class=\"gt_row gt_right\">3.0</td>\n<td headers=\"No Coffee\" class=\"gt_row gt_right\">4.0</td></tr>\n    <tr><td headers=\"TV\" class=\"gt_row gt_center\">No TV</td>\n<td headers=\"Coffee\" class=\"gt_row gt_right\">4.0</td>\n<td headers=\"No Coffee\" class=\"gt_row gt_right\">8.0</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"zqtdtkqiqm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zqtdtkqiqm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zqtdtkqiqm thead, #zqtdtkqiqm tbody, #zqtdtkqiqm tfoot, #zqtdtkqiqm tr, #zqtdtkqiqm td, #zqtdtkqiqm th {\n  border-style: none;\n}\n\n#zqtdtkqiqm p {\n  margin: 0;\n  padding: 0;\n}\n\n#zqtdtkqiqm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 28px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zqtdtkqiqm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zqtdtkqiqm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zqtdtkqiqm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zqtdtkqiqm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zqtdtkqiqm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zqtdtkqiqm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zqtdtkqiqm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zqtdtkqiqm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zqtdtkqiqm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zqtdtkqiqm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zqtdtkqiqm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zqtdtkqiqm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zqtdtkqiqm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zqtdtkqiqm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zqtdtkqiqm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zqtdtkqiqm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zqtdtkqiqm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zqtdtkqiqm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zqtdtkqiqm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zqtdtkqiqm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zqtdtkqiqm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zqtdtkqiqm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zqtdtkqiqm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zqtdtkqiqm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zqtdtkqiqm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zqtdtkqiqm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zqtdtkqiqm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zqtdtkqiqm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zqtdtkqiqm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zqtdtkqiqm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zqtdtkqiqm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zqtdtkqiqm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zqtdtkqiqm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zqtdtkqiqm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zqtdtkqiqm .gt_left {\n  text-align: left;\n}\n\n#zqtdtkqiqm .gt_center {\n  text-align: center;\n}\n\n#zqtdtkqiqm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zqtdtkqiqm .gt_font_normal {\n  font-weight: normal;\n}\n\n#zqtdtkqiqm .gt_font_bold {\n  font-weight: bold;\n}\n\n#zqtdtkqiqm .gt_font_italic {\n  font-style: italic;\n}\n\n#zqtdtkqiqm .gt_super {\n  font-size: 65%;\n}\n\n#zqtdtkqiqm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zqtdtkqiqm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zqtdtkqiqm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zqtdtkqiqm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zqtdtkqiqm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zqtdtkqiqm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zqtdtkqiqm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zqtdtkqiqm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zqtdtkqiqm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\" style><span data-qmd-base64=\"KipXaXRoIG1hcmdpbmFsIG1lYW5zKio=\"><span class='gt_from_md'><strong>With marginal means</strong></span></span></td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Row and column means show the main effects</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"TV\">Watched TV?</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Coffee\">Coffee</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"No-Coffee\">No Coffee</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Row-mean\">Row mean</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"TV\" class=\"gt_row gt_center\">TV</td>\n<td headers=\"Coffee\" class=\"gt_row gt_right\">3.0</td>\n<td headers=\"No Coffee\" class=\"gt_row gt_right\">4.0</td>\n<td headers=\"Row mean\" class=\"gt_row gt_right\" style=\"font-weight: bold;\">3.5</td></tr>\n    <tr><td headers=\"TV\" class=\"gt_row gt_center\">No TV</td>\n<td headers=\"Coffee\" class=\"gt_row gt_right\">4.0</td>\n<td headers=\"No Coffee\" class=\"gt_row gt_right\">8.0</td>\n<td headers=\"Row mean\" class=\"gt_row gt_right\" style=\"font-weight: bold;\">6.0</td></tr>\n    <tr><td headers=\"TV\" class=\"gt_row gt_center\" style=\"font-weight: bold;\">Column mean</td>\n<td headers=\"Coffee\" class=\"gt_row gt_right\" style=\"font-weight: bold;\">3.5</td>\n<td headers=\"No Coffee\" class=\"gt_row gt_right\" style=\"font-weight: bold;\">6.0</td>\n<td headers=\"Row mean\" class=\"gt_row gt_right\" style=\"font-weight: bold;\">4.8</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n:::::\n\n- Coffee main effect: 3.50 (coffee) vs.\n  6.00 (no coffee).\n\n- TV main effect: 3.50 (TV) vs. 6.00 (no\n  TV).\n\n## Visualizing Interactions\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec13fct_files/figure-revealjs/unnamed-chunk-7-1.png){width=624}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n- Each line is one level of the first IV (coffee). The x-axis is the second IV (TV).\n\n- **Parallel** lines mean **no interaction**: the effect of one IV doesn't depend on the other.\n\n- Here the lines are **not parallel**. Without coffee, TV drops happiness a lot (8.00 to 4.00). With coffee, TV matters much less (4.00 to 3.00). That is an interaction.\n:::\n:::::\n\n## Visualizing Interactions\n\n### A main effect hides the story\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec13fct_files/figure-revealjs/unnamed-chunk-8-1.png){width=768}\n:::\n:::\n\n\n- Averaged over TV, coffee drinkers are less happy\n  (3.50 vs. 6.00). The\n  interaction plot shows the full story: the size of the difference\n  **depends on whether people watched TV**.\n\n## Visualizing Interactions\n\n### From main effect to interaction\n\n![](images/inx.gif)\n\n## Calculating F Values\n\n::: callout-tip\n## Degrees of freedom\n\n- Between groups 1: $df_{B_1} = k_1 - 1$\n\n- Between groups 2: $df_{B_2} = k_2 - 1$\n\n- Interaction: $df_{Interaction} = (k_1 - 1) \\times (k_2 - 1)$\n\n- Error: $df_{Error} = N - (k_1 \\times k_2)$\n\n- Total: $df_{Total} = N - 1$\n:::\n\n## Calculating MS\n\n::: callout-tip\n## Each MS is an SS divided by its df\n\n$MS_{B_1} = \\dfrac{SS_{B_1}}{k_1-1} \\qquad MS_{B_2} = \\dfrac{SS_{B_2}}{k_2-1}$\n\n$MS_{Interaction} = \\dfrac{SS_{Interaction}}{(k_1-1)(k_2-1)} \\qquad MS_{Error} = \\dfrac{SS_{Error}}{N-(k_1 k_2)}$\n:::\n\n## Calculating F\n\n::: callout-tip\n## Every F uses the same denominator\n\n$F_A = \\dfrac{MS_{B_1}}{MS_{Error}} \\qquad F_B = \\dfrac{MS_{B_2}}{MS_{Error}} \\qquad F_{AB} = \\dfrac{MS_{Interaction}}{MS_{Error}}$\n:::\n\n## How Many F's?\n\n```{dot}\ndigraph F_Tests {\n  size=5\n  rankdir=TB\n  bgcolor=\"#E9F1EC\"\n  node [shape=box, style=\"rounded,filled\", fontname=\"Fira Sans\", color = \"#5C715E\", fillcolor = \"white\"]\n  edge [color = \"#5C715E\"]\n\n  oneway [label=\"1-Way ANOVA\\n→ 1 F-test\\n(Main Effect Only)\"]\n  twoway [label=\"2-Way ANOVA (2×2)\\n→ 3 F-tests\\n(2 Main Effects + 1 Interaction)\"]\n  threeway [label=\"3-Way ANOVA (2×2×2)\\n→ 7 F-tests\\n(3 Main + 3 Two-Way + 1 Three-Way)\"]\n  fourway [label=\"4-Way ANOVA (2×2×2×2)\\n→ 15 F-tests\\n(4 Main + 6 Two-Way + 4 Three-Way + 1 Four-Way)\"]\n\n  oneway -> twoway -> threeway -> fourway\n\n  note [label=\"General Formula:\\nF-tests = 2ⁿ - 1\\n(where n = # of IVs)\", shape=note, fillcolor=\"#DCE8E1\", color=\"#5C715E\", fontcolor=\"#2F3E46\"]\n  threeway -> note [style=dotted, color=\"#888\"]\n}\n```\n\n## Factorial ANOVA in R\n\n### The model formula\n\n::: {.codewindow .r .codewindow-dark}\nfactorial_anova.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# A * B means: main effect of A + main effect of B + the A:B interaction\nfit <- aov(weight_loss ~ diet_type * exercise_regimen, data = wl)\n\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                           Df Sum Sq Mean Sq F value   Pr(>F)    \ndiet_type                   1 101.27  101.27  41.899 4.06e-09 ***\nexercise_regimen            1 114.06  114.06  47.191 6.41e-10 ***\ndiet_type:exercise_regimen  1   9.07    9.07   3.751   0.0557 .  \nResiduals                  96 232.02    2.42                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n:::\n\n- `diet_type * exercise_regimen` is shorthand for\n  `diet_type + exercise_regimen + diet_type:exercise_regimen`.\n\n- Each row of the table is one F-test: two main effects and the\n  interaction.\n\n## Interpreting Results\n\n### Example 1: weight loss, diet type × exercise regimen\n\n::: panel-tabset\n## Table\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"abhpcemlas\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#abhpcemlas table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#abhpcemlas thead, #abhpcemlas tbody, #abhpcemlas tfoot, #abhpcemlas tr, #abhpcemlas td, #abhpcemlas th {\n  border-style: none;\n}\n\n#abhpcemlas p {\n  margin: 0;\n  padding: 0;\n}\n\n#abhpcemlas .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 26px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 80%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#abhpcemlas .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#abhpcemlas .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#abhpcemlas .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#abhpcemlas .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#abhpcemlas .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#abhpcemlas .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#abhpcemlas .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#abhpcemlas .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#abhpcemlas .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#abhpcemlas .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#abhpcemlas .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#abhpcemlas .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#abhpcemlas .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#abhpcemlas .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#abhpcemlas .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#abhpcemlas .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#abhpcemlas .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#abhpcemlas .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#abhpcemlas .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#abhpcemlas .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#abhpcemlas .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#abhpcemlas .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#abhpcemlas .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#abhpcemlas .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#abhpcemlas .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#abhpcemlas .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#abhpcemlas .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#abhpcemlas .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#abhpcemlas .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#abhpcemlas .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#abhpcemlas .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#abhpcemlas .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#abhpcemlas .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#abhpcemlas .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#abhpcemlas .gt_left {\n  text-align: left;\n}\n\n#abhpcemlas .gt_center {\n  text-align: center;\n}\n\n#abhpcemlas .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#abhpcemlas .gt_font_normal {\n  font-weight: normal;\n}\n\n#abhpcemlas .gt_font_bold {\n  font-weight: bold;\n}\n\n#abhpcemlas .gt_font_italic {\n  font-style: italic;\n}\n\n#abhpcemlas .gt_super {\n  font-size: 65%;\n}\n\n#abhpcemlas .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#abhpcemlas .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#abhpcemlas .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#abhpcemlas .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#abhpcemlas .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#abhpcemlas .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#abhpcemlas .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#abhpcemlas .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#abhpcemlas div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Source\">Source</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"SS\">SS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"MS\">MS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">diet_type</td>\n<td headers=\"df\" class=\"gt_row gt_center\">1</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">101.27</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">101.27</td>\n<td headers=\"F\" class=\"gt_row gt_center\">41.90</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt;.001</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center gt_striped\">exercise_regimen</td>\n<td headers=\"df\" class=\"gt_row gt_center gt_striped\">1</td>\n<td headers=\"SS\" class=\"gt_row gt_center gt_striped\">114.06</td>\n<td headers=\"MS\" class=\"gt_row gt_center gt_striped\">114.06</td>\n<td headers=\"F\" class=\"gt_row gt_center gt_striped\">47.19</td>\n<td headers=\"p\" class=\"gt_row gt_center gt_striped\">&lt;.001</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">diet_type:exercise_regimen</td>\n<td headers=\"df\" class=\"gt_row gt_center\">1</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">9.07</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">9.07</td>\n<td headers=\"F\" class=\"gt_row gt_center\">3.75</td>\n<td headers=\"p\" class=\"gt_row gt_center\">0.056</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center gt_striped\">Residuals</td>\n<td headers=\"df\" class=\"gt_row gt_center gt_striped\">96</td>\n<td headers=\"SS\" class=\"gt_row gt_center gt_striped\">232.02</td>\n<td headers=\"MS\" class=\"gt_row gt_center gt_striped\">2.42</td>\n<td headers=\"F\" class=\"gt_row gt_center gt_striped\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center gt_striped\">–</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"6\"> <span data-qmd-base64=\"KkRlcGVuZGVudCBWYXJpYWJsZTogV2VpZ2h0IExvc3MqPGJyPipEaWV0IFR5cGU6IExvdyBDYXJiLCBMb3cgRmF0Kjxicj4qRXhlcmNpc2UgUmVnaW1lbjogQ2FyZGlvLCBTdHJlbmd0aCo=\"><span class='gt_from_md'><em>Dependent Variable: Weight Loss</em><br><em>Diet Type: Low Carb, Low Fat</em><br><em>Exercise Regimen: Cardio, Strength</em></span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec13fct_files/figure-revealjs/unnamed-chunk-12-1.png){width=864}\n:::\n:::\n\n:::\n\n## Interpreting the Fs in 2-way ANOVA\n\n- $F_A$ (Diet type): F(1, 96) = 41.90, p < .001\n\n- $F_B$ (Exercise regimen): F(1, 96) = 47.19, p < .001\n\n- $F_{AB}$ (Diet × Exercise):\n  F(1, 96) = 3.75, p = .056 (*not significant*)\n\n::: {.callout-tip appearance=\"minimal\"}\nBoth main effects are significant and the interaction is not, so the\neffect of diet is about the **same** at each exercise regimen (and vice\nversa): the lines in the plot are close to parallel.\n:::\n\n## Interpreting Results\n\n### Example 2: political interest, gender × education\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"iiycruooyt\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#iiycruooyt table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#iiycruooyt thead, #iiycruooyt tbody, #iiycruooyt tfoot, #iiycruooyt tr, #iiycruooyt td, #iiycruooyt th {\n  border-style: none;\n}\n\n#iiycruooyt p {\n  margin: 0;\n  padding: 0;\n}\n\n#iiycruooyt .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 26px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 80%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#iiycruooyt .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#iiycruooyt .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#iiycruooyt .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#iiycruooyt .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iiycruooyt .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iiycruooyt .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iiycruooyt .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#iiycruooyt .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#iiycruooyt .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#iiycruooyt .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#iiycruooyt .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#iiycruooyt .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#iiycruooyt .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#iiycruooyt .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#iiycruooyt .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#iiycruooyt .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#iiycruooyt .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#iiycruooyt .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iiycruooyt .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#iiycruooyt .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#iiycruooyt .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#iiycruooyt .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iiycruooyt .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#iiycruooyt .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#iiycruooyt .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iiycruooyt .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iiycruooyt .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#iiycruooyt .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iiycruooyt .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#iiycruooyt .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iiycruooyt .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iiycruooyt .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iiycruooyt .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iiycruooyt .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iiycruooyt .gt_left {\n  text-align: left;\n}\n\n#iiycruooyt .gt_center {\n  text-align: center;\n}\n\n#iiycruooyt .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#iiycruooyt .gt_font_normal {\n  font-weight: normal;\n}\n\n#iiycruooyt .gt_font_bold {\n  font-weight: bold;\n}\n\n#iiycruooyt .gt_font_italic {\n  font-style: italic;\n}\n\n#iiycruooyt .gt_super {\n  font-size: 65%;\n}\n\n#iiycruooyt .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#iiycruooyt .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#iiycruooyt .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#iiycruooyt .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#iiycruooyt .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#iiycruooyt .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#iiycruooyt .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#iiycruooyt .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#iiycruooyt div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Source\">Source</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"SS\">SS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"MS\">MS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">gender</td>\n<td headers=\"df\" class=\"gt_row gt_center\">1</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">216.57</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">216.57</td>\n<td headers=\"F\" class=\"gt_row gt_center\">244.15</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt;.001</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center gt_striped\">education_level</td>\n<td headers=\"df\" class=\"gt_row gt_center gt_striped\">3</td>\n<td headers=\"SS\" class=\"gt_row gt_center gt_striped\">198.31</td>\n<td headers=\"MS\" class=\"gt_row gt_center gt_striped\">66.10</td>\n<td headers=\"F\" class=\"gt_row gt_center gt_striped\">74.52</td>\n<td headers=\"p\" class=\"gt_row gt_center gt_striped\">&lt;.001</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">gender:education_level</td>\n<td headers=\"df\" class=\"gt_row gt_center\">3</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">23.65</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">7.88</td>\n<td headers=\"F\" class=\"gt_row gt_center\">8.89</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt;.001</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center gt_striped\">Residuals</td>\n<td headers=\"df\" class=\"gt_row gt_center gt_striped\">92</td>\n<td headers=\"SS\" class=\"gt_row gt_center gt_striped\">81.61</td>\n<td headers=\"MS\" class=\"gt_row gt_center gt_striped\">0.89</td>\n<td headers=\"F\" class=\"gt_row gt_center gt_striped\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center gt_striped\">–</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"6\"> <span data-qmd-base64=\"KkRlcGVuZGVudCBWYXJpYWJsZTogUG9saXRpY2FsIEludGVyZXN0Kjxicj4qR2VuZGVyOiBNYWxlLCBGZW1hbGUqPGJyPipFZHVjYXRpb246IEhpZ2ggU2Nob29sLCBCYWNoZWxvcidzLCBNYXN0ZXIncywgUGhEKg==\"><span class='gt_from_md'><em>Dependent Variable: Political Interest</em><br><em>Gender: Male, Female</em><br><em>Education: High School, Bachelor’s, Master’s, PhD</em></span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n- Gender: F(1, 92) = 244.15, p < .001\n\n- Education: F(3, 92) = 74.52, p < .001\n\n- Gender × Education: F(3, 92) = 8.89, p < .001\n\n## Interpreting F's\n\n### Visually\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec13fct_files/figure-revealjs/unnamed-chunk-14-1.png){width=960}\n:::\n:::\n\n\n- The lines are **not parallel**: the effect of education depends on\n  gender, which is why the **interaction** is significant.\n\n## Effect Size: Partial Eta Squared\n\n::: callout-tip\n## $\\eta_p^2$\n\n$\\eta_p^2 = \\dfrac{SS_{effect}}{SS_{effect} + SS_{error}}$ (one value\nfor each F)\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vtwvzmekou\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vtwvzmekou table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vtwvzmekou thead, #vtwvzmekou tbody, #vtwvzmekou tfoot, #vtwvzmekou tr, #vtwvzmekou td, #vtwvzmekou th {\n  border-style: none;\n}\n\n#vtwvzmekou p {\n  margin: 0;\n  padding: 0;\n}\n\n#vtwvzmekou .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 28px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 55%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vtwvzmekou .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vtwvzmekou .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vtwvzmekou .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vtwvzmekou .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vtwvzmekou .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vtwvzmekou .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vtwvzmekou .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vtwvzmekou .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vtwvzmekou .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vtwvzmekou .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vtwvzmekou .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vtwvzmekou .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vtwvzmekou .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vtwvzmekou .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vtwvzmekou .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vtwvzmekou .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vtwvzmekou .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vtwvzmekou .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vtwvzmekou .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vtwvzmekou .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vtwvzmekou .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vtwvzmekou .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vtwvzmekou .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vtwvzmekou .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vtwvzmekou .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vtwvzmekou .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vtwvzmekou .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vtwvzmekou .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vtwvzmekou .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vtwvzmekou .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vtwvzmekou .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vtwvzmekou .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vtwvzmekou .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vtwvzmekou .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vtwvzmekou .gt_left {\n  text-align: left;\n}\n\n#vtwvzmekou .gt_center {\n  text-align: center;\n}\n\n#vtwvzmekou .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vtwvzmekou .gt_font_normal {\n  font-weight: normal;\n}\n\n#vtwvzmekou .gt_font_bold {\n  font-weight: bold;\n}\n\n#vtwvzmekou .gt_font_italic {\n  font-style: italic;\n}\n\n#vtwvzmekou .gt_super {\n  font-size: 65%;\n}\n\n#vtwvzmekou .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vtwvzmekou .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vtwvzmekou .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vtwvzmekou .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vtwvzmekou .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vtwvzmekou .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vtwvzmekou .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vtwvzmekou .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vtwvzmekou div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Effect\">Effect</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Partial-η²\">Partial η²</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Effect\" class=\"gt_row gt_left\">Diet type</td>\n<td headers=\"Partial η²\" class=\"gt_row gt_right\">0.304</td></tr>\n    <tr><td headers=\"Effect\" class=\"gt_row gt_left gt_striped\">Exercise regimen</td>\n<td headers=\"Partial η²\" class=\"gt_row gt_right gt_striped\">0.330</td></tr>\n    <tr><td headers=\"Effect\" class=\"gt_row gt_left\">Diet × Exercise</td>\n<td headers=\"Partial η²\" class=\"gt_row gt_right\">0.038</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n- Benchmarks are the same as one-way ANOVA: about .01 small, .06 medium,\n  .14 large.\n\n## Following Up an Interaction\n\n### What if the interaction is significant?\n\n- A significant interaction means the effect of one IV **depends** on\n  the other, so interpret the **cells**, not just the main effects.\n\n- Compare the cell means with a post-hoc test, or test the effect of one\n  IV **at each level** of the other (*simple effects*).\n\n::: {.codewindow .r .codewindow-dark}\nfollow_up.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Tukey's HSD for every pair of cells (the four combinations)\nTukeyHSD(fit, \"diet_type:exercise_regimen\")\n```\n:::\n\n:::\n\n- In the weight-loss example the interaction was **not** significant, so\n  we interpret the two main effects.\n\n## Assumptions of Factorial ANOVA\n\n::: callout-important\n## Assumptions\n\n1.  **The DV is continuous** (interval or ratio scale).\n2.  **Observations are independent.** Each person is in only one cell.\n3.  **Normality:** scores (residuals) are approximately normal in each\n    cell.\n4.  **Homogeneity of variance:** the cells have similar variances\n    (Levene's Test).\n:::\n\n::: {.codewindow .r .codewindow-dark}\nassumptions.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(car)\nleveneTest(weight_loss ~ diet_type * exercise_regimen, data = wl)\nshapiro.test(residuals(fit))\n```\n:::\n\n:::\n\n## Reporting F\n\n> If asked to report findings in terms of the Null Hypothesis (H~0~),\n> you should report findings as:\n\n- Reject $H_0$, or\n\n- Fail to Reject $H_0$\n\n## Reporting F\n\nIf asked to report findings in general or for publication, you need\n**EACH** F-value:\n\n- $F$(df between, df error) = F-value\n\n- the corresponding p-value\n\n- an effect size ($\\eta_p^2$)\n\n- for significant results: the means and standard deviations of each\n  group\n\n## Reporting F\n\n### Main effect of diet type\n\n> Participants on the low-carb diet (*M* = 10.06, *SD*\n> = 2.13) lost significantly more weight than\n> participants on the low-fat diet (*M* = 8.04, *SD* =\n> 1.65), *F(1, 96) = 41.90, p < .001*, $\\eta_p^2$\n> = 0.30.\n\n## Reporting F\n\n### Main effect of exercise regimen\n\n> Participants who did cardio (*M* = 10.12, *SD* =\n> 1.98) lost significantly more weight than\n> participants who did strength training (*M* = 7.98,\n> *SD* = 1.75),\n> *F(1, 96) = 47.19, p < .001*, $\\eta_p^2$ =\n> 0.33.\n\n## Reporting F\n\n### Interaction\n\n> **If NOT significant:** The interaction between diet type and exercise\n> regimen was not significant,\n> *F(1, 96) = 3.75, p = .056*.\n\n> **If significant:** report the cell means and standard deviations, and\n> describe the pattern (e.g., \"the benefit of cardio was larger for the\n> low-carb diet\").\n\n## Factorial ANOVA Wrap-Up\n\n### Connecting the dots\n\n- **Big picture:** a factorial ANOVA lets us test **multiple independent\n  variables** at once.\n\n  - Not just whether each matters, but *whether they matter together.*\n\n## Understanding Interactions\n\n### What it tests\n\n| Source | Question | Interpretation |\n|:-----------------------|:-----------------------|:-----------------------|\n| **Main Effect A** | Does IV1 (e.g., Coffee) affect the DV on average? | \"Coffee drinkers happier?\" |\n| **Main Effect B** | Does IV2 (e.g., TV Show) affect the DV on average? | \"TV watchers happier?\" |\n| **Interaction (A × B)** | Does the effect of Coffee *depend* on watching TV? | \"Coffee only helps if watching TV?\" |",
    "supporting": [
      "lec13fct_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}