{
  "hash": "34fe2cce4d97e42f14ac4857d7ad12c3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Within-Subjects ANOVA\"\nsubtitle: \"PSY 348: Lecture 14\"\nauthor: \"Dave Brocker\"\ninstitute: \"Farmingdale State College\"\nfooter: \"Within-Subjects ANOVA | ⬡⬢⬡⬢⬡⬢\"\nformat:\n  revealjs:\n    theme: ../custom.scss\n    scrollable: true\n    width: 1600\n    height: 900\n    incremental: true\n    touch: true\n    chalkboard: true\n    lightbox: true\n    code-fold: true\n    slide-number: c/t\n    include-after-body: ../title-bg.html\n    drop:\n      engine: webr\nrevealjs-plugins:\n  - drop\n  - codewindow\n---\n\n\n\n# When to Use Repeated Measures ANOVA\n\nUse Repeated Measures ANOVA when:\n\n- You have the **same participants measured more than once** (e.g., pre-test/post-test).\n\n- You're interested in **changes over time** or **under different conditions**.\n\n  - Testing whether students' enjoyment of statistics improves after receiving lollipops for 2 weeks.\n\n# Between vs. Within Subjects ANOVA\n\n::::::: columns\n:::: {.column width=\"50%\"}\n::: callout-tip\n## Between-subjects ANOVA\n\n- Compares means **between groups** (Group A vs. B vs. C).\n\n- Error comes from individual differences **between people**.\n:::\n::::\n\n:::: {.column width=\"50%\"}\n::: callout-important\n## Within-subjects (repeated measures) ANOVA\n\n- Compares means **within the same participants** over time or conditions.\n\n- **Controls for** individual differences.\n:::\n::::\n:::::::\n\n# Pizza and Productivity Study\n\n## A Repeated-Measures Design\n\n:::::: columns\n:::: {.column width=\"50%\"}\n::: callout-tip\n## Design\n\n- **Objective:** test whether productivity changes over time.\n\n- **IV:** time\n\n  1.  Before lunch\n  2.  10 minutes after pizza\n  3.  1 hour after pizza\n\n- The **same participants** are measured at each timepoint.\n\n- **DV:** number of emails written in 10 minutes.\n:::\n::::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-2-1.png){width=624}\n:::\n:::\n\n:::\n::::::\n\n## Visualizing the Data\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-3-1.png){width=1056}\n:::\n:::\n\n\n## Why Repeated-Measures ANOVA?\n\n- Can't use multiple paired-samples t-tests.\n\n  - Alpha inflation increases the Type I error rate.\n\n- Repeated-Measures ANOVA allows us to:\n\n  - Compare within-subject changes across time.\n\n  - **Control for individual variability.**\n\n  - Test for an overall **time effect**.\n\n## Within-Subjects ANOVA\n\n### Where the variance comes from\n\n- **Between-subjects** ANOVA splits variance into **between-group** and **error** (within-group) parts.\n\n- **Within-subjects** ANOVA has a third source, because each person contributes several scores:\n\n:::::: term-list\n::: fragment\n\n[Time]{.term-pill}\n\n: How the **means** vary across the time points (the effect we care about).\n:::\n\n::: fragment\n\n[Subjects]{.term-pill}\n\n: How people differ from **each other overall**.\n:::\n\n::: fragment\n\n[Error]{.term-pill}\n\n: What is left over once time and subjects are accounted for.\n:::\n::::::\n\n## Within-Subjects ANOVA\n\n### Partitioning the variability\n\n```{dot}\ndigraph {\n  node[shape = \"box\", style = \"rounded,filled\", fillcolor = \"white\", color = \"#5C715E\", fontname = \"Fira Sans\"]\n  edge[color = \"#5C715E\"]\n  bgcolor = \"#E9F1EC\"\n\n  A[label=\"Total Variability\"]\n  B[label=\"Time Variability\"]\n  C[label=\"Within-Groups Variability\"]\n  D[label=\"Subject Variability\"]\n  E[label=\"Error Variability\"]\n\n  A -> B\n  A -> C\n  C -> D\n  C -> E\n}\n```\n\n## Within-Subjects ANOVA\n\n### The key idea\n\n::: callout-tip\n## Removing the person\n\n$SS_{W} = SS_{Subjects} + SS_{Error}$\n\n$SS_{Error} = SS_{W} - SS_{Subjects}$\n:::\n\n- In between-subjects ANOVA, differences between people sit **inside** the error term.\n\n- In within-subjects ANOVA we **subtract them out**, so the error is smaller and the test is more **powerful**.\n\n## Calculating Repeated-Measures ANOVA\n\n::: callout-tip\n## The F ratio\n\n$F = \\dfrac{MS_{Time}}{MS_{Error}}$\n\n$MS_{Time} = \\dfrac{SS_{Time}}{df_{Time}} = \\dfrac{SS_{Time}}{k - 1}$\n\n$MS_{Error} = \\dfrac{SS_{W} - SS_{Subjects}}{df_{Error}} = \\dfrac{SS_{W} - SS_{Subjects}}{(n-1)(k-1)}$\n:::\n\n- $k$ is the number of time points (or conditions) and $n$ is the number of participants.\n\n## Degrees of Freedom\n\n::: callout-tip\n## Rules\n\n- Time: $df_{Time} = k - 1$\n\n- Subjects: $df_{Subjects} = n - 1$\n\n- Error: $df_{Error} = (n - 1) \\times (k - 1)$\n:::\n\n## Degrees of Freedom\n\n### Example\n\n> **20 students** rate their **stress** at **three time points** during finals week: three days before the exam, the night before, and after the exam.\n\nWhat are the df's for a one-way repeated-measures ANOVA on Time?\n\n<details>\n\n<summary>Reveal answer</summary>\n\n- $df_{Time} = 3 - 1 = 2$\n\n- $df_{Subjects} = 20 - 1 = 19$\n\n- $df_{Error} = 19 \\times 2 = 38$\n\n</details>\n\n## Pizza Study Results\n\n### The ANOVA table\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"wxadufvwzd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wxadufvwzd table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wxadufvwzd thead, #wxadufvwzd tbody, #wxadufvwzd tfoot, #wxadufvwzd tr, #wxadufvwzd td, #wxadufvwzd th {\n  border-style: none;\n}\n\n#wxadufvwzd p {\n  margin: 0;\n  padding: 0;\n}\n\n#wxadufvwzd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 26px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wxadufvwzd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wxadufvwzd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wxadufvwzd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wxadufvwzd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wxadufvwzd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wxadufvwzd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wxadufvwzd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wxadufvwzd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wxadufvwzd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wxadufvwzd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wxadufvwzd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wxadufvwzd .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wxadufvwzd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wxadufvwzd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wxadufvwzd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wxadufvwzd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wxadufvwzd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wxadufvwzd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wxadufvwzd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wxadufvwzd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wxadufvwzd .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wxadufvwzd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wxadufvwzd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wxadufvwzd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wxadufvwzd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wxadufvwzd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wxadufvwzd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wxadufvwzd .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wxadufvwzd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wxadufvwzd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wxadufvwzd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wxadufvwzd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wxadufvwzd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wxadufvwzd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wxadufvwzd .gt_left {\n  text-align: left;\n}\n\n#wxadufvwzd .gt_center {\n  text-align: center;\n}\n\n#wxadufvwzd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wxadufvwzd .gt_font_normal {\n  font-weight: normal;\n}\n\n#wxadufvwzd .gt_font_bold {\n  font-weight: bold;\n}\n\n#wxadufvwzd .gt_font_italic {\n  font-style: italic;\n}\n\n#wxadufvwzd .gt_super {\n  font-size: 65%;\n}\n\n#wxadufvwzd .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wxadufvwzd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wxadufvwzd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wxadufvwzd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wxadufvwzd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wxadufvwzd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wxadufvwzd .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wxadufvwzd .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#wxadufvwzd div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Source\">Source</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"SS\">SS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"MS\">MS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Time (condition)</td>\n<td headers=\"df\" class=\"gt_row gt_center\">2</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">105.58</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">52.79</td>\n<td headers=\"F\" class=\"gt_row gt_center\">69.19</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt;.001</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center gt_striped\">Subjects</td>\n<td headers=\"df\" class=\"gt_row gt_center gt_striped\">29</td>\n<td headers=\"SS\" class=\"gt_row gt_center gt_striped\">175.71</td>\n<td headers=\"MS\" class=\"gt_row gt_center gt_striped\">6.06</td>\n<td headers=\"F\" class=\"gt_row gt_center gt_striped\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center gt_striped\">–</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Error</td>\n<td headers=\"df\" class=\"gt_row gt_center\">58</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">44.25</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">0.76</td>\n<td headers=\"F\" class=\"gt_row gt_center\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center\">–</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n::: {.callout-tip appearance=\"minimal\"}\n$F(2, 58) = 69.19$, $p$ < .001: productivity changes significantly across the three time points.\n:::\n\n## Pizza Study Results\n\n### In R\n\n::: {.codewindow .r .codewindow-dark}\nrepeated_measures.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(afex)\n\n# id = who; within = the repeated factor\nfit <- aov_ez(id = \"id\", dv = \"y\", data = pizza,\n              within = \"cond\", return = \"afex_aov\")\n\n# the corrected ANOVA table (Greenhouse-Geisser if needed)\nanova(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type 3 tests)\n\nResponse: y\n     num Df den Df     MSE      F     ges    Pr(>F)    \ncond 1.9264 55.866 0.79209 69.189 0.32431 1.403e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n:::\n\n- `summary(fit)` also prints Mauchly's test and the other corrections.\n\n\n## Pizza Study Results\n\n### Why within-subjects helps\n\n::::::::: side-by-cols\n::::: stat-card\n::: stat-num\n69.19\n:::\n\n::: stat-sub\n**Repeated-measures** F (removes person differences)\n:::\n:::::\n\n::::: stat-card\n::: stat-num\n20.88\n:::\n\n::: stat-sub\n**Between-subjects** F (same data, ignoring the person)\n:::\n:::::\n:::::::::\n\n- The same scores give a much larger F once we account for the fact that each person was measured three times.\n\n## Repeated-Measures ANOVA\n\n### Assumptions\n\n::: callout-important\n## Assumptions\n\n- **Normality** of the differences.\n\n- **Sphericity:** the variances of all pairwise differences are about equal.\n\n  - Test: **Mauchly's Test**.\n\n- If sphericity is violated, use the **Greenhouse-Geisser correction**.\n\n  - Always check sphericity when the within-subject factor has **more than two** levels.\n:::\n\n## Repeated-Measures ANOVA\n\n### Interpretation\n\n- $F(2, 58) = 69.19$, $p$ < .001\n\n  - Main effect of time on productivity.\n\n  - Productivity changes significantly across the timepoints.\n\n    - What would be your next step?\n\n## Repeated-Measures ANOVA\n\n### Effect size\n\n::: callout-tip\n## Partial eta squared\n\n$\\eta_p^2 = \\dfrac{SS_{Time}}{SS_{Time} + SS_{Error}} = \\dfrac{105.58}{105.58 + 44.25} =0.70$\n:::\n\n- Benchmarks are the same as other ANOVAs: about .01 small, .06 medium, .14 large.\n\n## Follow-Up\n\n### Post-hoc comparisons\n\n- A significant F says that **some** time points differ, not which.\n\n- Run paired t-tests with a **Bonferroni correction**:\n\n::: {.codewindow .r .codewindow-dark}\nposthoc.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\npairwise.t.test(pizza$y, pizza$cond,\n                paired = TRUE, p.adjust.method = \"bonferroni\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using paired t tests \n\ndata:  pizza$y and pizza$cond \n\n             Before lunch 10 min after\n10 min after 1.5e-08      -           \n1 hour after 0.0086       1.4e-12     \n\nP value adjustment method: bonferroni \n```\n\n\n:::\n:::\n\n:::\n\n## Follow-Up\n\n### Reading the comparisons\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"kqubulkyqk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#kqubulkyqk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#kqubulkyqk thead, #kqubulkyqk tbody, #kqubulkyqk tfoot, #kqubulkyqk tr, #kqubulkyqk td, #kqubulkyqk th {\n  border-style: none;\n}\n\n#kqubulkyqk p {\n  margin: 0;\n  padding: 0;\n}\n\n#kqubulkyqk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 28px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 60%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#kqubulkyqk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#kqubulkyqk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#kqubulkyqk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#kqubulkyqk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kqubulkyqk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kqubulkyqk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kqubulkyqk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#kqubulkyqk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#kqubulkyqk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#kqubulkyqk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#kqubulkyqk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#kqubulkyqk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#kqubulkyqk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#kqubulkyqk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#kqubulkyqk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#kqubulkyqk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#kqubulkyqk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#kqubulkyqk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kqubulkyqk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#kqubulkyqk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#kqubulkyqk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#kqubulkyqk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kqubulkyqk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#kqubulkyqk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#kqubulkyqk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kqubulkyqk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kqubulkyqk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#kqubulkyqk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kqubulkyqk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#kqubulkyqk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kqubulkyqk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kqubulkyqk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kqubulkyqk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kqubulkyqk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kqubulkyqk .gt_left {\n  text-align: left;\n}\n\n#kqubulkyqk .gt_center {\n  text-align: center;\n}\n\n#kqubulkyqk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#kqubulkyqk .gt_font_normal {\n  font-weight: normal;\n}\n\n#kqubulkyqk .gt_font_bold {\n  font-weight: bold;\n}\n\n#kqubulkyqk .gt_font_italic {\n  font-style: italic;\n}\n\n#kqubulkyqk .gt_super {\n  font-size: 65%;\n}\n\n#kqubulkyqk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#kqubulkyqk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#kqubulkyqk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#kqubulkyqk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#kqubulkyqk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#kqubulkyqk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#kqubulkyqk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#kqubulkyqk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#kqubulkyqk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Comparison\">Comparison</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Adjusted-p\">Adjusted p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Comparison\" class=\"gt_row gt_left\">Before lunch vs. 10 min after</td>\n<td headers=\"Adjusted p\" class=\"gt_row gt_left\">&lt;.001</td></tr>\n    <tr><td headers=\"Comparison\" class=\"gt_row gt_left gt_striped\">Before lunch vs. 1 hour after</td>\n<td headers=\"Adjusted p\" class=\"gt_row gt_left gt_striped\">0.009</td></tr>\n    <tr><td headers=\"Comparison\" class=\"gt_row gt_left\">10 min after vs. 1 hour after</td>\n<td headers=\"Adjusted p\" class=\"gt_row gt_left\">&lt;.001</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n- The adjusted p-values already account for running three comparisons.\n\n## Within-Subjects ANOVA\n\n### Reporting F\n\nIf asked to report findings in terms of the Null Hypothesis (H~0~), you should report findings as:\n\n- Reject $H_0$, or\n\n- Fail to Reject $H_0$\n\n- If asked to report findings in general or for publication, you need to report $F(df_{Time}, df_{Error}) = F, p$, an effect size, and the means and standard deviations at each time point.\n\n## Within-Subjects ANOVA\n\n### Reporting the pizza study\n\n> Productivity differed significantly across the three time points, *F(2, 58) = 69.19, p < .001*, $\\eta_p^2$ = 0.70. Productivity was highest 10 minutes after pizza (*M* = 6.93, *SD* = 1.61) and lowest an hour after pizza (*M* = 4.33, *SD* = 1.60); before lunch it was *M* = 5.14 (*SD* = 1.56).\n\n## Repeated-Measures ANOVA\n\n### Example: an engagement intervention\n\n> Prof. Brocker evaluates a new **engagement intervention**. **100 students** rate their enjoyment of statistics (`1` to `10`) at the start of the semester, after week 1 of a statistics warm-up activity, and after week 2.\n\n::: {.callout-tip .nonincremental}\n## Find the degrees of freedom\n\n-   $df_{Time}$ = ?\n\n-   $df_{Subjects}$ = ?\n\n-   $df_{Error}$ = ?\n\n-   $n$ = ?\n:::\n\n## Repeated-Measures ANOVA\n\n### Engagement intervention: answers\n\n::: {.callout-important .nonincremental}\n## Degrees of freedom\n\n-   $df_{Time} = k - 1 = 3 - 1 = 2$\n\n-   $df_{Subjects} = n - 1 = 100 - 1 = 99$\n\n-   $df_{Error} = (n - 1)(k - 1) = 99 \\times 2 = 198$\n\n-   $n = 100$\n:::\n\n## Repeated-Measures ANOVA\n\n### Engagement intervention: results\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jvjlvpejdx\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jvjlvpejdx table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jvjlvpejdx thead, #jvjlvpejdx tbody, #jvjlvpejdx tfoot, #jvjlvpejdx tr, #jvjlvpejdx td, #jvjlvpejdx th {\n  border-style: none;\n}\n\n#jvjlvpejdx p {\n  margin: 0;\n  padding: 0;\n}\n\n#jvjlvpejdx .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 26px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jvjlvpejdx .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jvjlvpejdx .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jvjlvpejdx .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jvjlvpejdx .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jvjlvpejdx .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jvjlvpejdx .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jvjlvpejdx .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jvjlvpejdx .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jvjlvpejdx .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jvjlvpejdx .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jvjlvpejdx .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jvjlvpejdx .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jvjlvpejdx .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jvjlvpejdx .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jvjlvpejdx .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jvjlvpejdx .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jvjlvpejdx .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jvjlvpejdx .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jvjlvpejdx .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jvjlvpejdx .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jvjlvpejdx .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jvjlvpejdx .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jvjlvpejdx .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jvjlvpejdx .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jvjlvpejdx .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jvjlvpejdx .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jvjlvpejdx .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jvjlvpejdx .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jvjlvpejdx .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jvjlvpejdx .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jvjlvpejdx .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jvjlvpejdx .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jvjlvpejdx .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jvjlvpejdx .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jvjlvpejdx .gt_left {\n  text-align: left;\n}\n\n#jvjlvpejdx .gt_center {\n  text-align: center;\n}\n\n#jvjlvpejdx .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jvjlvpejdx .gt_font_normal {\n  font-weight: normal;\n}\n\n#jvjlvpejdx .gt_font_bold {\n  font-weight: bold;\n}\n\n#jvjlvpejdx .gt_font_italic {\n  font-style: italic;\n}\n\n#jvjlvpejdx .gt_super {\n  font-size: 65%;\n}\n\n#jvjlvpejdx .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jvjlvpejdx .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jvjlvpejdx .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jvjlvpejdx .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jvjlvpejdx .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jvjlvpejdx .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jvjlvpejdx .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jvjlvpejdx .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jvjlvpejdx div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Source\">Source</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"SS\">SS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"MS\">MS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Time (condition)</td>\n<td headers=\"df\" class=\"gt_row gt_center\">2</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">111.72</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">55.86</td>\n<td headers=\"F\" class=\"gt_row gt_center\">343.60</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt;.001</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center gt_striped\">Subjects</td>\n<td headers=\"df\" class=\"gt_row gt_center gt_striped\">99</td>\n<td headers=\"SS\" class=\"gt_row gt_center gt_striped\">769.76</td>\n<td headers=\"MS\" class=\"gt_row gt_center gt_striped\">7.78</td>\n<td headers=\"F\" class=\"gt_row gt_center gt_striped\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center gt_striped\">–</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Error</td>\n<td headers=\"df\" class=\"gt_row gt_center\">198</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">32.19</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">0.16</td>\n<td headers=\"F\" class=\"gt_row gt_center\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center\">–</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n*F(2, 198) = 343.60, p < .001*\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-10-1.png){width=576}\n:::\n:::\n\n:::\n:::::\n\n## Repeated-Measures ANOVA\n\n### Example: active-learning practices\n\n> Professor Brocker tests whether structured **active-learning practices** improve `80` students' attitudes toward statistics. He collects a `1-10` enjoyment rating at the **beginning** of the semester, **mid-semester** (after four modules), and the **end** (after eight modules).\n\n::: {.callout-tip .nonincremental}\n## Find the degrees of freedom\n\n1.  $df_{Time}$ = ?\n2.  $df_{Participants}$ = ?\n3.  $df_{Error}$ = ?\n:::\n\n## Repeated-Measures ANOVA\n\n### Active-learning practices: answers\n\n::: {.callout-important .nonincremental}\n## Degrees of freedom\n\n1.  $df_{Time} = k - 1 = 3 - 1 = 2$\n2.  $df_{Participants} = n - 1 = 80 - 1 = 79$\n3.  $df_{Error} = (n - 1)(k - 1) = 79 \\times 2 = 158$\n:::\n\n## Repeated-Measures ANOVA\n\n### Active-learning practices: results\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ttkaniyvok\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ttkaniyvok table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ttkaniyvok thead, #ttkaniyvok tbody, #ttkaniyvok tfoot, #ttkaniyvok tr, #ttkaniyvok td, #ttkaniyvok th {\n  border-style: none;\n}\n\n#ttkaniyvok p {\n  margin: 0;\n  padding: 0;\n}\n\n#ttkaniyvok .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 26px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ttkaniyvok .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ttkaniyvok .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ttkaniyvok .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ttkaniyvok .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ttkaniyvok .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ttkaniyvok .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ttkaniyvok .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ttkaniyvok .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ttkaniyvok .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ttkaniyvok .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ttkaniyvok .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ttkaniyvok .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ttkaniyvok .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ttkaniyvok .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ttkaniyvok .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ttkaniyvok .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ttkaniyvok .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ttkaniyvok .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ttkaniyvok .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ttkaniyvok .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ttkaniyvok .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ttkaniyvok .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ttkaniyvok .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ttkaniyvok .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ttkaniyvok .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ttkaniyvok .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ttkaniyvok .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ttkaniyvok .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ttkaniyvok .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ttkaniyvok .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ttkaniyvok .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ttkaniyvok .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ttkaniyvok .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ttkaniyvok .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ttkaniyvok .gt_left {\n  text-align: left;\n}\n\n#ttkaniyvok .gt_center {\n  text-align: center;\n}\n\n#ttkaniyvok .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ttkaniyvok .gt_font_normal {\n  font-weight: normal;\n}\n\n#ttkaniyvok .gt_font_bold {\n  font-weight: bold;\n}\n\n#ttkaniyvok .gt_font_italic {\n  font-style: italic;\n}\n\n#ttkaniyvok .gt_super {\n  font-size: 65%;\n}\n\n#ttkaniyvok .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ttkaniyvok .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ttkaniyvok .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ttkaniyvok .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ttkaniyvok .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ttkaniyvok .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ttkaniyvok .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ttkaniyvok .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ttkaniyvok div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Source\">Source</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"SS\">SS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"MS\">MS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Time (condition)</td>\n<td headers=\"df\" class=\"gt_row gt_center\">2</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">116.75</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">58.38</td>\n<td headers=\"F\" class=\"gt_row gt_center\">281.96</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt;.001</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center gt_striped\">Subjects</td>\n<td headers=\"df\" class=\"gt_row gt_center gt_striped\">79</td>\n<td headers=\"SS\" class=\"gt_row gt_center gt_striped\">552.90</td>\n<td headers=\"MS\" class=\"gt_row gt_center gt_striped\">7.00</td>\n<td headers=\"F\" class=\"gt_row gt_center gt_striped\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center gt_striped\">–</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Error</td>\n<td headers=\"df\" class=\"gt_row gt_center\">158</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">32.71</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">0.21</td>\n<td headers=\"F\" class=\"gt_row gt_center\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center\">–</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n*F(2, 158) = 281.96, p < .001*\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-12-1.png){width=576}\n:::\n:::\n\n:::\n:::::\n\n## Interpreting F\n\n::: callout-tip\n## What F means\n\n$MS_{Time}$ is made up of $MS_{Error}$ + the theoretical change over time:\n\n- $MS_{Time} = \\text{change over time} + MS_{Error}$\n\n- If there is no change: $MS_{Time} = 0 + MS_{Error}$, so $F = \\dfrac{MS_{Error}}{MS_{Error}} = 1$.\n\n- If there is a change: $F = 1 + \\dfrac{\\text{change}}{MS_{Error}}$, which is greater than 1.\n:::\n\n- When $F \\leq 1$, it's not likely to be significant.\n\n## Hypothesis Testing: ANOVA\n\n::: callout-tip\n## Decision rule\n\n- $F \\leq 1$: fail to reject the null hypothesis.\n\n- $F > 1$: compare to the critical value (or use the *p*-value). Reject $H_0$ only if $p < \\alpha$.\n:::\n\n## Reporting F\n\n### Active-learning example\n\n> Attitudes toward statistics differed significantly across the semester, *F(2, 158) = 281.96, p < .001*. Attitudes were highest at the end of the semester (*M* = 6.27, *SD* = 1.69) and lowest at the beginning (*M* = 4.56, *SD* = 1.42). Mid-semester attitudes were *M* = 5.45 (*SD* = 1.59).\n\n## Data Manipulation\n\n### Wide and long format\n\n- When collected, data can be in either **wide** or **long** format.\n\n- Below are the same five participants in both formats.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"udkfzwbdfx\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#udkfzwbdfx table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#udkfzwbdfx thead, #udkfzwbdfx tbody, #udkfzwbdfx tfoot, #udkfzwbdfx tr, #udkfzwbdfx td, #udkfzwbdfx th {\n  border-style: none;\n}\n\n#udkfzwbdfx p {\n  margin: 0;\n  padding: 0;\n}\n\n#udkfzwbdfx .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 22px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 60%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#udkfzwbdfx .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#udkfzwbdfx .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#udkfzwbdfx .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#udkfzwbdfx .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#udkfzwbdfx .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#udkfzwbdfx .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#udkfzwbdfx .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#udkfzwbdfx .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#udkfzwbdfx .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#udkfzwbdfx .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#udkfzwbdfx .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#udkfzwbdfx .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#udkfzwbdfx .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#udkfzwbdfx .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#udkfzwbdfx .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#udkfzwbdfx .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#udkfzwbdfx .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#udkfzwbdfx .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#udkfzwbdfx .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#udkfzwbdfx .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#udkfzwbdfx .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#udkfzwbdfx .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#udkfzwbdfx .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#udkfzwbdfx .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#udkfzwbdfx .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#udkfzwbdfx .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#udkfzwbdfx .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#udkfzwbdfx .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#udkfzwbdfx .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#udkfzwbdfx .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#udkfzwbdfx .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#udkfzwbdfx .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#udkfzwbdfx .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#udkfzwbdfx .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#udkfzwbdfx .gt_left {\n  text-align: left;\n}\n\n#udkfzwbdfx .gt_center {\n  text-align: center;\n}\n\n#udkfzwbdfx .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#udkfzwbdfx .gt_font_normal {\n  font-weight: normal;\n}\n\n#udkfzwbdfx .gt_font_bold {\n  font-weight: bold;\n}\n\n#udkfzwbdfx .gt_font_italic {\n  font-style: italic;\n}\n\n#udkfzwbdfx .gt_super {\n  font-size: 65%;\n}\n\n#udkfzwbdfx .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#udkfzwbdfx .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#udkfzwbdfx .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#udkfzwbdfx .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#udkfzwbdfx .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#udkfzwbdfx .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#udkfzwbdfx .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#udkfzwbdfx .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#udkfzwbdfx div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\" style>Wide data</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Each row is one participant</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Participant\">Participant</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Immediate\">Immediate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"After24Hours\">After24Hours</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"After1Week\">After1Week</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">1</td>\n<td headers=\"Immediate\" class=\"gt_row gt_right\">11.4</td>\n<td headers=\"After24Hours\" class=\"gt_row gt_right\">4.6</td>\n<td headers=\"After1Week\" class=\"gt_row gt_right\">4.5</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center gt_striped\">2</td>\n<td headers=\"Immediate\" class=\"gt_row gt_right gt_striped\">6.2</td>\n<td headers=\"After24Hours\" class=\"gt_row gt_right gt_striped\">7.1</td>\n<td headers=\"After1Week\" class=\"gt_row gt_right gt_striped\">8.1</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">3</td>\n<td headers=\"Immediate\" class=\"gt_row gt_right\">7.0</td>\n<td headers=\"After24Hours\" class=\"gt_row gt_right\">5.8</td>\n<td headers=\"After1Week\" class=\"gt_row gt_right\">7.4</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center gt_striped\">4</td>\n<td headers=\"Immediate\" class=\"gt_row gt_right gt_striped\">7.4</td>\n<td headers=\"After24Hours\" class=\"gt_row gt_right gt_striped\">6.2</td>\n<td headers=\"After1Week\" class=\"gt_row gt_right gt_striped\">4.5</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">5</td>\n<td headers=\"Immediate\" class=\"gt_row gt_right\">6.5</td>\n<td headers=\"After24Hours\" class=\"gt_row gt_right\">9.3</td>\n<td headers=\"After1Week\" class=\"gt_row gt_right\">6.8</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Data Manipulation\n\n### Wide and long format\n\n:::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"khqndycmux\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#khqndycmux table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#khqndycmux thead, #khqndycmux tbody, #khqndycmux tfoot, #khqndycmux tr, #khqndycmux td, #khqndycmux th {\n  border-style: none;\n}\n\n#khqndycmux p {\n  margin: 0;\n  padding: 0;\n}\n\n#khqndycmux .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 18px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 90%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#khqndycmux .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#khqndycmux .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#khqndycmux .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#khqndycmux .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#khqndycmux .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#khqndycmux .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#khqndycmux .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#khqndycmux .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#khqndycmux .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#khqndycmux .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#khqndycmux .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#khqndycmux .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#khqndycmux .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#khqndycmux .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#khqndycmux .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#khqndycmux .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#khqndycmux .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#khqndycmux .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#khqndycmux .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#khqndycmux .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#khqndycmux .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#khqndycmux .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#khqndycmux .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#khqndycmux .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#khqndycmux .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#khqndycmux .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#khqndycmux .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#khqndycmux .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#khqndycmux .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#khqndycmux .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#khqndycmux .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#khqndycmux .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#khqndycmux .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#khqndycmux .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#khqndycmux .gt_left {\n  text-align: left;\n}\n\n#khqndycmux .gt_center {\n  text-align: center;\n}\n\n#khqndycmux .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#khqndycmux .gt_font_normal {\n  font-weight: normal;\n}\n\n#khqndycmux .gt_font_bold {\n  font-weight: bold;\n}\n\n#khqndycmux .gt_font_italic {\n  font-style: italic;\n}\n\n#khqndycmux .gt_super {\n  font-size: 65%;\n}\n\n#khqndycmux .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#khqndycmux .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#khqndycmux .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#khqndycmux .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#khqndycmux .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#khqndycmux .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#khqndycmux .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#khqndycmux .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#khqndycmux div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\" style>Long data</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Each row is one participant at one time</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Participant\">Participant</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Time\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Memory\">Memory</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">1</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Immediate</td>\n<td headers=\"Memory\" class=\"gt_row gt_right\">11.4</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center gt_striped\">1</td>\n<td headers=\"Time\" class=\"gt_row gt_left gt_striped\">After24Hours</td>\n<td headers=\"Memory\" class=\"gt_row gt_right gt_striped\">4.6</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">1</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">After1Week</td>\n<td headers=\"Memory\" class=\"gt_row gt_right\">4.5</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center gt_striped\">2</td>\n<td headers=\"Time\" class=\"gt_row gt_left gt_striped\">Immediate</td>\n<td headers=\"Memory\" class=\"gt_row gt_right gt_striped\">6.2</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">2</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">After24Hours</td>\n<td headers=\"Memory\" class=\"gt_row gt_right\">7.1</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center gt_striped\">2</td>\n<td headers=\"Time\" class=\"gt_row gt_left gt_striped\">After1Week</td>\n<td headers=\"Memory\" class=\"gt_row gt_right gt_striped\">8.1</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">3</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Immediate</td>\n<td headers=\"Memory\" class=\"gt_row gt_right\">7.0</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center gt_striped\">3</td>\n<td headers=\"Time\" class=\"gt_row gt_left gt_striped\">After24Hours</td>\n<td headers=\"Memory\" class=\"gt_row gt_right gt_striped\">5.8</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">3</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">After1Week</td>\n<td headers=\"Memory\" class=\"gt_row gt_right\">7.4</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center gt_striped\">4</td>\n<td headers=\"Time\" class=\"gt_row gt_left gt_striped\">Immediate</td>\n<td headers=\"Memory\" class=\"gt_row gt_right gt_striped\">7.4</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">4</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">After24Hours</td>\n<td headers=\"Memory\" class=\"gt_row gt_right\">6.2</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center gt_striped\">4</td>\n<td headers=\"Time\" class=\"gt_row gt_left gt_striped\">After1Week</td>\n<td headers=\"Memory\" class=\"gt_row gt_right gt_striped\">4.5</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">5</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Immediate</td>\n<td headers=\"Memory\" class=\"gt_row gt_right\">6.5</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center gt_striped\">5</td>\n<td headers=\"Time\" class=\"gt_row gt_left gt_striped\">After24Hours</td>\n<td headers=\"Memory\" class=\"gt_row gt_right gt_striped\">9.3</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">5</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">After1Week</td>\n<td headers=\"Memory\" class=\"gt_row gt_right\">6.8</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n\n:::: {.column width=\"50%\"}\n::: {.codewindow .r .codewindow-dark}\npivot.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyr)\n\n# wide -> long: one row per person per time\nlong <- wide |>\n  pivot_longer(cols = !Participant,\n               names_to = \"Time\",\n               values_to = \"Memory\")\n```\n:::\n\n:::\n\n- `aov()` and `aov_ez()` need the **long** format.\n::::\n::::::\n\n## Practice\n\n### 1. Memory recall\n\n> 30 participants study a word list and recall it **immediately**, **after 24 hours**, and **after 1 week**. Does recall change over time?\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"iuvhmoiblu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#iuvhmoiblu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#iuvhmoiblu thead, #iuvhmoiblu tbody, #iuvhmoiblu tfoot, #iuvhmoiblu tr, #iuvhmoiblu td, #iuvhmoiblu th {\n  border-style: none;\n}\n\n#iuvhmoiblu p {\n  margin: 0;\n  padding: 0;\n}\n\n#iuvhmoiblu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 20px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#iuvhmoiblu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#iuvhmoiblu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#iuvhmoiblu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#iuvhmoiblu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iuvhmoiblu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iuvhmoiblu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iuvhmoiblu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#iuvhmoiblu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#iuvhmoiblu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#iuvhmoiblu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#iuvhmoiblu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#iuvhmoiblu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#iuvhmoiblu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#iuvhmoiblu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#iuvhmoiblu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#iuvhmoiblu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#iuvhmoiblu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#iuvhmoiblu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iuvhmoiblu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#iuvhmoiblu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#iuvhmoiblu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#iuvhmoiblu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iuvhmoiblu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#iuvhmoiblu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#iuvhmoiblu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iuvhmoiblu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iuvhmoiblu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#iuvhmoiblu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iuvhmoiblu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#iuvhmoiblu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iuvhmoiblu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iuvhmoiblu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iuvhmoiblu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iuvhmoiblu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iuvhmoiblu .gt_left {\n  text-align: left;\n}\n\n#iuvhmoiblu .gt_center {\n  text-align: center;\n}\n\n#iuvhmoiblu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#iuvhmoiblu .gt_font_normal {\n  font-weight: normal;\n}\n\n#iuvhmoiblu .gt_font_bold {\n  font-weight: bold;\n}\n\n#iuvhmoiblu .gt_font_italic {\n  font-style: italic;\n}\n\n#iuvhmoiblu .gt_super {\n  font-size: 65%;\n}\n\n#iuvhmoiblu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#iuvhmoiblu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#iuvhmoiblu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#iuvhmoiblu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#iuvhmoiblu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#iuvhmoiblu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#iuvhmoiblu .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#iuvhmoiblu .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#iuvhmoiblu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Source\">Source</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"SS\">SS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"MS\">MS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Time (condition)</td>\n<td headers=\"df\" class=\"gt_row gt_center\">2</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">213.74</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">106.87</td>\n<td headers=\"F\" class=\"gt_row gt_center\">102.22</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt;.001</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center gt_striped\">Subjects</td>\n<td headers=\"df\" class=\"gt_row gt_center gt_striped\">29</td>\n<td headers=\"SS\" class=\"gt_row gt_center gt_striped\">155.67</td>\n<td headers=\"MS\" class=\"gt_row gt_center gt_striped\">5.37</td>\n<td headers=\"F\" class=\"gt_row gt_center gt_striped\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center gt_striped\">–</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Error</td>\n<td headers=\"df\" class=\"gt_row gt_center\">58</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">60.64</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">1.05</td>\n<td headers=\"F\" class=\"gt_row gt_center\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center\">–</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n<details>\n\n<summary>Reveal answer</summary>\n\n*F(2, 58) = 102.22, p < .001*: recall decreased significantly over time.\n\n</details>\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-17-1.png){width=576}\n:::\n:::\n\n:::\n:::::\n\n\n## Practice\n\n### 2. Clinical trial\n\n> 30 patients each receive a **low**, **medium**, and **high** dose of a medication (in separate sessions) and report symptom improvement. Does dose matter?\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hzxjnzhprw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hzxjnzhprw table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hzxjnzhprw thead, #hzxjnzhprw tbody, #hzxjnzhprw tfoot, #hzxjnzhprw tr, #hzxjnzhprw td, #hzxjnzhprw th {\n  border-style: none;\n}\n\n#hzxjnzhprw p {\n  margin: 0;\n  padding: 0;\n}\n\n#hzxjnzhprw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 20px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hzxjnzhprw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hzxjnzhprw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hzxjnzhprw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hzxjnzhprw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hzxjnzhprw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hzxjnzhprw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hzxjnzhprw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hzxjnzhprw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hzxjnzhprw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hzxjnzhprw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hzxjnzhprw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hzxjnzhprw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hzxjnzhprw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hzxjnzhprw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hzxjnzhprw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hzxjnzhprw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hzxjnzhprw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hzxjnzhprw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hzxjnzhprw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hzxjnzhprw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hzxjnzhprw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hzxjnzhprw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hzxjnzhprw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hzxjnzhprw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hzxjnzhprw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hzxjnzhprw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hzxjnzhprw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hzxjnzhprw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hzxjnzhprw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hzxjnzhprw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hzxjnzhprw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hzxjnzhprw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hzxjnzhprw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hzxjnzhprw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hzxjnzhprw .gt_left {\n  text-align: left;\n}\n\n#hzxjnzhprw .gt_center {\n  text-align: center;\n}\n\n#hzxjnzhprw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hzxjnzhprw .gt_font_normal {\n  font-weight: normal;\n}\n\n#hzxjnzhprw .gt_font_bold {\n  font-weight: bold;\n}\n\n#hzxjnzhprw .gt_font_italic {\n  font-style: italic;\n}\n\n#hzxjnzhprw .gt_super {\n  font-size: 65%;\n}\n\n#hzxjnzhprw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hzxjnzhprw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hzxjnzhprw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hzxjnzhprw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hzxjnzhprw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hzxjnzhprw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hzxjnzhprw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hzxjnzhprw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hzxjnzhprw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Source\">Source</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"SS\">SS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"MS\">MS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Time (condition)</td>\n<td headers=\"df\" class=\"gt_row gt_center\">2</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">89.14</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">44.57</td>\n<td headers=\"F\" class=\"gt_row gt_center\">60.95</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt;.001</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center gt_striped\">Subjects</td>\n<td headers=\"df\" class=\"gt_row gt_center gt_striped\">29</td>\n<td headers=\"SS\" class=\"gt_row gt_center gt_striped\">178.95</td>\n<td headers=\"MS\" class=\"gt_row gt_center gt_striped\">6.17</td>\n<td headers=\"F\" class=\"gt_row gt_center gt_striped\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center gt_striped\">–</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Error</td>\n<td headers=\"df\" class=\"gt_row gt_center\">58</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">42.41</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">0.73</td>\n<td headers=\"F\" class=\"gt_row gt_center\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center\">–</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n<details>\n\n<summary>Reveal answer</summary>\n\n*F(2, 58) = 60.95, p < .001*: improvement increased significantly with dose.\n\n</details>\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-19-1.png){width=576}\n:::\n:::\n\n:::\n:::::\n\n\n## Practice\n\n### 3. Behavioral therapy progress\n\n> 30 participants rate their anxiety at **baseline**, **mid-treatment**, and **post-treatment**.\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"efcuipwhpr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#efcuipwhpr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#efcuipwhpr thead, #efcuipwhpr tbody, #efcuipwhpr tfoot, #efcuipwhpr tr, #efcuipwhpr td, #efcuipwhpr th {\n  border-style: none;\n}\n\n#efcuipwhpr p {\n  margin: 0;\n  padding: 0;\n}\n\n#efcuipwhpr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 20px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#efcuipwhpr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#efcuipwhpr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#efcuipwhpr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#efcuipwhpr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#efcuipwhpr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#efcuipwhpr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#efcuipwhpr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#efcuipwhpr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#efcuipwhpr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#efcuipwhpr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#efcuipwhpr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#efcuipwhpr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#efcuipwhpr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#efcuipwhpr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#efcuipwhpr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#efcuipwhpr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#efcuipwhpr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#efcuipwhpr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#efcuipwhpr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#efcuipwhpr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#efcuipwhpr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#efcuipwhpr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#efcuipwhpr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#efcuipwhpr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#efcuipwhpr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#efcuipwhpr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#efcuipwhpr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#efcuipwhpr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#efcuipwhpr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#efcuipwhpr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#efcuipwhpr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#efcuipwhpr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#efcuipwhpr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#efcuipwhpr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#efcuipwhpr .gt_left {\n  text-align: left;\n}\n\n#efcuipwhpr .gt_center {\n  text-align: center;\n}\n\n#efcuipwhpr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#efcuipwhpr .gt_font_normal {\n  font-weight: normal;\n}\n\n#efcuipwhpr .gt_font_bold {\n  font-weight: bold;\n}\n\n#efcuipwhpr .gt_font_italic {\n  font-style: italic;\n}\n\n#efcuipwhpr .gt_super {\n  font-size: 65%;\n}\n\n#efcuipwhpr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#efcuipwhpr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#efcuipwhpr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#efcuipwhpr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#efcuipwhpr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#efcuipwhpr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#efcuipwhpr .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#efcuipwhpr .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#efcuipwhpr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Source\">Source</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"SS\">SS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"MS\">MS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Time (condition)</td>\n<td headers=\"df\" class=\"gt_row gt_center\">2</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">434.22</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">217.11</td>\n<td headers=\"F\" class=\"gt_row gt_center\">101.90</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt;.001</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center gt_striped\">Subjects</td>\n<td headers=\"df\" class=\"gt_row gt_center gt_striped\">29</td>\n<td headers=\"SS\" class=\"gt_row gt_center gt_striped\">268.05</td>\n<td headers=\"MS\" class=\"gt_row gt_center gt_striped\">9.24</td>\n<td headers=\"F\" class=\"gt_row gt_center gt_striped\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center gt_striped\">–</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Error</td>\n<td headers=\"df\" class=\"gt_row gt_center\">58</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">123.58</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">2.13</td>\n<td headers=\"F\" class=\"gt_row gt_center\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center\">–</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n<details>\n\n<summary>Reveal answer</summary>\n\n*F(2, 58) = 101.90, p < .001*: anxiety decreased.\n\n</details>\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-21-1.png){width=576}\n:::\n:::\n\n:::\n:::::\n\n\n## Practice\n\n### 4. Consumer product ratings\n\n> 30 consumers each rate **three products** (A, B, and C).\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"rhfjmxgyyx\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rhfjmxgyyx table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rhfjmxgyyx thead, #rhfjmxgyyx tbody, #rhfjmxgyyx tfoot, #rhfjmxgyyx tr, #rhfjmxgyyx td, #rhfjmxgyyx th {\n  border-style: none;\n}\n\n#rhfjmxgyyx p {\n  margin: 0;\n  padding: 0;\n}\n\n#rhfjmxgyyx .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 20px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rhfjmxgyyx .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rhfjmxgyyx .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rhfjmxgyyx .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rhfjmxgyyx .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rhfjmxgyyx .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rhfjmxgyyx .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rhfjmxgyyx .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rhfjmxgyyx .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rhfjmxgyyx .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rhfjmxgyyx .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rhfjmxgyyx .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rhfjmxgyyx .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rhfjmxgyyx .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rhfjmxgyyx .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rhfjmxgyyx .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rhfjmxgyyx .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rhfjmxgyyx .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rhfjmxgyyx .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rhfjmxgyyx .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rhfjmxgyyx .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rhfjmxgyyx .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rhfjmxgyyx .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rhfjmxgyyx .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rhfjmxgyyx .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rhfjmxgyyx .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rhfjmxgyyx .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rhfjmxgyyx .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rhfjmxgyyx .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rhfjmxgyyx .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rhfjmxgyyx .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rhfjmxgyyx .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rhfjmxgyyx .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rhfjmxgyyx .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rhfjmxgyyx .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rhfjmxgyyx .gt_left {\n  text-align: left;\n}\n\n#rhfjmxgyyx .gt_center {\n  text-align: center;\n}\n\n#rhfjmxgyyx .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rhfjmxgyyx .gt_font_normal {\n  font-weight: normal;\n}\n\n#rhfjmxgyyx .gt_font_bold {\n  font-weight: bold;\n}\n\n#rhfjmxgyyx .gt_font_italic {\n  font-style: italic;\n}\n\n#rhfjmxgyyx .gt_super {\n  font-size: 65%;\n}\n\n#rhfjmxgyyx .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rhfjmxgyyx .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rhfjmxgyyx .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rhfjmxgyyx .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rhfjmxgyyx .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rhfjmxgyyx .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rhfjmxgyyx .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#rhfjmxgyyx .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#rhfjmxgyyx div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Source\">Source</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"SS\">SS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"MS\">MS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Time (condition)</td>\n<td headers=\"df\" class=\"gt_row gt_center\">2</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">73.17</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">36.58</td>\n<td headers=\"F\" class=\"gt_row gt_center\">39.80</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt;.001</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center gt_striped\">Subjects</td>\n<td headers=\"df\" class=\"gt_row gt_center gt_striped\">29</td>\n<td headers=\"SS\" class=\"gt_row gt_center gt_striped\">215.88</td>\n<td headers=\"MS\" class=\"gt_row gt_center gt_striped\">7.44</td>\n<td headers=\"F\" class=\"gt_row gt_center gt_striped\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center gt_striped\">–</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Error</td>\n<td headers=\"df\" class=\"gt_row gt_center\">58</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">53.31</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">0.92</td>\n<td headers=\"F\" class=\"gt_row gt_center\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center\">–</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n<details>\n\n<summary>Reveal answer</summary>\n\n*F(2, 58) = 39.80, p < .001*: the ratings differed by product. A post-hoc test would show which products differ.\n\n</details>\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-23-1.png){width=576}\n:::\n:::\n\n:::\n:::::\n\n\n## Practice\n\n### 5. Physiological stress\n\n> 30 participants' heart rate is measured at **rest**, during a **task**, and during **recovery**.\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vlfdpqkmlw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vlfdpqkmlw table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vlfdpqkmlw thead, #vlfdpqkmlw tbody, #vlfdpqkmlw tfoot, #vlfdpqkmlw tr, #vlfdpqkmlw td, #vlfdpqkmlw th {\n  border-style: none;\n}\n\n#vlfdpqkmlw p {\n  margin: 0;\n  padding: 0;\n}\n\n#vlfdpqkmlw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 20px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vlfdpqkmlw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vlfdpqkmlw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vlfdpqkmlw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vlfdpqkmlw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vlfdpqkmlw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vlfdpqkmlw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vlfdpqkmlw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vlfdpqkmlw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vlfdpqkmlw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vlfdpqkmlw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vlfdpqkmlw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vlfdpqkmlw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vlfdpqkmlw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vlfdpqkmlw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vlfdpqkmlw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vlfdpqkmlw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vlfdpqkmlw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vlfdpqkmlw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vlfdpqkmlw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vlfdpqkmlw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vlfdpqkmlw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vlfdpqkmlw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vlfdpqkmlw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vlfdpqkmlw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vlfdpqkmlw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vlfdpqkmlw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vlfdpqkmlw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vlfdpqkmlw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vlfdpqkmlw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vlfdpqkmlw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vlfdpqkmlw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vlfdpqkmlw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vlfdpqkmlw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vlfdpqkmlw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vlfdpqkmlw .gt_left {\n  text-align: left;\n}\n\n#vlfdpqkmlw .gt_center {\n  text-align: center;\n}\n\n#vlfdpqkmlw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vlfdpqkmlw .gt_font_normal {\n  font-weight: normal;\n}\n\n#vlfdpqkmlw .gt_font_bold {\n  font-weight: bold;\n}\n\n#vlfdpqkmlw .gt_font_italic {\n  font-style: italic;\n}\n\n#vlfdpqkmlw .gt_super {\n  font-size: 65%;\n}\n\n#vlfdpqkmlw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vlfdpqkmlw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vlfdpqkmlw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vlfdpqkmlw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vlfdpqkmlw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vlfdpqkmlw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vlfdpqkmlw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vlfdpqkmlw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vlfdpqkmlw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Source\">Source</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"SS\">SS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"MS\">MS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Time (condition)</td>\n<td headers=\"df\" class=\"gt_row gt_center\">2</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">7,027.50</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">3,513.75</td>\n<td headers=\"F\" class=\"gt_row gt_center\">215.83</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt;.001</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center gt_striped\">Subjects</td>\n<td headers=\"df\" class=\"gt_row gt_center gt_striped\">29</td>\n<td headers=\"SS\" class=\"gt_row gt_center gt_striped\">2,266.64</td>\n<td headers=\"MS\" class=\"gt_row gt_center gt_striped\">78.16</td>\n<td headers=\"F\" class=\"gt_row gt_center gt_striped\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center gt_striped\">–</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_center\">Error</td>\n<td headers=\"df\" class=\"gt_row gt_center\">58</td>\n<td headers=\"SS\" class=\"gt_row gt_center\">944.26</td>\n<td headers=\"MS\" class=\"gt_row gt_center\">16.28</td>\n<td headers=\"F\" class=\"gt_row gt_center\">–</td>\n<td headers=\"p\" class=\"gt_row gt_center\">–</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n<details>\n\n<summary>Reveal answer</summary>\n\n*F(2, 58) = 215.83, p < .001*: heart rate differed significantly across the phases.\n\n</details>\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-25-1.png){width=576}\n:::\n:::\n\n:::\n:::::\n\n\n## Summary: Within-Subjects ANOVA\n\n- Compares **three or more** related means (the same people measured repeatedly).\n\n- Splits the variability into time, subjects, and error, and **removes the subject differences** from the error term.\n\n- $F = MS_{Time} / MS_{Error}$ with $df = (k - 1,\\ (n - 1)(k - 1))$.\n\n- Check sphericity (Mauchly's Test) and use the Greenhouse-Geisser correction if it is violated.\n\n- Follow a significant $F$ with post-hoc paired comparisons (Bonferroni).\n\n- Report $F(df_{Time}, df_{Error})$, $p$, an effect size, and the means and standard deviations.",
    "supporting": [
      "lec14_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}