{
  "hash": "460d60382814a119e11390084e870aeb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Within Subjects ANOVA\"\nsubtitle: \"Lecture 14\"\nauthor: \"Dave Brocker\"\nfooter: \"⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡\"\ninstitute: \"Farmingdale State College\"\nexecute:\n  echo: true\nformat: \n  revealjs:\n    theme: custom.scss\n    scrollable: true\n    width: 1600\n    height: 900\n    incremental: true   \n    touch: true\n    chalkboard: true\n    lightbox: true\n    code-fold: true\n---\n\n\n\n\n# When to Use Repeated Measures ANOVA\n\nUse Repeated Measures ANOVA when:\n\n-   You have the **same participants measured more than once** (e.g., pre-test/post-test).\n\n-   You're interested in **changes over time** or **under different conditions**.\n\n    -   Testing whether students' enjoyment of statistics improves after receiving lollipops for 2 weeks.\n\n# Between vs. Within Subjects ANOVA\n\n-   **Between-Subjects ANOVA:**\n\n    -   Compares means **between groups** (e.g., Group A vs. Group B vs. Group C).\n\n    -   Error comes from individual differences **between people**.\n\n-   **Within-Subjects (Repeated Measures) ANOVA:**\n\n    -   Compares means **within the same participants** over time.\n\n    -   Controls for individual differences.\n\n# Pizza and Productivity Study\n\n## A Repeated-Measures Design\n\n-   Objective: Test whether productivity changes over time\n-   IV:\n    1.  Before lunch\n    2.  10 minutes after pizza\n    3.  1 hour after pizza\n-   Same participants measured at each timepoint\n-   DV:\n    -   Number of emails written in 10 minutes\n\n# Visualizing the Data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(forcats)\n\nset.seed(123)\ndata <- tibble(\n  id = rep(1:30, each = 3),\n  time = factor(rep(c(\"Pre\", \"Post10\", \"Post60\"), times = 30), ordered = TRUE),\n  productivity = c(\n    rnorm(30, mean = 5, sd = 1),\n    rnorm(30, mean = 7, sd = 1.5),\n    rnorm(30, mean = 4.5, sd = 1)\n  )\n)\n\ndata %>%\n  ggplot(aes(fct_inorder(time), productivity, group = id)) +\n  geom_point() +\n  geom_line(alpha = 0.3) +\n  stat_summary(\n    aes(group = 1), \n    fun.data = \"mean_se\", \n    geom = \"line\", \n    color = \"red\", \n    lty = \"dashed\"\n    ) +\n  labs(\n    title = \"Individual and Mean Productivity Over Time\",\n    x = \"\\nTime\",\n    y = \"Productivity (Emails Sent)\\n\"\n    ) +\n  theme_minimal() +\n  theme_sub_panel(grid = element_blank())\n```\n\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-1-1.png){width=960}\n:::\n:::\n\n\n\n\n## Why Repeated-Measures ANOVA?\n\n-   Can't use multiple paired-samples t-tests\n    -   Alpha inflation - increases Type I error\n-   Repeated-Measures ANOVA allows us to:\n    -   Compare within-subject changes across time\n    -   Control for individual variability\n    -   Test for an overall **time effect**\n\n## Repeated-Measures ANOVA\n\n### Assumptions\n\n-   **Normality** of differences\n-   **Sphericity**: Equal variances of pairwise differences\n    -   Test: **Mauchly’s Test**\n-   If assumption is violated, use **Greenhouse-Geisser correction**\n    -   Always check sphericity if more than two levels of the within-subject factor\n\n## Repeated-Measures ANOVA\n\n### Interpretation\n\n-   F(2, 58) = 12.3, p \\< .001\n    -   Main effect of time on productivity\n    -   Productivity changes significantly across timepoints\n        -   What would be your next step?\n\n## Follow-Up\n\n### Post-hoc Comparisons\n\n-   Run paired t-tests with **Bonferroni correction**\n-   Which timepoints differ?\n    -   Pre vs. Post-10 Minutes\n    -   Post-10 Minutes vs. Post-60 Minutes\n    -   Pre vs. Post-60 Minutes\n\n## ANOVA\n\n-   Between subjects ANOVA compares means **between** groups to determine if they differ significantly from one another.\n\n-   Within subjects ANOVA compares pre-manipulation means to post-manipulation means to determine if there is a difference **within** participants over time.\n\n## Within Subjects ANOVA\n\n-   Within subjects ANOVA examines differences within participants over time.\n\n-   Within subjects ANOVA is also known as Repeated Measures ANOVA, because it looks at one measure repeated over time.\n\n## Within Subjects ANOVA\n\nThe independent variable is time.\n\n-   Before intervention: baseline or pre-test\n\n-   After intervention: post-test\n\n## Within Subjects ANOVA\n\n-   Within subjects ANOVA can look at 2 or more time points.\n    -   Think about this as **conditions**\n\n## Within Subjects ANOVA\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(gt)\nlibrary(gtsummary)\nlibrary(broom)\nlibrary(afex)\n\n# Generate data for two normal distributions\nx <- seq(-6, 6, length=100)\nnull_dist <- dnorm(x, mean = 0, sd = 1)\nalt_dist <- dnorm(x, mean = 2, sd = 1)\n\ndata <- data.frame(\n  x = rep(x, 2),\n  y = c(null_dist, alt_dist),\n  hypothesis = factor(rep(c(\"Null Hypothesis\", \"Alternative Hypothesis\"), each=length(x)))\n)\n\n# Create the plot\n\nplt <- \n  ggplot(data, aes(x = x, y = y, \n                 lty = rev(hypothesis))) +\n    geom_line(aes(color = \"purple\")) +\n  theme_linedraw() + \n  labs(\n    x = \"\",\n    y = \"\",\n    lty = \"Hypotheses\"\n  ) + \n  theme(\n    panel.grid = element_blank(),\n    legend.position = \"inside\",\n    legend.position.inside = c(.2,.5),\n    legend.background = element_rect(color = \"black\")\n  ) + \n  scale_color_identity()\n\nplt\n```\n\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n\n\n## Between Subjects ANOVA\n\nIn between subjects ANOVA, we analyze two types of variance:\n\n-   **Between Group variance**: How the data varies between the groups\n\n-   **Error variance**: How the data varies across all participants\n\n## Within Subjects ANOVA\n\nIn within subjects ANOVA the variance is more complicated, because data will differ in 3 ways:\n\n-   Over time\n\n    -   How the data varies across time-points\n\n-   Error variance:\n\n    -   How the data varies across all participants\n\n-   Per participant\n\n    -   How the data varies between each person\n\n## Within Subjects ANOVA\n\n### Over Time\n\n> A person’s mood measured **before TV,** **during TV**, and **after TV** are correlated because they come from the same person\n\n## Within Subjects ANOVA\n\n### Error\n\n> Mood will have natural variance across participants and time.\n\n## Within Subjects ANOVA Example\n\n### **Per participant**\n\n> Each participant's scores will be more like *their* other scores than they are like the scores of another participant.\n\n## Within Subjects ANOVA\n\n\n\n\n```{dot}\n digraph {     \n    node[shape = \"box\", style = \"rounded\"]\n    \n      A[label=\"Total Variability\"]\n      B[label=\"Time Variability\"]\n      C[label=\"Within-Groups Variability\"]\n      D[label=\"Subject Variability\"]\n      E[label=\"Error Variability\"]\n      \n      A -> B\n      A -> C\n      C -> D\n      C -> E\n}\n```\n\n\n\n\n## Within Subjects ANOVA\n\nWhat is the F ratio in between subjects ANOVA?\n\n-   $F = \\frac{{MS_{BG}}}{MS_{Error}}$\n\n-   $MS_{BG} = \\frac{SS_{BG}}{df_{BG}}$\n\n-   $MS_{Error} = \\frac{SS_{Error}}{df_{Error}}$\n\n## Within Subjects ANOVA\n\nWe want measure 2 sources of variance:\n\n-   $SS_{Time}$\n\n    -   Similar to SS~Between~ from between subjects ANOVA\n\n-   $SS_{Error}$\n\n    -   Harder to calculate in within subjects ANOVA, because of the subject variance.\n\n## Within Subjects ANOVA\n\n-   $SS_{WG} = SS_{Subjects} + SS_{Error}$\n\n## Within Subjects ANOVA\n\n-   $SS_{W} = SS_{Subjects} + \\color{red}{SS_{Error}}$\n\n-   $SS_{Error} = SS_{W} - SS_{Subjects}$\n\n## Calculating Means Squared (MS)\n\n-   We calculate a SS for the variance between the times points ($SS_{Time}$).\n\n    -   This is just like the $SS_{BG}$ from between subjects ANOVA\n\n-   We calculate a SS for the within group variance ($SS_{W}$).\n\n-   We calculate a SS for the variance by person ($SS_{Subject}$).\n\n-   To find $SS_{Error}$, we subtract $SS_{Subjects}$ from $SS_{WG}$.\n\n## Calculating means squared (MS)\n\n-   $MS_{Time} = \\frac{SS_{Time}} {df_{Time}}$\n\n-   $MS_{Error} = \\frac{(SS_{W} - SS_{Subject})}{df_{Error}}$\n\n## Degrees of freedom\n\n-   Time $(MS_{Time}) = k - 1$\n\n-   Error $(MS_{Error}) = (n - 1) \\times (k - 1)$\n\n    -   k is the number of time points\n\n## Degrees of Freedom\n\n### Examples\n\n> A researcher measures students’ **stress levels** at **three time points** during finals week:\n>\n> a\\) Three days before the exam b) The night before the exam c) After the exam. A total of **20 students** provided stress ratings at all three times.\n\nWhat are the df's for a one-way repeated-measures ANOVA on Time?\n\n## Degrees of Freedom\n\n### Examples\n\n> A researcher measures students’ **stress levels** at **three time points** during finals week:\n>\n> a\\) Three days before the exam b) The night before the exam c) After the exam. A total of **20 students** provided stress ratings at all three times.\n\n1.  df~Time~ = 3 - 1 = 2\n2.  df~Error~ = 19\\*2 = 38\n3.  df~Subjects~ = 20-1 = 19\n\n## Calculating Repeated-Measures ANVOA\n\n-   $F = \\frac{MS_{Time}}{MS_{Error}}$\n\n-   $MS_{Time} = \\frac{SS_{Time}}{df_{Time}} = \\frac{SS_{Time}}{(k - 1)}$\n\n-   $MS_{Error} = \\frac{(SS_{W} - SS_{Subject})} {df_{Error}} = \\frac{(SS_{W}\\ - SS_{Subject})}{(n-1)\\times(k-1)}$\n\n## Repeated-Measures ANOVA\n\n### Example\n\n> Prof. Brocker wants to evaluate whether a new **engagement intervention** improves students’ attitudes toward statistics. At the beginning of the semester, **100 students** complete a survey rating how much they enjoy statistics on a scale from `1 (not at all)` to `10 (extremely)`.He then implements a two-week intervention in which each class begins with a brief **statistics-related warm-up activity** designed to increase interest and reduce anxiety. After the first week of the intervention, students rate their enjoyment of statistics again. At the end of the second week, they complete the rating a third time.\n\n-   df~Time~ =\n\n-   df~Subjects~ =\n\n-   df~Error~ =\n\n-   n =\n\n## Practice\n\n> Prof. Brocker wants to evaluate whether a new **engagement intervention** improves students’ attitudes toward statistics. At the beginning of the semester, **100 students** complete a survey rating how much they enjoy statistics on a scale from `1 (not at all)` to `10 (extremely)`.He then implements a two-week intervention in which each class begins with a brief **statistics-related warm-up activity** designed to increase interest and reduce anxiety. After the first week of the intervention, students rate their enjoyment of statistics again. At the end of the second week, they complete the rating a third time.\n\n-   df~Time~ = `3 - 1 = 2`\n\n-   df~Subjects~ = `100-1 = 99`\n\n-   df~Error~ = `(100 - 1) * (3-1) = 198`\n\n-   n = `100`\n\n## Practice\n\n> Prof. Brocker wants to evaluate whether a new **engagement intervention** improves students’ attitudes toward statistics.\n\n::::: columns\n::: {.column width=\"50%\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ez)\nlibrary(afex)\n\nset.seed(2025)  # for reproducibility\n\nn <- 100\n\n# Baseline: lower enjoyment, more variability\nbaseline <- rnorm(n, mean = 4.8, sd = 1.6)\n\n# After Week 1: slight increase\nweek1 <- baseline + rnorm(n, mean = 0.7, sd = 0.5)\n\n# After Week 2: additional increase\nweek2 <- week1 + rnorm(n, mean = 0.8, sd = 0.5)\n\n# Keep scores bounded between 1 and 10\nclip <- function(x) pmin(pmax(x, 1), 10)\nbaseline <- clip(baseline)\nweek1    <- clip(week1)\nweek2    <- clip(week2)\n\n# Construct long dataset\ndata_long <- tibble(\n  id = factor(1:n),\n  baseline = baseline,\n  week1 = week1,\n  week2 = week2\n) %>%\n  pivot_longer(cols = baseline:week2,\n               names_to = \"time\",\n               values_to = \"enjoyment\")\n\naov_ez(\n  data = data_long,\n  dv = \"enjoyment\",\n  id = \"id\",\n  within = \"time\",\n  anova_table = list(es = \"ges\"),\n  return = \"aov\"\n) |>\n  tidy() |> \n  rename(\n    Source = term,\n    SS = sumsq,\n    MS = meansq,\n    `F` = statistic, \n    p = p.value\n  ) |> \n  select(-stratum) |> \n  filter(Source == \"time\" | df == 198) |> \n  gt() |> \n  fmt_auto()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"rgekufeskj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rgekufeskj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rgekufeskj thead, #rgekufeskj tbody, #rgekufeskj tfoot, #rgekufeskj tr, #rgekufeskj td, #rgekufeskj th {\n  border-style: none;\n}\n\n#rgekufeskj p {\n  margin: 0;\n  padding: 0;\n}\n\n#rgekufeskj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rgekufeskj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rgekufeskj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rgekufeskj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rgekufeskj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rgekufeskj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rgekufeskj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rgekufeskj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rgekufeskj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rgekufeskj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rgekufeskj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rgekufeskj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rgekufeskj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rgekufeskj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rgekufeskj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rgekufeskj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rgekufeskj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rgekufeskj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rgekufeskj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rgekufeskj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rgekufeskj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rgekufeskj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rgekufeskj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rgekufeskj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rgekufeskj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rgekufeskj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rgekufeskj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rgekufeskj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rgekufeskj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rgekufeskj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rgekufeskj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rgekufeskj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rgekufeskj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rgekufeskj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rgekufeskj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rgekufeskj .gt_left {\n  text-align: left;\n}\n\n#rgekufeskj .gt_center {\n  text-align: center;\n}\n\n#rgekufeskj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rgekufeskj .gt_font_normal {\n  font-weight: normal;\n}\n\n#rgekufeskj .gt_font_bold {\n  font-weight: bold;\n}\n\n#rgekufeskj .gt_font_italic {\n  font-style: italic;\n}\n\n#rgekufeskj .gt_super {\n  font-size: 65%;\n}\n\n#rgekufeskj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rgekufeskj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rgekufeskj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rgekufeskj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rgekufeskj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rgekufeskj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rgekufeskj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#rgekufeskj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#rgekufeskj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Source\">Source</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SS\">SS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MS\">MS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Source\" class=\"gt_row gt_left\">time</td>\n<td headers=\"df\" class=\"gt_row gt_right\">  2 </td>\n<td headers=\"SS\" class=\"gt_row gt_right\">111.716</td>\n<td headers=\"MS\" class=\"gt_row gt_right\">55.858</td>\n<td headers=\"F\" class=\"gt_row gt_right\">343.599</td>\n<td headers=\"p\" class=\"gt_row gt_right\">4.101&nbsp;×&nbsp;10<sup style='font-size: 65%;'>−65</sup></td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_left\">Residuals</td>\n<td headers=\"df\" class=\"gt_row gt_right\">198 </td>\n<td headers=\"SS\" class=\"gt_row gt_right\"> 32.188</td>\n<td headers=\"MS\" class=\"gt_row gt_right\"> 0.163</td>\n<td headers=\"F\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p\" class=\"gt_row gt_right\">NA</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_long %>%\n  group_by(time) %>%\n  summarize(mean = mean(enjoyment), se = sd(enjoyment)/sqrt(n)) %>%\n  ggplot(aes(x = time, y = mean, group = 1)) +\n  geom_line(size = 1.2) +\n  geom_point(size = 3) +\n  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.1) +\n  labs(title = \"Enjoyment of Statistics Across Intervention\",\n       x = \"Time Point\",\n       y = \"Mean Enjoyment (1–10)\") +\n  theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n\n:::\n:::::\n\n## ANOVA\n\n> Professor Brocker is interested in whether structured **active-learning practices** improve `80`students’ attitudes toward statistics over time. He administers a `1–10` enjoyment rating at three points:\n>\n> 1.  **Beginning of the semester** (before any intervention).\n>\n> 2.  **After four active-learning modules** (mid-semester).\n>\n> 3.  **After eight active-learning modules** (end of the semester).\n\n1.  df~Time~ =\n2.  df~Participants~ =\n3.  df~Error~ =\n\n## Practice\n\n> Professor Brocker is interested in whether structured **active-learning practices** improve 80 students’ attitudes toward statistics over time. He administers a `1–10` enjoyment rating at three points:\n>\n> 1.  **Beginning of the semester** (before any intervention).\n>\n> 2.  **After four active-learning modules** (mid-semester).\n>\n> 3.  **After eight active-learning modules** (end of the semester).\n\n1.  df~Time~ = 3 - 1 = 2\n2.  df~Participants~ = 80 - 1 = 79\n3.  df~Error~ = 158\n\n## Practice\n\n> Professor Brocker is interested in whether structured **active-learning practices** improve 80 students’ attitudes toward statistics over time. He administers a `1–10` enjoyment rating at three points:\n\n::::: columns\n::: {.column width=\"50%\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2025)\n\nn <- 80\n\n# Attitude ratings (1–10 scale)\nbeginning <- rnorm(n, mean = 4.5, sd = 1.4)   # before any modules\nmid       <- beginning + rnorm(n, mean = 1.0, sd = 0.6)  # after 4 modules\nend       <- mid + rnorm(n, mean = 0.8, sd = 0.5)        # after 8 modules\n\n# Bound values between 1 and 10\nclip <- function(x) pmin(pmax(x, 1), 10)\n\nbeginning <- clip(beginning)\nmid       <- clip(mid)\nend       <- clip(end)\n\n# Create long dataset\ndata_long2 <- tibble(\n  id = factor(1:n),\n  beginning = beginning,\n  mid = mid,\n  end = end\n) |>\n  pivot_longer(\n    cols = beginning:end,\n    names_to = \"time\",\n    values_to = \"attitude\"\n  ) |> \n  mutate(\n    time = factor(time, \n                  levels = c(\"beginning\",\"mid\",\"end\"))\n    )\n\n# ------------------------------\n# Repeated-Measures ANOVA\n# ------------------------------\n\nrm_aov <- aov_ez(\n  id = \"id\",\n  dv = \"attitude\",\n  within = \"time\",\n  data = data_long2,\n  anova_table = list(es = \"ges\"),\n  return = \"aov\"\n)\n\n# Clean table for display\nrm_aov |>\n  tidy() |>\n  rename(\n    Source = term,\n    SS = sumsq,\n    MS = meansq,\n    `F` = statistic, \n    p = p.value\n  ) |> \n  select(!stratum) |>\n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"deaplhbeht\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#deaplhbeht table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#deaplhbeht thead, #deaplhbeht tbody, #deaplhbeht tfoot, #deaplhbeht tr, #deaplhbeht td, #deaplhbeht th {\n  border-style: none;\n}\n\n#deaplhbeht p {\n  margin: 0;\n  padding: 0;\n}\n\n#deaplhbeht .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#deaplhbeht .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#deaplhbeht .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#deaplhbeht .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#deaplhbeht .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#deaplhbeht .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#deaplhbeht .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#deaplhbeht .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#deaplhbeht .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#deaplhbeht .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#deaplhbeht .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#deaplhbeht .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#deaplhbeht .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#deaplhbeht .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#deaplhbeht .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#deaplhbeht .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#deaplhbeht .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#deaplhbeht .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#deaplhbeht .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#deaplhbeht .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#deaplhbeht .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#deaplhbeht .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#deaplhbeht .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#deaplhbeht .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#deaplhbeht .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#deaplhbeht .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#deaplhbeht .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#deaplhbeht .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#deaplhbeht .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#deaplhbeht .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#deaplhbeht .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#deaplhbeht .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#deaplhbeht .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#deaplhbeht .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#deaplhbeht .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#deaplhbeht .gt_left {\n  text-align: left;\n}\n\n#deaplhbeht .gt_center {\n  text-align: center;\n}\n\n#deaplhbeht .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#deaplhbeht .gt_font_normal {\n  font-weight: normal;\n}\n\n#deaplhbeht .gt_font_bold {\n  font-weight: bold;\n}\n\n#deaplhbeht .gt_font_italic {\n  font-style: italic;\n}\n\n#deaplhbeht .gt_super {\n  font-size: 65%;\n}\n\n#deaplhbeht .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#deaplhbeht .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#deaplhbeht .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#deaplhbeht .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#deaplhbeht .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#deaplhbeht .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#deaplhbeht .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#deaplhbeht .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#deaplhbeht div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Source\">Source</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SS\">SS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MS\">MS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Source\" class=\"gt_row gt_left\">Residuals</td>\n<td headers=\"df\" class=\"gt_row gt_right\">79</td>\n<td headers=\"SS\" class=\"gt_row gt_right\">552.89748</td>\n<td headers=\"MS\" class=\"gt_row gt_right\">6.998702</td>\n<td headers=\"F\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_left\">time</td>\n<td headers=\"df\" class=\"gt_row gt_right\">2</td>\n<td headers=\"SS\" class=\"gt_row gt_right\">116.75497</td>\n<td headers=\"MS\" class=\"gt_row gt_right\">58.377487</td>\n<td headers=\"F\" class=\"gt_row gt_right\">281.961</td>\n<td headers=\"p\" class=\"gt_row gt_right\">7.467537e-53</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_left\">Residuals</td>\n<td headers=\"df\" class=\"gt_row gt_right\">158</td>\n<td headers=\"SS\" class=\"gt_row gt_right\">32.71248</td>\n<td headers=\"MS\" class=\"gt_row gt_right\">0.207041</td>\n<td headers=\"F\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p\" class=\"gt_row gt_right\">NA</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_long2 |>\n  group_by(time) |>\n  summarize(\n    mean = mean(attitude),\n    se = sd(attitude) / sqrt(n)\n  ) |>\n  ggplot(aes(fct_inorder(time, ordered = TRUE), mean, group = 1)) +\n  geom_line(size = 1.2) +\n  geom_point(size = 3) +\n  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.1) +\n  labs(\n    title = \"Attitudes Toward Statistics Across the Semester\",\n    x = \"\\nTime Point\",\n    y = \"Mean Attitude Rating (1–10)\\n\"\n  ) +\n  theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n\n:::\n:::::\n\n## Practice\n\n### Interpreting F\n\nMS~Time~ is made up of MS~Error~ + the theoretical difference over time:\n\n-   $MS_{Time} = \\text{change over time} + MS_{Error}$\n-   $MS_{Time} = 0 + MS_{Error}$\n-   $MS_{Time} = MS_{Error}$\n-   $F = \\frac{MS_{Error}}{MS_{Error}} = 1$\n\n## Interpreting F\n\n-   When F \\<= 1, it's not likely to be significant.\n\n-   The MS~Time~ is made up of the MS~Error~ + the theoretical difference over time:\n\n    -   $MS_{Time} = \\text{change over time} + MS_{Error}$\n\n    -   $MS_{Time} = \\text{effect} + MS_{Error}$\n\n    -   $F > 1$\n\n## Hypothesis testing: ANOVA\n\n-   $F \\leq 1$\n\n    -   Fail to reject the Null Hypothesis\n\n-   $F > 1$\n\n    -   Refer to *p*-value\n\n    -   Reject the Null Hypothesis\n\n## Reporting F\n\nIf asked to report findings in terms of the Null Hypothesis (H0), you should report findings as:\n\n-   Reject H~0~, or\n\n-   Fail to Reject H~0~\n\n-   If asked to report findings in general or for publication, you need to report:\n\n    -   $F(df_{Time}, df_{Error}) = F, p$\n\n## Reporting F\n\n> Enjoyment of statistics after three weeks was significantly higher compared to enjoyment of statistics at the start of measurement, *F* (2, 158) = 281.96, *p* \\<.001\n\n-   If the results are significant, we have to also report the means and standard deviations for each time point.\n\n> Participants' enjoyment of statistics differed significant across time, *`F`*`(2, 158) = 281.96, p <.001`. Enjoyment was highest at week 2 (`M= 6.61, s = 1.77`). Enjoyment was lowest at baseline (`M  = 5.14, s  = 1.62`). Anxiety at week 1 test was `M= 5.86, s = 1.67`.\n\n## Data Manipulation\n\n-   When collected, data can be in either wide or long format.\n\n-   Below are the first five rows of the same dataset:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\n  Participant = factor(1:5),\n  Immediate = rnorm(5, mean = 8, sd = 1.5),\n  After24Hours = rnorm(5, mean = 6, sd = 1.5),\n  After1Week = rnorm(5, mean = 4, sd = 1.5)\n) |> \n  gt() |> \n  tab_header(title = \"Wide Data\",\n             subtitle = \"Each row represents an indivdual participant\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qpwsixhcby\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qpwsixhcby table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qpwsixhcby thead, #qpwsixhcby tbody, #qpwsixhcby tfoot, #qpwsixhcby tr, #qpwsixhcby td, #qpwsixhcby th {\n  border-style: none;\n}\n\n#qpwsixhcby p {\n  margin: 0;\n  padding: 0;\n}\n\n#qpwsixhcby .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qpwsixhcby .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qpwsixhcby .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qpwsixhcby .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qpwsixhcby .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qpwsixhcby .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qpwsixhcby .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qpwsixhcby .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qpwsixhcby .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qpwsixhcby .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qpwsixhcby .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qpwsixhcby .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qpwsixhcby .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qpwsixhcby .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qpwsixhcby .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qpwsixhcby .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qpwsixhcby .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qpwsixhcby .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qpwsixhcby .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qpwsixhcby .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qpwsixhcby .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qpwsixhcby .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qpwsixhcby .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qpwsixhcby .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qpwsixhcby .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qpwsixhcby .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qpwsixhcby .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qpwsixhcby .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qpwsixhcby .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qpwsixhcby .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qpwsixhcby .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qpwsixhcby .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qpwsixhcby .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qpwsixhcby .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qpwsixhcby .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qpwsixhcby .gt_left {\n  text-align: left;\n}\n\n#qpwsixhcby .gt_center {\n  text-align: center;\n}\n\n#qpwsixhcby .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qpwsixhcby .gt_font_normal {\n  font-weight: normal;\n}\n\n#qpwsixhcby .gt_font_bold {\n  font-weight: bold;\n}\n\n#qpwsixhcby .gt_font_italic {\n  font-style: italic;\n}\n\n#qpwsixhcby .gt_super {\n  font-size: 65%;\n}\n\n#qpwsixhcby .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qpwsixhcby .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qpwsixhcby .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qpwsixhcby .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qpwsixhcby .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qpwsixhcby .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qpwsixhcby .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qpwsixhcby .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#qpwsixhcby div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\" style>Wide Data</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Each row represents an indivdual participant</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Participant\">Participant</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Immediate\">Immediate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"After24Hours\">After24Hours</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"After1Week\">After1Week</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">1</td>\n<td headers=\"Immediate\" class=\"gt_row gt_right\">8.705734</td>\n<td headers=\"After24Hours\" class=\"gt_row gt_right\">5.686030</td>\n<td headers=\"After1Week\" class=\"gt_row gt_right\">5.851281</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">2</td>\n<td headers=\"Immediate\" class=\"gt_row gt_right\">6.397846</td>\n<td headers=\"After24Hours\" class=\"gt_row gt_right\">7.113822</td>\n<td headers=\"After1Week\" class=\"gt_row gt_right\">3.414249</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">3</td>\n<td headers=\"Immediate\" class=\"gt_row gt_right\">5.571551</td>\n<td headers=\"After24Hours\" class=\"gt_row gt_right\">8.255040</td>\n<td headers=\"After1Week\" class=\"gt_row gt_right\">4.175469</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">4</td>\n<td headers=\"Immediate\" class=\"gt_row gt_right\">6.417572</td>\n<td headers=\"After24Hours\" class=\"gt_row gt_right\">5.461643</td>\n<td headers=\"After1Week\" class=\"gt_row gt_right\">2.616414</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">5</td>\n<td headers=\"Immediate\" class=\"gt_row gt_right\">6.597311</td>\n<td headers=\"After24Hours\" class=\"gt_row gt_right\">4.543876</td>\n<td headers=\"After1Week\" class=\"gt_row gt_right\">2.219887</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\ndata.frame(\n  Participant = factor(1:5),\n  Immediate = rnorm(5, mean = 8, sd = 1.5),\n  Day = rnorm(5, mean = 6, sd = 1.5),\n  Week = rnorm(5, mean = 4, sd = 1.5)\n) |> \n  tidyr::pivot_longer(cols = !Participant,\n                      names_to = \"Time\",\n                      values_to = \"Stress\") |> \n  gt() |> \n  fmt_auto() |> \n  tab_header(title = \"Long Data\",\n             subtitle = \"Each row represents an indivdual participant's score on each level of the treatment\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vbspqdplen\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vbspqdplen table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vbspqdplen thead, #vbspqdplen tbody, #vbspqdplen tfoot, #vbspqdplen tr, #vbspqdplen td, #vbspqdplen th {\n  border-style: none;\n}\n\n#vbspqdplen p {\n  margin: 0;\n  padding: 0;\n}\n\n#vbspqdplen .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vbspqdplen .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vbspqdplen .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vbspqdplen .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vbspqdplen .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vbspqdplen .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vbspqdplen .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vbspqdplen .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vbspqdplen .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vbspqdplen .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vbspqdplen .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vbspqdplen .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vbspqdplen .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vbspqdplen .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vbspqdplen .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vbspqdplen .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vbspqdplen .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vbspqdplen .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vbspqdplen .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vbspqdplen .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vbspqdplen .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vbspqdplen .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vbspqdplen .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vbspqdplen .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vbspqdplen .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vbspqdplen .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vbspqdplen .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vbspqdplen .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vbspqdplen .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vbspqdplen .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vbspqdplen .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vbspqdplen .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vbspqdplen .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vbspqdplen .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vbspqdplen .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vbspqdplen .gt_left {\n  text-align: left;\n}\n\n#vbspqdplen .gt_center {\n  text-align: center;\n}\n\n#vbspqdplen .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vbspqdplen .gt_font_normal {\n  font-weight: normal;\n}\n\n#vbspqdplen .gt_font_bold {\n  font-weight: bold;\n}\n\n#vbspqdplen .gt_font_italic {\n  font-style: italic;\n}\n\n#vbspqdplen .gt_super {\n  font-size: 65%;\n}\n\n#vbspqdplen .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vbspqdplen .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vbspqdplen .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vbspqdplen .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vbspqdplen .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vbspqdplen .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vbspqdplen .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vbspqdplen .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vbspqdplen div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\" style>Long Data</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Each row represents an indivdual participant's score on each level of the treatment</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Participant\">Participant</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Time\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Stress\">Stress</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">1</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Immediate</td>\n<td headers=\"Stress\" class=\"gt_row gt_right\">6.566</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">1</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Day</td>\n<td headers=\"Stress\" class=\"gt_row gt_right\">6.58 </td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">1</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Week</td>\n<td headers=\"Stress\" class=\"gt_row gt_right\">1.127</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">2</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Immediate</td>\n<td headers=\"Stress\" class=\"gt_row gt_right\">7.219</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">2</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Day</td>\n<td headers=\"Stress\" class=\"gt_row gt_right\">7.573</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">2</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Week</td>\n<td headers=\"Stress\" class=\"gt_row gt_right\">3.645</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">3</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Immediate</td>\n<td headers=\"Stress\" class=\"gt_row gt_right\">8.333</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">3</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Day</td>\n<td headers=\"Stress\" class=\"gt_row gt_right\">7.335</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">3</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Week</td>\n<td headers=\"Stress\" class=\"gt_row gt_right\">1.699</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">4</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Immediate</td>\n<td headers=\"Stress\" class=\"gt_row gt_right\">9.193</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">4</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Day</td>\n<td headers=\"Stress\" class=\"gt_row gt_right\">6.733</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">4</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Week</td>\n<td headers=\"Stress\" class=\"gt_row gt_right\">2.172</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">5</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Immediate</td>\n<td headers=\"Stress\" class=\"gt_row gt_right\">8.013</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">5</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Day</td>\n<td headers=\"Stress\" class=\"gt_row gt_right\">7.256</td></tr>\n    <tr><td headers=\"Participant\" class=\"gt_row gt_center\">5</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Week</td>\n<td headers=\"Stress\" class=\"gt_row gt_right\">4.629</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n## Memory Recall Study\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100)\n\n# Memory Recall Study\nmemory_data <- data.frame(\n  Participant = factor(1:30),\n  Immediate = rnorm(30, mean = 8, sd = 1.5),\n  After24Hours = rnorm(30, mean = 6, sd = 1.5),\n  After1Week = rnorm(30, mean = 4, sd = 1.5)\n)\n\n# Make Data Longer\nmemory_data_long <- \n  memory_data |> \n  pivot_longer(cols = !Participant,\n                      names_to = \"Time\",\n                      values_to = \"Memory\")\n\n\naov(Memory ~ Time + Error(Participant), data = memory_data_long) |> \n  tidy() |> \n  mutate(\n    Source = term,\n    SS = sumsq,\n    MS = meansq,\n    `F` = ifelse(is.na(statistic),\"--\",statistic |> round(3)),\n    p = ifelse(p.value >.05,\"<.05\",p.value),\n    p = ifelse(is.na(p),\"--\",p)\n  ) |> \n  select(Source, df, SS, MS, `F`, p) |> \n  gt() |> \n  fmt_auto()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jddizngugi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jddizngugi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jddizngugi thead, #jddizngugi tbody, #jddizngugi tfoot, #jddizngugi tr, #jddizngugi td, #jddizngugi th {\n  border-style: none;\n}\n\n#jddizngugi p {\n  margin: 0;\n  padding: 0;\n}\n\n#jddizngugi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jddizngugi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jddizngugi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jddizngugi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jddizngugi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jddizngugi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jddizngugi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jddizngugi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jddizngugi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jddizngugi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jddizngugi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jddizngugi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jddizngugi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jddizngugi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jddizngugi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jddizngugi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jddizngugi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jddizngugi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jddizngugi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jddizngugi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jddizngugi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jddizngugi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jddizngugi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_left {\n  text-align: left;\n}\n\n#jddizngugi .gt_center {\n  text-align: center;\n}\n\n#jddizngugi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jddizngugi .gt_font_normal {\n  font-weight: normal;\n}\n\n#jddizngugi .gt_font_bold {\n  font-weight: bold;\n}\n\n#jddizngugi .gt_font_italic {\n  font-style: italic;\n}\n\n#jddizngugi .gt_super {\n  font-size: 65%;\n}\n\n#jddizngugi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jddizngugi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jddizngugi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jddizngugi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jddizngugi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jddizngugi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jddizngugi .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jddizngugi .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jddizngugi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Source\">Source</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SS\">SS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MS\">MS</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Source\" class=\"gt_row gt_left\">Residuals</td>\n<td headers=\"df\" class=\"gt_row gt_right\">29 </td>\n<td headers=\"SS\" class=\"gt_row gt_right\"> 60.124</td>\n<td headers=\"MS\" class=\"gt_row gt_right\">  2.073</td>\n<td headers=\"F\" class=\"gt_row gt_right\">--</td>\n<td headers=\"p\" class=\"gt_row gt_left\">--</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_left\">Time</td>\n<td headers=\"df\" class=\"gt_row gt_right\"> 2 </td>\n<td headers=\"SS\" class=\"gt_row gt_right\">253.722</td>\n<td headers=\"MS\" class=\"gt_row gt_right\">126.861</td>\n<td headers=\"F\" class=\"gt_row gt_right\">53.001</td>\n<td headers=\"p\" class=\"gt_row gt_left\">8.10477782732907e-14</td></tr>\n    <tr><td headers=\"Source\" class=\"gt_row gt_left\">Residuals</td>\n<td headers=\"df\" class=\"gt_row gt_right\">58 </td>\n<td headers=\"SS\" class=\"gt_row gt_right\">138.826</td>\n<td headers=\"MS\" class=\"gt_row gt_right\">  2.394</td>\n<td headers=\"F\" class=\"gt_row gt_right\">--</td>\n<td headers=\"p\" class=\"gt_row gt_left\">--</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\nmemory_data_long |> \n  ggplot(aes(Time,Memory, color = Time)) + \n    stat_summary(\n    geom = \"line\",\n    group = 1,\n    fun.data = \"mean_se\",\n    color = \"black\"\n  ) + \n    stat_summary(\n    fun.data = \"mean_se\",\n    geom = \"line\",\n    group = 1,\n    color = \"black\"\n  ) + \n  geom_jitter(alpha = .2) + \n  stat_summary(\n    geom = \"errorbar\",\n    fun.data = \"mean_se\",\n    width = .2\n  ) + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n\n\n## Clinical Trial\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100)\n\n# Clinical Trial Study\nclinical_data <- data.frame(\n  Participant = factor(1:30),\n  LowDose = rnorm(30, mean = 5, sd = 1),\n  MediumDose = rnorm(30, mean = 6.5, sd = 1),\n  HighDose = rnorm(30, mean = 8, sd = 1)\n)\n\nclinical_data_long <- \n  clinical_data |> \n  pivot_longer(\n    cols = !Participant,\n    names_to = \"Dosage\",\n    values_to = \"DV\"\n  )\n\naov(DV ~ Dosage + Error(Participant), data = clinical_data_long) |> \n  tidy() |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jddizngugi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jddizngugi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jddizngugi thead, #jddizngugi tbody, #jddizngugi tfoot, #jddizngugi tr, #jddizngugi td, #jddizngugi th {\n  border-style: none;\n}\n\n#jddizngugi p {\n  margin: 0;\n  padding: 0;\n}\n\n#jddizngugi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jddizngugi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jddizngugi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jddizngugi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jddizngugi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jddizngugi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jddizngugi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jddizngugi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jddizngugi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jddizngugi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jddizngugi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jddizngugi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jddizngugi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jddizngugi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jddizngugi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jddizngugi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jddizngugi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jddizngugi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jddizngugi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jddizngugi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jddizngugi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jddizngugi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jddizngugi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_left {\n  text-align: left;\n}\n\n#jddizngugi .gt_center {\n  text-align: center;\n}\n\n#jddizngugi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jddizngugi .gt_font_normal {\n  font-weight: normal;\n}\n\n#jddizngugi .gt_font_bold {\n  font-weight: bold;\n}\n\n#jddizngugi .gt_font_italic {\n  font-style: italic;\n}\n\n#jddizngugi .gt_super {\n  font-size: 65%;\n}\n\n#jddizngugi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jddizngugi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jddizngugi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jddizngugi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jddizngugi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jddizngugi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jddizngugi .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jddizngugi .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jddizngugi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stratum\">stratum</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sumsq\">sumsq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"meansq\">meansq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"stratum\" class=\"gt_row gt_left\">Participant</td>\n<td headers=\"term\" class=\"gt_row gt_left\">Residuals</td>\n<td headers=\"df\" class=\"gt_row gt_right\">29</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">26.72174</td>\n<td headers=\"meansq\" class=\"gt_row gt_right\">0.9214392</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"stratum\" class=\"gt_row gt_left\">Within</td>\n<td headers=\"term\" class=\"gt_row gt_left\">Dosage</td>\n<td headers=\"df\" class=\"gt_row gt_right\">2</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">128.73321</td>\n<td headers=\"meansq\" class=\"gt_row gt_right\">64.3666071</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">60.50637</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">6.394066e-15</td></tr>\n    <tr><td headers=\"stratum\" class=\"gt_row gt_left\">Within</td>\n<td headers=\"term\" class=\"gt_row gt_left\">Residuals</td>\n<td headers=\"df\" class=\"gt_row gt_right\">58</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">61.70033</td>\n<td headers=\"meansq\" class=\"gt_row gt_right\">1.0637988</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\nclinical_data_long |> \n  ggplot(aes(Dosage,DV, color = Dosage)) + \n    stat_summary(\n    geom = \"line\",\n    group = 1,\n    fun.data = \"mean_se\",\n    color = \"black\"\n  ) + \n    stat_summary(\n    fun.data = \"mean_se\",\n    geom = \"line\",\n    group = 1,\n    color = \"black\"\n  ) + \n  geom_jitter(alpha = .2) + \n  stat_summary(\n    geom = \"errorbar\",\n    fun.data = \"mean_se\",\n    width = .2\n  ) + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n\n\n\n## Behavioral Therapy Progress\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100)\n\n# Behavioral Therapy Study\ntherapy_data <- data.frame(\n  Participant = factor(1:30),\n  Baseline = rnorm(30, mean = 10, sd = 2),\n  MidTreatment = rnorm(30, mean = 7, sd = 2),\n  PostTreatment = rnorm(30, mean = 5, sd = 2)\n)\n\ntherapy_data_long <- \n  therapy_data |> \n  pivot_longer(\n    cols = !Participant,\n    names_to = \"Treatment_Group\",\n    values_to = \"DV\"\n  )\n\naov_ez(\n  \"Participant\",\n  \"DV\",\n  therapy_data_long, \n  within = \"Treatment_Group\",\n  anova_table = list(correction = \"none\"),\n  return = \"nice\"\n) |> gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jddizngugi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jddizngugi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jddizngugi thead, #jddizngugi tbody, #jddizngugi tfoot, #jddizngugi tr, #jddizngugi td, #jddizngugi th {\n  border-style: none;\n}\n\n#jddizngugi p {\n  margin: 0;\n  padding: 0;\n}\n\n#jddizngugi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jddizngugi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jddizngugi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jddizngugi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jddizngugi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jddizngugi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jddizngugi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jddizngugi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jddizngugi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jddizngugi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jddizngugi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jddizngugi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jddizngugi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jddizngugi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jddizngugi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jddizngugi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jddizngugi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jddizngugi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jddizngugi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jddizngugi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jddizngugi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jddizngugi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jddizngugi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_left {\n  text-align: left;\n}\n\n#jddizngugi .gt_center {\n  text-align: center;\n}\n\n#jddizngugi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jddizngugi .gt_font_normal {\n  font-weight: normal;\n}\n\n#jddizngugi .gt_font_bold {\n  font-weight: bold;\n}\n\n#jddizngugi .gt_font_italic {\n  font-style: italic;\n}\n\n#jddizngugi .gt_super {\n  font-size: 65%;\n}\n\n#jddizngugi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jddizngugi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jddizngugi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jddizngugi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jddizngugi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jddizngugi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jddizngugi .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jddizngugi .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jddizngugi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Effect\">Effect</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MSE\">MSE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ges\">ges</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Effect\" class=\"gt_row gt_left\">Treatment_Group</td>\n<td headers=\"df\" class=\"gt_row gt_right\">2, 58</td>\n<td headers=\"MSE\" class=\"gt_row gt_right\">4.26</td>\n<td headers=\"F\" class=\"gt_row gt_right\">46.88 ***</td>\n<td headers=\"ges\" class=\"gt_row gt_right\">.530</td>\n<td headers=\"p.value\" class=\"gt_row gt_left\">&lt;.001</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\ntherapy_data_long |> \n  ggplot(aes(Treatment_Group,DV,color = Treatment_Group)) +\n  geom_jitter(alpha = .2) + \n  stat_summary(\n    fun.data = \"mean_se\",\n    geom = \"errorbar\",\n    width = .2\n  ) + \n  stat_summary(\n    fun.data = \"mean_se\",\n    geom = \"line\",\n    group = 1,\n    color = \"black\"\n  ) + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n\n\n\n## 4. Consumer Product Ratings\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100)\n\n# Consumer Product Study\nproduct_data <- data.frame(\n  Participant = factor(1:30),\n  ProductA = rnorm(30, mean = 6, sd = 1),\n  ProductB = rnorm(30, mean = 7, sd = 1),\n  ProductC = rnorm(30, mean = 5, sd = 1)\n)\n\nproduct_data_long <- \n  product_data |> \n  pivot_longer(cols = !Participant,\n                      names_to = \"products\",\n                      values_to = \"ratings\")\n\naov(ratings ~ products + Error(Participant), data = product_data_long) |>\n  tidy() |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jddizngugi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jddizngugi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jddizngugi thead, #jddizngugi tbody, #jddizngugi tfoot, #jddizngugi tr, #jddizngugi td, #jddizngugi th {\n  border-style: none;\n}\n\n#jddizngugi p {\n  margin: 0;\n  padding: 0;\n}\n\n#jddizngugi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jddizngugi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jddizngugi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jddizngugi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jddizngugi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jddizngugi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jddizngugi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jddizngugi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jddizngugi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jddizngugi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jddizngugi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jddizngugi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jddizngugi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jddizngugi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jddizngugi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jddizngugi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jddizngugi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jddizngugi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jddizngugi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jddizngugi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jddizngugi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jddizngugi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jddizngugi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_left {\n  text-align: left;\n}\n\n#jddizngugi .gt_center {\n  text-align: center;\n}\n\n#jddizngugi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jddizngugi .gt_font_normal {\n  font-weight: normal;\n}\n\n#jddizngugi .gt_font_bold {\n  font-weight: bold;\n}\n\n#jddizngugi .gt_font_italic {\n  font-style: italic;\n}\n\n#jddizngugi .gt_super {\n  font-size: 65%;\n}\n\n#jddizngugi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jddizngugi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jddizngugi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jddizngugi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jddizngugi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jddizngugi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jddizngugi .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jddizngugi .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jddizngugi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stratum\">stratum</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sumsq\">sumsq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"meansq\">meansq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"stratum\" class=\"gt_row gt_left\">Participant</td>\n<td headers=\"term\" class=\"gt_row gt_left\">Residuals</td>\n<td headers=\"df\" class=\"gt_row gt_right\">29</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">26.72174</td>\n<td headers=\"meansq\" class=\"gt_row gt_right\">0.9214392</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"stratum\" class=\"gt_row gt_left\">Within</td>\n<td headers=\"term\" class=\"gt_row gt_left\">products</td>\n<td headers=\"df\" class=\"gt_row gt_right\">2</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">68.46662</td>\n<td headers=\"meansq\" class=\"gt_row gt_right\">34.2333084</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">32.18025</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">3.961105e-10</td></tr>\n    <tr><td headers=\"stratum\" class=\"gt_row gt_left\">Within</td>\n<td headers=\"term\" class=\"gt_row gt_left\">Residuals</td>\n<td headers=\"df\" class=\"gt_row gt_right\">58</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">61.70033</td>\n<td headers=\"meansq\" class=\"gt_row gt_right\">1.0637988</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\nproduct_data_long |> \n  ggplot(aes(products,ratings,fill = products)) + \n  stat_summary(\n    fun = \"mean\",\n    geom = \"bar\",\n    width = .5\n  ) +\n  stat_summary(\n    fun.data = \"mean_se\",\n    geom = \"errorbar\",\n    width = .2\n  ) + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n\n\n\n## 5. Physiological Stress Study\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100)\n\n# Physiological Stress Study\nstress_data <- data.frame(\n  Participant = factor(1:30),\n  Rest = rnorm(30, mean = 50, sd = 5),\n  Task = rnorm(30, mean = 70, sd = 5),\n  Recovery = rnorm(30, mean = 55, sd = 5)\n)\n\nstress_data_long <- \n  stress_data |> \n  pivot_longer(cols = !Participant,\n                      names_to = \"Time\",\n                      values_to = \"Stress\")\n\naov(Stress ~ Time + Error(Participant), data = stress_data_long) |>\n  tidy() |> \n  gt() |> \n  fmt_auto()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jddizngugi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jddizngugi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jddizngugi thead, #jddizngugi tbody, #jddizngugi tfoot, #jddizngugi tr, #jddizngugi td, #jddizngugi th {\n  border-style: none;\n}\n\n#jddizngugi p {\n  margin: 0;\n  padding: 0;\n}\n\n#jddizngugi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jddizngugi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jddizngugi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jddizngugi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jddizngugi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jddizngugi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jddizngugi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jddizngugi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jddizngugi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jddizngugi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jddizngugi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jddizngugi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jddizngugi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jddizngugi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jddizngugi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jddizngugi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jddizngugi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jddizngugi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jddizngugi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jddizngugi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jddizngugi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jddizngugi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jddizngugi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jddizngugi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jddizngugi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jddizngugi .gt_left {\n  text-align: left;\n}\n\n#jddizngugi .gt_center {\n  text-align: center;\n}\n\n#jddizngugi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jddizngugi .gt_font_normal {\n  font-weight: normal;\n}\n\n#jddizngugi .gt_font_bold {\n  font-weight: bold;\n}\n\n#jddizngugi .gt_font_italic {\n  font-style: italic;\n}\n\n#jddizngugi .gt_super {\n  font-size: 65%;\n}\n\n#jddizngugi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jddizngugi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jddizngugi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jddizngugi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jddizngugi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jddizngugi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jddizngugi .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jddizngugi .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jddizngugi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stratum\">stratum</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sumsq\">sumsq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"meansq\">meansq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"stratum\" class=\"gt_row gt_left\">Participant</td>\n<td headers=\"term\" class=\"gt_row gt_left\">Residuals</td>\n<td headers=\"df\" class=\"gt_row gt_right\">29 </td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">  668.043</td>\n<td headers=\"meansq\" class=\"gt_row gt_right\">   23.036</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"stratum\" class=\"gt_row gt_left\">Within</td>\n<td headers=\"term\" class=\"gt_row gt_left\">Time</td>\n<td headers=\"df\" class=\"gt_row gt_right\"> 2 </td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">6,802.717</td>\n<td headers=\"meansq\" class=\"gt_row gt_right\">3,401.358</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">127.895</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">5.456&nbsp;×&nbsp;10<sup style='font-size: 65%;'>−22</sup></td></tr>\n    <tr><td headers=\"stratum\" class=\"gt_row gt_left\">Within</td>\n<td headers=\"term\" class=\"gt_row gt_left\">Residuals</td>\n<td headers=\"df\" class=\"gt_row gt_right\">58 </td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">1,542.508</td>\n<td headers=\"meansq\" class=\"gt_row gt_right\">   26.595</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\nstress_data_long |> \n  ggplot(aes(Time,Stress,color = Time)) + \n  geom_jitter(alpha = .2) + \n  stat_summary(\n    fun.data = \"mean_se\",\n    geom = \"errorbar\",\n    width = .2\n  ) + \n  stat_summary(\n    fun.data = \"mean_se\",\n    geom = \"line\",\n    group = 1) + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lec14_files/figure-revealjs/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n",
    "supporting": [
      "lec14_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}