{
  "hash": "c36f00813a0483b61dc2dfe9236ec7b7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Independent-Samples T-Test\"\nsubtitle: \"PSY 348: Lecture 11\"\nauthor: \"Dave Brocker\"\ninstitute: \"Farmingdale State College\"\nfooter: \"Independent-Samples T-Test | ⬡⬢⬡⬢⬡⬢\"\nformat:\n  revealjs:\n    theme: ../custom.scss\n    incremental: true\n    touch: true\n    chalkboard: true\n    lightbox: true\n    scrollable: true\n    code-fold: true\n    slide-number: c/t\n    include-after-body: ../title-bg.html\n    width: 1600\n    height: 900\n    drop:\n      engine: webr\nrevealjs-plugins:\n  - drop\n  - codewindow\n---\n\n\n\n## From Paired to Independent Samples\n\nLast time, we compared **two related means**: the *same participants* measured twice (e.g., stress before vs. after a mindfulness program).\n\nNow, we'll compare **two unrelated means**: *different participants* in each group.\n\n| Paired t-test                          | Independent t-test             |\n|----------------------------------------|--------------------------------|\n| Same people                            | Different people               |\n| Within-subjects                        | Between-subjects               |\n| Reduces error (individual differences) | Must estimate error separately |\n\n## From Paired to Independent Samples\n\n### Visual comparison\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec11_files/figure-revealjs/unnamed-chunk-2-1.png){width=1152}\n:::\n:::\n\n\n## Sampling Theory (Recap)\n\n### Comparing two unrelated groups\n\n- Sampling theory lets us test two unrelated groups.\n\n- Under $H_0$ the **difference** between group means is centered on 0. Under $H_A$ it is centered somewhere else.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec11_files/figure-revealjs/unnamed-chunk-3-1.png){width=1056}\n:::\n:::\n\n\n## Sampling Theory (Recap)\n\n### A difference near 0 looks like the null\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec11_files/figure-revealjs/unnamed-chunk-4-1.png){width=1056}\n:::\n:::\n\n\n- An observed difference like this is easy to produce when $H_0$ is true.\n\n## Sampling Theory (Recap)\n\n### A difference beyond the critical value does not\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec11_files/figure-revealjs/unnamed-chunk-5-1.png){width=1056}\n:::\n:::\n\n\n- Beyond the critical value, the observed difference would be very unusual under $H_0$, so we **reject** it.\n\n## Inferential Statistics\n\n### Applied to independent groups\n\n- Our goal is still to test whether a difference is likely due to chance.\n\n- With independent samples, chance variation now includes **differences between individuals** in *both* groups.\n\n## Group Variance\n\n### Within and between\n\n::::: columns\n::: {.column width=\"50%\"}\nTo compare the means we need to know:\n\n- **Between-group variance:** how much the answers from the **experimental** group differ from the **control** group.\n\n- **Within-group variance:** how much the **answers of all participants** differ from one another.\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec11_files/figure-revealjs/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n:::\n:::::\n\n## Independent-Samples t-Test Overview\n\nUsed when we compare **two different groups** on a continuous outcome.\n\n:::::: badge-row\n::: content-badge\n[local_cafe]{.material-icons}\n\n#### Coffee vs. decaf\n\nHappiness scores\n:::\n\n::: content-badge\n[headphones]{.material-icons}\n\n#### Music vs. silence\n\nStudy performance\n:::\n\n::: content-badge\n[smartphone]{.material-icons}\n\n#### Phone vs. no phone\n\nSleep quality before bed\n:::\n::::::\n\n- **Goal:** is the mean difference between groups larger than what we'd expect by chance?\n\n## Independent-Samples t-Test\n\n### Example\n\n> The experimental group drinks caffeinated coffee. The control group drinks decaf. I ask both groups to complete a survey to measure their happiness on a scale of `1` to `10`.\n\n- The experimental group has a mean happiness score of `8`.\n\n- The control group has a mean happiness score of `6`.\n\n::: fragment\nIs the group that drank coffee significantly happier than the control group?\n:::\n\n## Formulas\n\n### Theoretical and computational\n\nInferential statistics have both **theoretical** and **computational** formulas:\n\n::::: columns\n::: {.column width=\"50%\"}\n::: callout-tip\n## Theoretical\n\nThe formula if we actually knew the population parameters ($\\sigma$).\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: callout-important\n## Computational\n\nThe formula for estimating the test statistic based solely on sample data.\n:::\n:::\n:::::\n\n## Theoretical Formula\n\n### If we knew the population standard deviation\n\n$$z = \\frac{\\color{red}{\\bar{x}_1} - \\color{orange}{\\bar{x}_2}}{\\color{grey}{\\sigma\\sqrt{\\frac{1}{n_1} + \\frac{1}{n_2}}}}$$\n\n- [Sample mean, group 1]{style=\"color:red\"}\n\n- [Sample mean, group 2]{style=\"color:orange\"}\n\n- [Standard error of the difference]{style=\"color:grey\"}, using the population $\\sigma$ (assumed equal in both groups)\n\n## Computational Formula\n\n### Estimating from the samples (pooled t-test)\n\n$$t = \\frac{\\bar{x}_1 - \\bar{x}_2}{\\sqrt{\\color{darkblue}{s_p^2}\\left(\\frac{1}{n_1} + \\frac{1}{n_2}\\right)}} \\qquad s_p^2 = \\frac{(n_1 - 1)s_1^2 + (n_2 - 1)s_2^2}{n_1 + n_2 - 2}$$\n\n- [$s_p^2$ = pooled variance]{style=\"color: darkblue\"}, a weighted average of the two group variances.\n\n- $df = n_1 + n_2 - 2$\n\n## Computational Formula\n\n### When the variances are not equal (Welch's t-test)\n\n$$t = \\frac{\\bar{x}_1 - \\bar{x}_2}{\\sqrt{\\frac{s_1^2}{n_1} + \\frac{s_2^2}{n_2}}}$$\n\n- No pooling: each group's variance keeps its own weight, and df is adjusted (it is usually not a whole number).\n\n- This is what `t.test()` does **by default** in R. Adding `var.equal = TRUE` gives the pooled version above.\n\n## Coffee Example\n\n### Manual\n\n::: callout-tip\n## Pooled variance and standard error\n\n$s_p^2 = \\dfrac{(10-1)(1)^2 + (10-1)(1)^2}{10 + 10 - 2} = 1.00$ and $SE = \\sqrt{1.00\\left(\\frac{1}{10} + \\frac{1}{10}\\right)} = 0.45$\n:::\n\n::: callout-tip\n## Compute t\n\n$t = \\dfrac{8 - 6}{0.45} = 4.47$\n:::\n\n::: callout-tip\n## Decide\n\n$df = 10 + 10 - 2 = 18$. At $\\alpha = .05$ (two-tailed), $t_{critical} = \\pm 2.101$. Since $4.47 > 2.101$, we **reject** $H_0$.\n:::\n\n## Coffee Example\n\n### Data overview\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"pejxgyrike\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#pejxgyrike table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#pejxgyrike thead, #pejxgyrike tbody, #pejxgyrike tfoot, #pejxgyrike tr, #pejxgyrike td, #pejxgyrike th {\n  border-style: none;\n}\n\n#pejxgyrike p {\n  margin: 0;\n  padding: 0;\n}\n\n#pejxgyrike .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 30px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 80%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#pejxgyrike .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#pejxgyrike .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#pejxgyrike .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#pejxgyrike .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pejxgyrike .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pejxgyrike .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pejxgyrike .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#pejxgyrike .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#pejxgyrike .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#pejxgyrike .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#pejxgyrike .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#pejxgyrike .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#pejxgyrike .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#pejxgyrike .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pejxgyrike .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#pejxgyrike .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#pejxgyrike .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#pejxgyrike .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pejxgyrike .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#pejxgyrike .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#pejxgyrike .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#pejxgyrike .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pejxgyrike .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#pejxgyrike .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#pejxgyrike .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pejxgyrike .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pejxgyrike .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#pejxgyrike .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pejxgyrike .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#pejxgyrike .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pejxgyrike .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pejxgyrike .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pejxgyrike .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pejxgyrike .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pejxgyrike .gt_left {\n  text-align: left;\n}\n\n#pejxgyrike .gt_center {\n  text-align: center;\n}\n\n#pejxgyrike .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#pejxgyrike .gt_font_normal {\n  font-weight: normal;\n}\n\n#pejxgyrike .gt_font_bold {\n  font-weight: bold;\n}\n\n#pejxgyrike .gt_font_italic {\n  font-style: italic;\n}\n\n#pejxgyrike .gt_super {\n  font-size: 65%;\n}\n\n#pejxgyrike .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#pejxgyrike .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#pejxgyrike .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#pejxgyrike .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#pejxgyrike .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#pejxgyrike .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#pejxgyrike .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#pejxgyrike .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#pejxgyrike div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"mdiff\">mdiff</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"t\">t</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Experimental\">Experimental</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Control\">Control</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"CI[ll,uu]\">CI[ll,uu]</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"mdiff\" class=\"gt_row gt_right\">2.00</td>\n<td headers=\"t\" class=\"gt_row gt_right\">4.47</td>\n<td headers=\"df\" class=\"gt_row gt_right\">18</td>\n<td headers=\"p\" class=\"gt_row gt_left\">&lt;.001</td>\n<td headers=\"Experimental\" class=\"gt_row gt_right\">8.00</td>\n<td headers=\"Control\" class=\"gt_row gt_right\">6.00</td>\n<td headers=\"CI[ll,uu]\" class=\"gt_row gt_left\">[1.06, 2.94]</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n- `mdiff` is the experimental mean minus the control mean ($8 - 6 = 2$). The factor levels set the order, so put the group you want **first** to get a positive difference.\n\n## Independent-Samples t-Test\n\n### Assumptions\n\n::: callout-important\n## Assumptions\n\n1.  **DV is continuous** (interval or ratio scale).\n2.  **Observations are independent**, and the data are randomly sampled. Each person appears in only one group.\n3.  **Normality:** each group's distribution is approximately normal (or the groups are large enough for the CLT).\n4.  **Homogeneity of variance:** variances are similar across groups (tested with **Levene's Test**).\n:::\n\n## Interpreting Levene's Test\n\n- Levene's Test tells us whether the assumption of equal variances holds.\n\n  - If $p > .05$ → use the **top row** (\"Equal variances assumed\")\n\n  - If $p < .05$ → use the **bottom row** (\"Equal variances not assumed\")\n\n- Normality: each group's distribution should be approximately normal.\n\n## Independent-Samples t-Test\n\n### Homogeneity of variance\n\n![](images/spiderman.png){style=\"border-radius: 20px;\" width=\"300\"}\n\n::: fragment\nIf **Levene's Test** is significant, use the t value from the second row and its corresponding significance.\n:::\n\n- t is the test statistic.\n\n- Sig. (2-tailed) is the p-value.\n\n## Why Do We Care?\n\nWe need **Levene's Test** because if the variance of the experimental group is not equal to the variance of the control group, pooling the two variances is not appropriate. We switch to the unpooled (**Welch**) version of the test, which does not assume equal variances.\n\n- A significant Levene's Test means a significant difference in the variances.\n\n## Let's Apply It\n\n### Three independent designs\n\nWe'll test three common between-subjects designs:\n\n:::::: badge-row\n::: content-badge\n[cookie]{.material-icons}\n\n#### Chocolate and Concentration\n\nExperimental vs. control\n:::\n\n::: content-badge\n[headphones]{.material-icons}\n\n#### Music and Studying\n\nEnvironmental manipulation\n:::\n\n::: content-badge\n[smartphone]{.material-icons}\n\n#### Phone Use and Sleep\n\nBehavioral difference\n:::\n::::::\n\n## Does chocolate improve concentration?\n\n### Design\n\n> 50 undergraduate students from XYZ University were randomly assigned to one of two groups. One group received a small piece of chocolate (70% dark cocoa) to consume before completing a 10-minute concentration task. The other group received no chocolate. The task measured sustained attention and was scored on a 0-20 scale.\n\n- **IV:** chocolate (yes vs. no)\n\n- **DV:** concentration task score\n\n- **Design:** between-subjects, randomized\n\n## Does chocolate improve concentration?\n\n### Hypotheses\n\n::::: columns\n::: {.column width=\"50%\"}\n::: callout-tip\n## Null hypothesis $H_0$\n\nConcentration is the same with and without chocolate.\n\n$\\mu_\\text{chocolate} = \\mu_\\text{no chocolate}$\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: callout-important\n## Alternative hypothesis $H_A$\n\nConcentration differs between the groups.\n\n$\\mu_\\text{chocolate} \\neq \\mu_\\text{no chocolate}$\n:::\n:::\n:::::\n\n## Does chocolate improve concentration?\n\n### Data and results\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec11_files/figure-revealjs/unnamed-chunk-8-1.png){width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"znzgqmzxhm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#znzgqmzxhm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#znzgqmzxhm thead, #znzgqmzxhm tbody, #znzgqmzxhm tfoot, #znzgqmzxhm tr, #znzgqmzxhm td, #znzgqmzxhm th {\n  border-style: none;\n}\n\n#znzgqmzxhm p {\n  margin: 0;\n  padding: 0;\n}\n\n#znzgqmzxhm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 22px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#znzgqmzxhm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#znzgqmzxhm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#znzgqmzxhm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#znzgqmzxhm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#znzgqmzxhm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#znzgqmzxhm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#znzgqmzxhm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#znzgqmzxhm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#znzgqmzxhm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#znzgqmzxhm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#znzgqmzxhm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#znzgqmzxhm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#znzgqmzxhm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#znzgqmzxhm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#znzgqmzxhm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#znzgqmzxhm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#znzgqmzxhm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#znzgqmzxhm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#znzgqmzxhm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#znzgqmzxhm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#znzgqmzxhm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#znzgqmzxhm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#znzgqmzxhm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#znzgqmzxhm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#znzgqmzxhm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#znzgqmzxhm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#znzgqmzxhm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#znzgqmzxhm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#znzgqmzxhm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#znzgqmzxhm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#znzgqmzxhm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#znzgqmzxhm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#znzgqmzxhm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#znzgqmzxhm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#znzgqmzxhm .gt_left {\n  text-align: left;\n}\n\n#znzgqmzxhm .gt_center {\n  text-align: center;\n}\n\n#znzgqmzxhm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#znzgqmzxhm .gt_font_normal {\n  font-weight: normal;\n}\n\n#znzgqmzxhm .gt_font_bold {\n  font-weight: bold;\n}\n\n#znzgqmzxhm .gt_font_italic {\n  font-style: italic;\n}\n\n#znzgqmzxhm .gt_super {\n  font-size: 65%;\n}\n\n#znzgqmzxhm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#znzgqmzxhm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#znzgqmzxhm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#znzgqmzxhm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#znzgqmzxhm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#znzgqmzxhm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#znzgqmzxhm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#znzgqmzxhm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#znzgqmzxhm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Difference\">Difference</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"t\">t</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"CI[ll,uu]\">CI[ll,uu]</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"d\">d</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Difference\" class=\"gt_row gt_right\">2.39</td>\n<td headers=\"t\" class=\"gt_row gt_right\">3.71</td>\n<td headers=\"df\" class=\"gt_row gt_right\">48</td>\n<td headers=\"p\" class=\"gt_row gt_left\">&lt;.001</td>\n<td headers=\"CI[ll,uu]\" class=\"gt_row gt_left\">[1.10, 3.69]</td>\n<td headers=\"d\" class=\"gt_row gt_right\">1.05</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nChocolate: $M = 15.38$, $SD = 2.61$. No chocolate: $M = 12.98$, $SD = 1.89$.\n:::\n:::::\n\n## Does chocolate improve concentration?\n\n### Check the assumptions, then run the test\n\n::: {.codewindow .r .codewindow-dark}\nchocolate.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(car)\n\n# Equal variances? (H0: the variances are equal)\nleveneTest(concentration ~ group, data = choco)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  1  1.4945 0.2275\n      48               \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n# Pooled (equal variances) t-test\nt.test(concentration ~ group, data = choco, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  concentration by group\nt = 3.7076, df = 48, p-value = 0.000542\nalternative hypothesis: true difference in means between group chocolate and group no_chocolate is not equal to 0\n95 percent confidence interval:\n 1.095202 3.690462\nsample estimates:\n   mean in group chocolate mean in group no_chocolate \n                  15.37507                   12.98224 \n```\n\n\n:::\n:::\n\n:::\n\n- Levene's $p > .05$, so equal variances are reasonable and the pooled test is appropriate.\n\n## Does chocolate improve concentration?\n\n### Decision, effect size, and report\n\n::::: columns\n::: {.column width=\"50%\"}\n::: callout-tip\n## Decide\n\n$t(48) = 3.71$, $p$ < .001. Since $p < .05$, we **reject** $H_0$.\n:::\n\n::: callout-tip\n## Effect size\n\n$d = \\dfrac{\\bar{x}_1 - \\bar{x}_2}{s_p} = \\dfrac{2.39}{2.28} = 1.05$ (a **large** effect)\n:::\n:::\n\n::: {.column width=\"50%\"}\n> An independent-samples t-test showed that students who ate chocolate (*M* = 15.38, *SD* = 2.61) scored significantly higher on the concentration task than students who did not (*M* = 12.98, *SD* = 1.89), [*t(48) = 3.71, p < .001*]{.hl}, 95% CI [1.10, 3.69], *d* = 1.05.\n:::\n:::::\n\n## Does instrumental music improve studying?\n\n### Design\n\n> **Design Summary**\\\n> 40 students participated in a study examining how background music affects studying. Participants were randomly assigned to study a short academic text under one of two conditions: instrumental music or silence. After 15 minutes of study time, they completed a 10-item multiple-choice quiz.\n\n- **IV:** study condition (instrumental music vs. silence)\n\n- **DV:** quiz performance (number of correct answers out of 10)\n\n- **Design:** between-subjects, randomized\n\n## Does instrumental music improve studying?\n\n### Hypotheses\n\n::::: columns\n::: {.column width=\"50%\"}\n::: callout-tip\n## Null hypothesis $H_0$\n\nQuiz performance is the same with music and in silence.\n\n$\\mu_\\text{music} = \\mu_\\text{silence}$\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: callout-important\n## Alternative hypothesis $H_A$\n\nQuiz performance differs between the conditions.\n\n$\\mu_\\text{music} \\neq \\mu_\\text{silence}$\n:::\n:::\n:::::\n\n## Does instrumental music improve studying?\n\n### Data and results\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec11_files/figure-revealjs/unnamed-chunk-11-1.png){width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"rwmcllaffp\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rwmcllaffp table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rwmcllaffp thead, #rwmcllaffp tbody, #rwmcllaffp tfoot, #rwmcllaffp tr, #rwmcllaffp td, #rwmcllaffp th {\n  border-style: none;\n}\n\n#rwmcllaffp p {\n  margin: 0;\n  padding: 0;\n}\n\n#rwmcllaffp .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 22px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rwmcllaffp .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rwmcllaffp .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rwmcllaffp .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rwmcllaffp .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rwmcllaffp .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rwmcllaffp .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rwmcllaffp .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rwmcllaffp .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rwmcllaffp .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rwmcllaffp .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rwmcllaffp .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rwmcllaffp .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rwmcllaffp .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rwmcllaffp .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rwmcllaffp .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rwmcllaffp .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rwmcllaffp .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rwmcllaffp .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rwmcllaffp .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rwmcllaffp .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rwmcllaffp .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rwmcllaffp .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rwmcllaffp .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rwmcllaffp .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rwmcllaffp .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rwmcllaffp .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rwmcllaffp .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rwmcllaffp .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rwmcllaffp .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rwmcllaffp .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rwmcllaffp .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rwmcllaffp .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rwmcllaffp .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rwmcllaffp .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rwmcllaffp .gt_left {\n  text-align: left;\n}\n\n#rwmcllaffp .gt_center {\n  text-align: center;\n}\n\n#rwmcllaffp .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rwmcllaffp .gt_font_normal {\n  font-weight: normal;\n}\n\n#rwmcllaffp .gt_font_bold {\n  font-weight: bold;\n}\n\n#rwmcllaffp .gt_font_italic {\n  font-style: italic;\n}\n\n#rwmcllaffp .gt_super {\n  font-size: 65%;\n}\n\n#rwmcllaffp .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rwmcllaffp .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rwmcllaffp .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rwmcllaffp .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rwmcllaffp .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rwmcllaffp .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rwmcllaffp .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#rwmcllaffp .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#rwmcllaffp div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Difference\">Difference</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"t\">t</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"CI[ll,uu]\">CI[ll,uu]</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"d\">d</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Difference\" class=\"gt_row gt_right\">0.60</td>\n<td headers=\"t\" class=\"gt_row gt_right\">1.73</td>\n<td headers=\"df\" class=\"gt_row gt_right\">38</td>\n<td headers=\"p\" class=\"gt_row gt_right\">0.091</td>\n<td headers=\"CI[ll,uu]\" class=\"gt_row gt_left\">[-0.10, 1.30]</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.55</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nMusic: $M = 7.65$, $SD = 1.08$. Silence: $M = 7.05$, $SD = 1.11$.\n:::\n:::::\n\n## Does instrumental music improve studying?\n\n### Run the test\n\n::: {.codewindow .r .codewindow-dark}\nmusic.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nt.test(quiz_score ~ group, data = music, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  quiz_score by group\nt = 1.7335, df = 38, p-value = 0.09112\nalternative hypothesis: true difference in means between group music and group silence is not equal to 0\n95 percent confidence interval:\n -0.1004822  1.2980566\nsample estimates:\n  mean in group music mean in group silence \n             7.647986              7.049199 \n```\n\n\n:::\n:::\n\n:::\n\n## Does instrumental music improve studying?\n\n### Decision, effect size, and report\n\n::::: columns\n::: {.column width=\"50%\"}\n::: callout-tip\n## Decide\n\n$t(38) = 1.73$, $p$ = .091. Since $p > .05$, we **fail to reject** $H_0$.\n:::\n\n::: callout-tip\n## Effect size\n\n$d = \\dfrac{0.60}{1.09} = 0.55$ (a **medium** effect)\n:::\n:::\n\n::: {.column width=\"50%\"}\n> An independent-samples t-test showed that students who studied with music (*M* = 7.65, *SD* = 1.08) did not differ significantly on the quiz from students who studied in silence (*M* = 7.05, *SD* = 1.11), [*t(38) = 1.73, p = .091*]{.hl}, 95% CI [-0.10, 1.30], *d* = 0.55.\n:::\n:::::\n\n::: {.callout-tip appearance=\"minimal\"}\nA medium effect that is *not* significant is a hint that the study may have been too small to detect it. (If we had predicted a *direction* before collecting data, the one-tailed $p$ would be about 0.046. But the direction has to be chosen **before** you see the result.)\n:::\n\n## Does bedtime phone use affect sleep?\n\n### Design\n\n> **Design Summary**\\\n> 80 students from XYZ University took part in a study on sleep and cell phone use. Participants were randomly assigned to one of two conditions. One group was instructed to avoid phone use for 30 minutes before bed, while the other used their phones as normal. The next morning, all students rated their sleep quality on a 1-10 scale.\n\n- **IV:** phone use before bed (yes vs. no)\n\n- **DV:** sleep quality rating (1 = poor, 10 = excellent)\n\n- **Design:** between-subjects, randomized\n\n## Does bedtime phone use affect sleep?\n\n### Hypotheses\n\n::::: columns\n::: {.column width=\"50%\"}\n::: callout-tip\n## Null hypothesis $H_0$\n\nSleep quality is the same with and without bedtime phone use.\n\n$\\mu_\\text{no phone} = \\mu_\\text{phone}$\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: callout-important\n## Alternative hypothesis $H_A$\n\nSleep quality differs between the conditions.\n\n$\\mu_\\text{no phone} \\neq \\mu_\\text{phone}$\n:::\n:::\n:::::\n\n## Does bedtime phone use affect sleep?\n\n### Data and results\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec11_files/figure-revealjs/unnamed-chunk-14-1.png){width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xayzuwmmbn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xayzuwmmbn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xayzuwmmbn thead, #xayzuwmmbn tbody, #xayzuwmmbn tfoot, #xayzuwmmbn tr, #xayzuwmmbn td, #xayzuwmmbn th {\n  border-style: none;\n}\n\n#xayzuwmmbn p {\n  margin: 0;\n  padding: 0;\n}\n\n#xayzuwmmbn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 22px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xayzuwmmbn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xayzuwmmbn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xayzuwmmbn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xayzuwmmbn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xayzuwmmbn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xayzuwmmbn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xayzuwmmbn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xayzuwmmbn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xayzuwmmbn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xayzuwmmbn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xayzuwmmbn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xayzuwmmbn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xayzuwmmbn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xayzuwmmbn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xayzuwmmbn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xayzuwmmbn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xayzuwmmbn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xayzuwmmbn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xayzuwmmbn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xayzuwmmbn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xayzuwmmbn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xayzuwmmbn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xayzuwmmbn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xayzuwmmbn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xayzuwmmbn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xayzuwmmbn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xayzuwmmbn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xayzuwmmbn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xayzuwmmbn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xayzuwmmbn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xayzuwmmbn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xayzuwmmbn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xayzuwmmbn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xayzuwmmbn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xayzuwmmbn .gt_left {\n  text-align: left;\n}\n\n#xayzuwmmbn .gt_center {\n  text-align: center;\n}\n\n#xayzuwmmbn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xayzuwmmbn .gt_font_normal {\n  font-weight: normal;\n}\n\n#xayzuwmmbn .gt_font_bold {\n  font-weight: bold;\n}\n\n#xayzuwmmbn .gt_font_italic {\n  font-style: italic;\n}\n\n#xayzuwmmbn .gt_super {\n  font-size: 65%;\n}\n\n#xayzuwmmbn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xayzuwmmbn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xayzuwmmbn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xayzuwmmbn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xayzuwmmbn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xayzuwmmbn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xayzuwmmbn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xayzuwmmbn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xayzuwmmbn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Difference\">Difference</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"t\">t</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"CI[ll,uu]\">CI[ll,uu]</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"d\">d</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Difference\" class=\"gt_row gt_right\">0.44</td>\n<td headers=\"t\" class=\"gt_row gt_right\">1.89</td>\n<td headers=\"df\" class=\"gt_row gt_right\">78</td>\n<td headers=\"p\" class=\"gt_row gt_right\">0.062</td>\n<td headers=\"CI[ll,uu]\" class=\"gt_row gt_left\">[-0.02, 0.90]</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.42</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nNo phone: $M = 7.34$, $SD = 0.97$. Phone: $M = 6.90$, $SD = 1.09$.\n:::\n:::::\n\n## Does bedtime phone use affect sleep?\n\n### Run the test\n\n::: {.codewindow .r .codewindow-dark}\nsleep.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nt.test(sleep_quality ~ group, data = sleep, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  sleep_quality by group\nt = 1.89, df = 78, p-value = 0.06248\nalternative hypothesis: true difference in means between group no_phone and group phone is not equal to 0\n95 percent confidence interval:\n -0.02330214  0.89639501\nsample estimates:\nmean in group no_phone    mean in group phone \n              7.341146               6.904599 \n```\n\n\n:::\n:::\n\n:::\n\n## Does bedtime phone use affect sleep?\n\n### Decision, effect size, and report\n\n::::: columns\n::: {.column width=\"50%\"}\n::: callout-tip\n## Decide\n\n$t(78) = 1.89$, $p$ = .062. Since $p > .05$, we **fail to reject** $H_0$. The result is close, but not significant.\n:::\n\n::: callout-tip\n## Effect size\n\n$d = \\dfrac{0.44}{1.03} = 0.42$ (a **small-to-medium** effect)\n:::\n:::\n\n::: {.column width=\"50%\"}\n> An independent-samples t-test showed that students who avoided their phones before bed (*M* = 7.34, *SD* = 0.97) did not differ significantly in sleep quality from students who used their phones (*M* = 6.90, *SD* = 1.09), [*t(78) = 1.89, p = .062*]{.hl}, 95% CI [-0.02, 0.90], *d* = 0.42.\n:::\n:::::\n\n## Practice\n\n### Caffeine and alertness\n\n> Does caffeine increase alertness? 40 participants were randomly assigned to caffeine or a placebo (`ex_3`: `Group`, `Alertness`; 20 per group). Alertness was scored on a 0-100 scale.\n\n1.  State $H_0$ and $H_A$.\n2.  Check the equal-variance assumption (Levene's Test).\n3.  Run the independent-samples t-test, compute $d$, and write an APA sentence.\n\n::: {.codewindow .r .codewindow-dark}\npractice_3.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nset.seed(103)\nex_3 <- tibble(\n  Group = factor(rep(c(\"Caffeine\", \"Placebo\"), each = 20),\n                 levels = c(\"Caffeine\", \"Placebo\")),\n  Alertness = c(rnorm(20, mean = 75, sd = 8), rnorm(20, mean = 68, sd = 8))\n)\n```\n:::\n\n:::\n\n<details>\n\n<summary>Reveal answer</summary>\n\n$H_0: \\mu_\\text{caffeine} = \\mu_\\text{placebo}$; $H_A: \\mu_\\text{caffeine} \\neq \\mu_\\text{placebo}$. Caffeine $M = 74.31$ vs. placebo $M = 68.23$: *t(38) = 2.52, p = .016*, 95% CI [1.19, 10.98], $d = 0.80$.\n\n</details>\n\n## Practice\n\n### Online vs. in-person exams\n\n> Do exam scores differ between online and in-person sections? 25 students in each format took the same exam (`ex_4`: `Format`, `Exam_Score`).\n\n1.  State $H_0$ and $H_A$.\n2.  Check the equal-variance assumption (Levene's Test).\n3.  Run the independent-samples t-test, compute $d$, and decide.\n\n::: {.codewindow .r .codewindow-dark}\npractice_4.R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nset.seed(104)\nex_4 <- tibble(\n  Format = factor(rep(c(\"Online\", \"InPerson\"), each = 25),\n                  levels = c(\"Online\", \"InPerson\")),\n  Exam_Score = c(rnorm(25, mean = 82, sd = 5), rnorm(25, mean = 79, sd = 6))\n)\n```\n:::\n\n:::\n\n<details>\n\n<summary>Reveal answer</summary>\n\n$H_0: \\mu_\\text{online} = \\mu_\\text{in-person}$; $H_A: \\mu_\\text{online} \\neq \\mu_\\text{in-person}$. Online $M = 81.99$ vs. in-person $M = 78.52$: *t(48) = 2.70, p = .009*, $d = 0.76$. Compare $p$ to $\\alpha = .05$ and interpret both the decision and the effect size.\n\n</details>\n\n## Summary: Independent-Samples t-Test\n\n- Compares **two independent groups**.\n\n- Tests whether the difference in means is significant.\n\n- Uses **pooled variance** as the denominator when variances are equal (**Welch** when they are not).\n\n- Check assumptions: independence, normality, equal variance (Levene's Test).\n\n- Report the test, the means and SDs, the confidence interval, and an **effect size** ($d$).\n",
    "supporting": [
      "lec11_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}